### PR TITLE
Docker tests and updates

### PR DESCRIPTION
**Pull request by nbrady-techempower**
### Updates

Added common dev libraries to tfb/base

### Haskell

- [x] snap
- [x] wai
- [x] yesod
- [x] servant
- [x] spock

### Nim

 - [x] jester

### Rust

- [x] hyper
- [x] iron
- [x] nickel
- [x] rouille
- [x] tokio-minihttp
- [x] may-minihttp

Removed/commented out actix from testing for now, added TODO note in framework directory.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@fafhrd91 if you had some time, could you take a look at the actix output from the docker branch. All the other rust frameworks are passing, but actix seems to be stuck on the `mio_uds` package.

**Comment by fafhrd91** [comment]
@nbrady-techempower sure

**Comment by fafhrd91** [comment]
@nbrady-techempower i can not find how can I get actix output?

**Comment by nbrady-techempower** [comment]
@fafhrd91 here's a run from travis from this PR https://api.travis-ci.org/v3/job/349380470/log.txt

**Comment by fafhrd91** [comment]
i do not see anything obvious. seems download process just stuck.

i updated all deps for actix in #3363  maybe this will help

**Comment by nbrady-techempower** [comment]
@fafhrd91 Thanks. It gets stuck there every time. If your deps update PR passes ill merge it into this branch

**Comment by fafhrd91** [comment]
i think problem is not "mio-uds", but what happen after that. in #3363 job starts compiling packages https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/349490184#L1813

is it possible something related how rustc is installed?

**Comment by nbrady-techempower** [comment]
@fafhrd91 that's quite possible. I'll investigate

**Pull request merged**
