### PR TITLE
Add unic framework

### PR DESCRIPTION
**Pull request by rajkumardusad**
Add [unic framework](https://github.com/unicframework/unic) benchmark

### CODE REVIEW

**Review by joanhey — CHANGES_REQUESTED** [review]
Please install the framework with composer or git.
Only the files used for the benchmark would be in this repo.

**Comment by rajkumardusad** [comment]
> Please install the framework with composer or git.
> Only the files used for the benchmark would be in this repo.

I have installed this framework with composer

**Comment by joanhey** [comment]
You need to install it in the dockerfile.

Example:
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/cakephp/cakephp.dockerfile#L21

**Comment by rajkumardusad** [comment]
> You need to install it in the dockerfile.
> 
> Example:
> https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/cakephp/cakephp.dockerfile#L21

I have done it this way.

**Comment by joanhey** [comment]
The core files don't need to be in this repo.

**Comment by rajkumardusad** [comment]
> The core files don't need to be in this repo.

But when we use `composer create-project unicframework/unic myproject` it will create a project structure that includes the core files.
I mean all core files comes with the framework itself, it cannot be installed explicitly.

**Comment by nbrady-techempower** [comment]
> But when we use composer create-project unicframework/unic myproject it will create a project structure that includes the core files.

This happens inside the dockerfile. None of those files need to be included in this PR. Can you remove the unnecessary files please?

**Pull request closed without merging**
