### PR TITLE
[Kotlin/Hexagon] Upgrade version and add support files

### PR DESCRIPTION
**Pull request by jaguililla**
* Upgrades Hexagon version
* Improves tests (light load testing). Testing is only done locally not at Dockerfiles
* Update dependencies
* Add support files (required to execute the tests locally before filing a PR).

### CODE REVIEW

**Comment by jaguililla** [comment]
Sorry for the CI job error, the problem is already fixed :)

**Comment by nbrady-techempower** [comment]
Looks like you have a `/data` directory with your own database scripts. Those have to be removed here.

**Comment by jaguililla** [comment]
I did the required changes. Thanks!

**Comment by jaguililla** [comment]
The CI job seems to be hung, clicking at the details it appears as OK.

**Pull request merged**
