### PR TITLE
Added openswoole

### PR DESCRIPTION
**Pull request by doubaokun**

### CODE REVIEW

**Comment by doubaokun** [comment]
@nbrady-techempower Could you please merge this PR?

**Comment by nbrady-techempower** [comment]
@doubaokun I will review shortly, but not on the weekends ;)

**Comment by joanhey** [comment]
From what I know, Swoole is now OpenSwoole. 
So it's the same. 
I'll be better to change the name in the Swoole, the code is exactly the same.
But remember that if you change the name, Swoole will disappear from the history. 
Well, It will be better to change only the `display_name` in `benchmark_config.json` and the `Readme`, so the history will be preserved.

**Comment by doubaokun** [comment]
@joanhey I few devs from the community still like to develop on the old Swoole and we like to leave it as is, so please merge this PR. Thanks.

**Pull request merged**
