### PR TITLE
fix: broken postgres dockerfile

### PR DESCRIPTION
**Pull request by billywhizz**
Fixes https://github.com/TechEmpower/FrameworkBenchmarks/issues/6050

### CODE REVIEW

**Review by sebastienros — COMMENTED** [review]
Definitely better than my PR, thanks

**Comment by nbrady-techempower** [comment]
Hmm saw this after @sebastienros's PR

**Comment by jcheron** [comment]
the package list must be updated, otherwise we get a 404 error:

```bash
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release  -sc || cat /etc/*-release|grep -oP  'CODENAME=\K\w+$'|head -1)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
```
It is also necessary to remove the hard-coded reference to `pgdg.list`

**Comment by billywhizz** [comment]
@jcheron i am not seeing a 404 error when i build from this dockerfile. can you explain a bit more what you are seeing? @nbrady-techempower i was thinking it would be better to stick on v12 of postgres until you make an official decision on migrating to 12 and folks have a chance to make any changes they need to. happy for you to close this PR if you think is not working/needed.

this is the log file from my local build of this dockerfile: https://gist.github.com/billywhizz/73ba054007413ad8b8514b5f1a3beecb

**Comment by jcheron** [comment]
> @jcheron i am not seeing a 404 error when i build from this dockerfile. can you explain a bit more what you are seeing? 
@billywhizz 
this one:
image

**Comment by billywhizz** [comment]
@jcheron this is not happening for me. i have tried on my laptop and on a remote machine with a clean docker. it builds fine for me as you can see from the log i posted above.

**Comment by jcheron** [comment]
@billywhizz 
It's ok after cleaning up the docker images!

**Comment by billywhizz** [comment]
i'm closing this as it seems the other PR to upgrade to v 13 of postgres has been merged

**Pull request closed without merging**
