### PR TITLE
Python turbogears

### PR DESCRIPTION
**Pull request by knewmanTE**
Added [TurboGears](http://turbogears.org/) Framework tests.

### CODE REVIEW

**Comment by LadyMozzarella** [comment]
I tried running turbogears locally here, but am getting errors:

```bash
INFO:root:Sleeping 60 seconds to ensure framework is ready
Server turbogears: [2015-04-15 17:30:42 +0000] [11159] [ERROR] Exception in worker process:
Server turbogears: Traceback (most recent call last):
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
Server turbogears:     worker.init_process()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
Server turbogears:     self.wsgi = self.app.wsgi()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Server turbogears:     self.callable = self.load()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
Server turbogears:     return self.load_wsgiapp()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
Server turbogears:     return util.import_app(self.app_uri)
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
Server turbogears:     __import__(module)
Server turbogears:   File "/FrameworkBenchmarks/frameworks/Python/turbogears/app.py", line 17, in <module>
Server turbogears:     from models.Fortune import Fortune
Server turbogears: ImportError: No module named models.Fortune
Server turbogears: Traceback (most recent call last):
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
Server turbogears:     worker.init_process()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
Server turbogears:     self.wsgi = self.app.wsgi()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
Server turbogears:     self.callable = self.load()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
Server turbogears:     return self.load_wsgiapp()
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
Server turbogears:     return util.import_app(self.app_uri)
Server turbogears:   File "/home/vagrant/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
Server turbogears:     __import__(module)
Server turbogears:   File "/FrameworkBenchmarks/frameworks/Python/turbogears/app.py", line 17, in <module>
Server turbogears:     from models.Fortune import Fortune
Server turbogears: ImportError: No module named models.Fortune
Server turbogears: [2015-04-15 17:30:42 +0000] [11159] [INFO] Worker exiting (pid: 11159)
```

**Comment by knewmanTE** [comment]
I removed an init file for the models that I didn't think was necessary. I'll try adding it back in and see if that helps.

**Comment by LadyMozzarella** [comment]
:+1: Look good. I'm only getting a `warn` here for en empty response at `/updates?queries=501` due to an empty response.

**Comment by knewmanTE** [comment]
That's odd. When I test /updates?queries=501 locally, it returns 500 results, as it should.

**Comment by LadyMozzarella** [comment]
hmm.. maybe Travis will get the results back correctly and there's just something funny over here? Wait for another (automated) opinion?

**Comment by knewmanTE** [comment]
Yeah, let's see what Travis thinks.

**Comment by LadyMozzarella** [comment]
It was totally fine on Travis. Must have been something funky in my set up. :)

**Pull request merged**
