### PR TITLE
Add h2o.cr (Crystal bindings to h2o)

### PR DESCRIPTION
**Pull request by S-YOU**
Add h2o.cr (Crystal bindings to h2o)
Tests: Plaintext only (for now)
Maintainer: Me

### CODE REVIEW

**Comment by faustinoaq** [comment]
@S-YOU Thank you so much! :sparkles: :smile:

**Comment by michaelhixson** [comment]
We need the source code of test implementations to live in this repository.  It looks like the source currently lives here instead:  https://github.com/S-YOU/h2o.cr/blob/master/examples/h2o_evloop_hello.cr

Could you copy the implementation into this repository and change the dockerfile so that it uses that copy instead of the external copy?

**Comment by S-YOU** [comment]
Thanks @michaelhixson, I have copied the file to this repository. Please take a look.

**Comment by michaelhixson** [comment]
Great, thanks!

**Pull request merged**
