### PR TITLE
Updated TreeFrog to version 1.12.0 and added setup for MongoDB and PostgreSQL

### PR DESCRIPTION
**Pull request by treefrogframework**
Updated treefrog to version 1.12.0.
Added setup for MongoDB and PostgreSQL.
Other bugfixes.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Thank you @treefrogframework ! This passed all local test and as soon as travis agrees on this branch we'll get this merged in!

**Comment by nbrady-techempower** [comment]
@treefrogframework once this passes, I'm going to merge it in. I was wondering if you would mind doing another commit to .gitignore all the changes that are made after running the tests.

**Comment by nbrady-techempower** [comment]
Relevant tests passed! Thanks again!

**Comment by treefrogframework** [comment]
Thank you, too!

**Pull request merged**
