### PR TITLE
[Java/Servlet] Modify servlet-mapping tags in web.xml to use url-pattern not somethi…

### PR DESCRIPTION
**Pull request by zloster**
…ng propriatory as url-regexp.

Modify web.xml to comform to WebApp 2.4 XML schema

This pull request is replacing #2327

### CODE REVIEW

**Comment by zloster** [comment]
There is a problem with Resin and the deployment descriptor. I'm trying to understand what's going on.

**Comment by zloster** [comment]
Now everything works as expected on a local test run.

**Comment by knewmanTE** [comment]
@zloster, the Postgres Fortunes test is failing. It looks like there's a typo in the [benchmark_config.json](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/servlet/benchmark_config.json#L50) that was also in the old [web.xml](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/servlet/src/main/webapp/WEB-INF/web.xml#L39), but now that you've updated web.xml, the test is failing. If you fix the typo in `benchmark_config.json`, that should solve the problem.

**Comment by zloster** [comment]
@knewmanTE Thank you for your help.

Updated and this time I've run the correct test entry locally (`dropwizard-postgres`). Embarrassingly previously I've run only the `dropwizard` test which only calls the `MySQL` endpoints.

**Pull request merged**
