### PR TITLE
Remove sabina

### PR DESCRIPTION
**Pull request by jaguililla**
Delete Sabina benchmark as the project is unmaintained (I'm the framework's developer).

### CODE REVIEW

**Comment by jaguililla** [comment]
retest this please

**Comment by jaguililla** [comment]
Retest this please!

**Comment by msmith-techempower** [comment]
Please remove the Kotlin stuff from this pull request.

**Comment by jaguililla** [comment]
The Kotlin code was removed, sorry for missing that!

**Comment by nbrady-techempower** [comment]
Hi @jaguililla Same with this PR! Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Pull request closed without merging**
