### PR TITLE
Round 14: Tweaking of Fintrospect implementation and JVM params

### PR DESCRIPTION
**Pull request by daviddenton**

### CODE REVIEW

**Comment by knewmanTE** [comment]
This looks good to me! Sorry for the inconvenience, and thanks for being so understanding about the branch changes!

**Comment by daviddenton** [comment]
No problem. Keep up the great work :)

**Comment by martin-g** [comment]
It seems this PR removed the impl for Fortunes test.
Was this intentional? Neither the title nor the description mention this.

**Comment by daviddenton** [comment]
It was intentional. The fortunes test didn't run anyway, so I thought I'd tidy it up and take another run at it later. :)

**Comment by martin-g** [comment]
Why Scala devs prefer to remove the implementation instead of fixing/improving it ?
Same with Play and Akka-HTTP/Spray (https://twitter.com/rolandkuhn/status/704620217104736256).
This doesn't leave good impression!

**Comment by daviddenton** [comment]
I can't comment on other cases, but i think it's better to not have broken code sitting around that might be mistaken for working code, especially when said code is meant to be an example for other devs to follow.

I'll look at reimplementing it in due course.

**Pull request merged**
