### PR TITLE
add: Nim's web framework "mofuw"

### PR DESCRIPTION
**Pull request by 2vg**
add: Nim's web framework "mofuw".
I pray that no problems will occur this time lol.

### CODE REVIEW

**Comment by 2vg** [comment]
I do not know the cause, but I pass the first test, but the same problem as before is happening the second time.
Do not merge this pull request yet as it builds in debug mode to investigate the problem.

**Comment by 2vg** [comment]
... I understood the cause
The time update function for the Date header is executed for after 1 second the server is started, but the problem occurred because the benchmark was executed earlier than updating the first time at time.
I fixed it.

**Comment by 2vg** [comment]
yeee, all ok. It can be merged !!!

**Comment by nbrady-techempower** [comment]
Awesome!

**Pull request merged**
