### PR TITLE
[ci fw-only Java/act] update to actframework r1.4.13

### PR DESCRIPTION
**Pull request by greenlaw110**

### CODE REVIEW

**Comment by greenlaw110** [comment]
@nbrady-techempower it looks like the failure tests are all mysql related. I suppose it is caused by the mysql configuration. Can we get this PR merged ?

**Comment by nbrady-techempower** [comment]
@greenlaw110 Would you mind rebasing this off master so we can get a travis run with our mysql config fix

**Comment by greenlaw110** [comment]
@nbrady-techempower I've merged from upstream/master but it looks like it's getting worse a lot of framework test failure due to `Server did not respond to request`

**Comment by nbrady-techempower** [comment]
@greenlaw110 these look mostly related to #3040 and should be fixed now. Thanks!

**Comment by greenlaw110** [comment]
@nbrady-techempower I merged upstream/master and looks like mysql database testing is still failing:

image

**Comment by nbrady-techempower** [comment]
Seems unlikely that it's related to the previous mysql issue on travis then. Do you have any logs? I have a run going on our server central environment and can see if it passed there on Monday.

**Comment by greenlaw110** [comment]
@nbrady-techempower you can find the log at 
https://travis-ci.org/actframework/FrameworkBenchmarks

**Pull request merged**
