### PR TITLE
fixes for windows setup and execution

### PR DESCRIPTION
**Pull request by nathana1**
- updates Windows setup script (mostly using chocolatey to install prereqs)
- fix test execution scripts to work on Windows (do Windows equivalent of some Unix only stuff)

cc: @sajayantony @damianedwards @halter73

### CODE REVIEW

**Comment by msmith-techempower** [comment]
o.O

@nbrady-techempower We need to test this out on windows.

**Comment by msmith-techempower** [comment]
We are a little swamped today, but we are going to try and get a Win10 VM up and test this out locally on Monday.

Much excite!

:+1:

**Comment by nbrady-techempower** [comment]
Very excited to start working on this! As primarily a Windows user this makes me really happy!

**Comment by nathana1** [comment]
I tried for parity in the new setup script with the previous one.  Let me know if anything was missed or if there's stuff that should be added/removed.

**Comment by bhauer** [comment]
Awesome!

@nbrady-techempower @msmith-techempower I'll get you guys a Windows 10 VM set up on our in-house network ASAP.  Or would it be better to use Windows Server 2016 Technical Preview 5?

**Comment by nbrady-techempower** [comment]
@nathana1 What VM would you suggest for testing your PRs? Windows 10 or Server 2016 Technical Preview 5?

**Comment by nathana1** [comment]
I tested on server 2012 R2.  It hopefully won't matter much but a server sku would probably be best.

**Comment by nbrady-techempower** [comment]
@nathana1 got it, thank you!

**Comment by nbrady-techempower** [comment]
Hi @nathana1 so quick update. Got the sever 2012 r2 vm up. Ran the bootstrap script which ran the install script. Then went to fire up aspnetcore test and nothing happened. Nothing in the results directories and no apparent errors. Were there any additional steps you took?

**Comment by nathana1** [comment]
I have these in parallel branches so the update-windows-setup branch doesn't have the aspnetcore tests in it.  If you checkout my aspnetcore-windows branch it has both the aspnetcore and windows changes.

Something else that just occurred to me is the bootstrap script as written will work after this is merged, but will currently pull down the current Windows install script and framework.  So to test you should modify the bootstrap clone to (the aspnetcore tests should just work with this branch):

git clone -b aspnetcore-windows https://github.com/nathana1/FrameworkBenchmarks.git $basedir

Sorry about that.

**Comment by nbrady-techempower** [comment]
Ah, that makes sense. I did merge in both pull requests locally when testing, but hadn't thought about the bootstrap script pulling from the current master. I will give that a shot, thanks!

**Comment by nbrady-techempower** [comment]
@nathana1 So just a quick update. Having the same issues as before after following the steps. I've merged in the files from your repo and changed install script to match. Did this again on a clean vm with the same results. If you have any time this week, would you mind trying this on a vm and documenting the steps that you took to get it to work from clean state? No rush at all, just feel like I'm either missing a step or there's something configured globally on your machine that might have been overlooked.

**Comment by nathana1** [comment]
This is what I've been doing:

1. create a new azure windows server 2012 r2 vm
2. copy over the bootstrap script
3. modify the git clone line to:  git clone -b aspnetcore-windows https://github.com/nathana1/FrameworkBenchmarks.git $basedir
4. run the bootstrap script
5. modify the benchmark.cfg to your environment (point to your client, server, db), copy the id_rsa for the db and client over
   
  a.  The other key lines seem to be os, database_os, and *identity_file.  os should be windows, database_os linux and the identity_file to something like c:\FrameworkBenchmark\id_rsa
6. run 'python .\toolset\run-tests.py --mode verify --test aspnetcore-win'

Hope this helps.

**Comment by nbrady-techempower** [comment]
Hi @nathana1 ! Sorry this has gone inactive. As you can see we've been making some significant changes to our toolset and travis trying to make things both easier to follow and to make our continuous integration testing look more like our actual development environments. I'd love to continue exploring this. I know the aspnet core team has been hard at work and done some great things so I don't know how available you are, but if you'd like to rebase and reopen we can start exploring this again. Thanks for all your work!

**Pull request closed without merging**
