### PR TITLE
php/phalcon: Define metadata in model

### PR DESCRIPTION
**Pull request by ruudboon**
Used some Phalcon native method to encode json.
Added metadata to Models to save on db queries.

### CODE REVIEW

**Comment by ruudboon** [comment]
We're not ready for labeling this as [verified](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Verified-Tag). We fully need to review the code and discuss with the rest of the team before we can approve that.

**Comment by Jeckerson** [comment]
This is first iteration of changes from Phalcon Team and it can be merged.

**Comment by joanhey** [comment]
Phalcon don't cache the model metadata in production ?

**Comment by Jeckerson** [comment]
@joanhey 

* https://docs.phalcon.io/4.0/en/db-models-metadata#adapters
* https://docs.phalcon.io/4.0/en/db-models-cache#model-caching

**Comment by joanhey** [comment]
In any benchmark test, first run a warm-up, so any cache, jit, ...  it's ready when start the bench.

Remember that a benchmark is not a competition. It's a tool to optimize the code.
If you by pass your normal flow, you will never optimize the code.

**Comment by ruudboon** [comment]
@joanhey In production for a lot of users this is a normal flow. Didn't know about the warm-up, will dive a bit more in the tooling to see what the options are. 
I agree with you that this tool can be used to optimise the code but there are different flows to that. The specified cases are perfect way to showcase how to setup a framework to run as fast as possible and give users ideas how to optimise certain parts.

**Comment by joanhey** [comment]
I give a tip, do it like you want !!

**Comment by ruudboon** [comment]
@joanhey Sorry I didn’t mean to sound rude or anything. Absolutely appreciate the feedback.

**Comment by joanhey** [comment]
If you want to check Phalcon micro:
https://tfb-status.techempower.com/unzip/results.2020-06-05-01-19-47-523.zip/results/20200531232959/phalcon-micro/run/phalcon-micro.log

After update to v4 have this problem.
It seems to me that don't use the db persistent connection now.

**Comment by ruudboon** [comment]
@joanhey Looking at the log it looks like that is indeed the case. If you have time, would you be able to isolate it with a code example and open an issue at https://github.com/phalcon/cphalcon/issues

**Comment by nbrady-techempower** [comment]
@ruudboon Is this PR ready to be merged?

**Comment by ruudboon** [comment]
@nbrady-techempower sorry, missed your comment. This one can be merged

**Pull request merged**
