### PR TITLE
Updated composer.json for installing cygnite v1.3.0 

### PR DESCRIPTION
**Pull request by sanjoydesk**
Updated composer.json

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @sanjoydesk Would you mind reopening this to target the round-14 branch? There have been a lot of php fixes and changes and we're running previews of round-13 currently

**Comment by sanjoydesk** [comment]
Hi @nbrady-techempower Seems like all checks passed. I would love to see the v1.3 benchmark results in round-13 itself. Meanwhile we will make ready the framework v2.0. 
Please merge the pull request. 

Let me why wrong branch you have tagged ?

Thanks!

**Comment by nbrady-techempower** [comment]
@sanjoydesk unfortunately we have closed off round-13 and have already begun preview runs on that. We have not allowed any updated content on it. Round-14 is going to be the big one though. We have several major framework fixes and updates.

**Comment by sanjoydesk** [comment]
Hi, @nbrady-techempower  It will be highly appreciable If you please add cygnite-1.3 in round-13 itself, as team just started preview runs not the final. Because it was suppose to be included in round-12 but unfortunately it was breaking. 

We are planning to  release cygnite v2.0 for which i will send you pull request which can be included in round-14. 

Thanks!

**Comment by nbrady-techempower** [comment]
@sanjoydesk ah, didn't realize it was a fix, thought it was just an update. No problem. Thanks!

**Comment by sanjoydesk** [comment]
Thank you @nbrady-techempower :+1:

**Pull request merged**
