### PR TITLE
upgrade Vert.x to 4.0.0

### PR DESCRIPTION
**Pull request by ChinaITYes**

### CODE REVIEW

**Comment by BillyYccc** [comment]
Sorry but I think the code you submitted here would not be ideal for the benchmark results, have you tried discussing with the community or the Vert.x official team?

**Comment by itgeekhome** [comment]
> Sorry but I think the code you submitted here would not be ideal for the benchmark results, have you tried discussing with the community or the Vert.x official team?

Thanks for your replying, I haven' t discussing with the community or the Vert.x official team yet, I just think the code style before wrote almost everything in a single java file which could not be recommended by the community or the Vert.x official team, because it wasn' t the best practice obviously,  and I think every Vert.x hobbyists has the duty to devote his or her intellgence for it. by the way, I have following the Vert.x repository for almost 2 years, but I saw no one did the thing, to make the code more readable and reasonable, so I decided to do it by myself.  that‘s all.

**Comment by vietj** [comment]
@ChinaITYes we haven't yet put efforts in Vert.x 4.0 for Techempower and the maintainer of Vert.x (myself and @pmlopes) are following accurately and handling Vert.x in TFB, so we would like to retain control over this. For the moment we do not whish to submit Vert.x 4.0.0 to TFB and wait until we have done proper benchmarking of Vert.x and optimized some bits.

**Comment by vietj** [comment]
As Vert.x project lead, I'm officially asking to not merge this PR, the Vert.x team will take care of upgrading to Vert.x 4 when it is appropriate.

**Comment by ChinaITYes** [comment]
> @ChinaITYes we haven't yet put efforts in Vert.x 4.0 for Techempower and the maintainer of Vert.x (myself and @pmlopes) are following accurately and handling Vert.x in TFB, so we would like to retain control over this. For the moment we do not whish to submit Vert.x 4.0.0 to TFB and wait until we have done proper benchmarking of Vert.x and optimized some bits.

OK, got it, thanks.

**Comment by ChinaITYes** [comment]
> As Vert.x project lead, I'm officially asking to not merge this PR, the Vert.x team will take care of upgrading to Vert.x 4 when it is appropriate.

OK, got it, I will close the pr later.

**Comment by vietj** [comment]
thanks for your understanding @ChinaITYes

**Pull request closed without merging**
