### PR TITLE
Remove uwebsockets

### PR DESCRIPTION
**Pull request by NateBrady23**
Unfortunately the maintainer is no longer able to make pull requests to this repo.

### CODE REVIEW

**Comment by porsager** [comment]
That's a pity. Any chance you'd allow someone else to maintain it?

**Comment by e3dio** [comment]
Wow you removed a legitimate project because someone voiced an opinion on the testing methods used ? So strong and brave of you

**Comment by IonelLupu** [comment]
@NateBrady23, what happened?

**Comment by JarvisPrestidge** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/1078

Personal feelings shouldn't overshadow valid technical critiques, even if bluntly delivered...

**Comment by IonelLupu** [comment]
so `uwebsockets` was removed just because they tweeted this? Were they lying about the other benchmarks or are they right?

image

**Comment by NateBrady23** [comment]
Why do so many people keep commenting on this without trying to find the answer. No, that person was not banned for a single tweet. They were banned for continued harassment in comments in PRs and issues that had to be deleted. Nobody cares about criticisms about the benchmarks. I've been doing this for 10 years. Never had to block a single person and remove their framework. I don't take any of that personally. Frankly, I don't have time. Harassment and derogatory language will absolutely not be tolerated. I don't care who you are. If you want to add the framework back, go ask the maintainer if you can maintain it here. We don't care who maintains it. It's only being removed because that person can't make updates to it, which is unfair to them.

**Comment by porsager** [comment]
How do you know we haven't tried? I still haven't found anything, but I suppose that makes sense when it was all deleted? Were these PRs and issues not related to the benchmarks and their quality, although they contained - what you deemed inappropriate language/behavior? The critiques I've seen - I think - all seemed valid. Could it be that Alex might already have a negative stance because his time is also wasted by people clamouring about his project not being represented here, and how sub-par projects are faster than his and only float to the top by employing bad tactics and incomplete implementations?

**Comment by NateBrady23** [comment]
Never said any of his critiques weren't valid.

If you read the plaintext requirements, it's basically the most open implementation for tests. If you're trying to "win" the plaintext benchmarks, I mean, I don't know what to tell you.

All that's left here to say is, if he wants someone else to maintain his framework, we don't care. I'll revert the PR, framework back, someone else can maintain it. As of today, after a decade, he is the only person blocked. That should tell you something. Look through the thousands of issues and PR's. We're not lacking critiques.

**Pull request merged**
