### PR TITLE
Add postgres tests to nodejs

### PR DESCRIPTION
**Pull request by zane-techempower**
Add Postgres testing to nodejs. Good addition for completeness. Postgres ususally out-performs mysql by a little so this could very well be the fastest nodejs variation.

### CODE REVIEW

**Comment by mcocciaTE** [comment]
Works for me!

**Comment by zane-techempower** [comment]
Mongodb was down for all of the tests which caused fails. This one is having the problem of not having databases active for the main test `nodejs` which only tests `/json` and `/plaintext`, thus not prompting the databases to start.

I am considering merging the `my-sql` or `my-sql-raw` tests into the main `nodejs` test to avoid this. Testing with mysql as the default database is commonly done. Will have more additions here today.

**Comment by msmith-techempower** [comment]
I tested this locally and got the same errors as travis - it looks like `hiredis` doesn't build successfully.

**Comment by zane-techempower** [comment]
I haven't seen `hiredis` fail to build in my experience. Went through the travis logs and only saw mongodb failing to start. `hiredis` is actually apart of the redis part of nodejs which is already merged in.

I have merged with the updated master, lets see how things go in travis.

**Comment by msmith-techempower** [comment]
@ssmith-techempower Try pulling this into a new branch on our latest master and testing it out.

**Comment by ssmith-techempower** [comment]
I pulled and tested this locally, LGTM. Merging it in.

**Pull request merged**
