### PR TITLE
Upgrade to latest jooby

### PR DESCRIPTION
**Pull request by jknack**

### CODE REVIEW

**Comment by msmith-techempower** [comment]
I don't know how I merged in Jooby without a line in `.travis.yml`... Please update that file to have an entry so that Travis-CI will automatically test the framework.

**Comment by jknack** [comment]
Hi @msmith-techempower 

Don't see .travis.yml in any of the others JVM tests. Is it a simple .travis.yml for build and package the app?

Let me know if I have to add any other command to travis.

Thanks

**Comment by msmith-techempower** [comment]
@jknack Sorry, `.travis.yml` exists at the root of the project, and has every framework directory listed in it (except Jooby). This is what Travis-CI uses to determine what to test, so we need you to update it and add Jooby to it.

**Comment by jknack** [comment]
Got it! and I added it!

Thanks.

**Comment by msmith-techempower** [comment]
All tests pass; LGTM!

**Pull request merged**
