### PR TITLE
Added framework: libevent

### PR DESCRIPTION
**Pull request by gkbrk**

### CODE REVIEW

**Comment by nmihajlovski** [comment]
@gkbrk Wow, this looks very interesting!
Looking forward to seeing the performance results!
Kudos for the hard work!

**Comment by knewmanTE** [comment]
Thanks for the pull request! Just wanted to apologize for the delay in reviewing this and merging it in; we're in the thick of preparing everything for our Round 13 release. As soon as Round 13 is over, we'll get to the Round 14 pull requests!

**Comment by gkbrk** [comment]
@knewmanTE No worries man, I'm excited for Round 13 as well.

**Comment by nbrady-techempower** [comment]
Hi @gkbrk ! Thanks for the contribution! Would you mind adding a README for this framework that includes some information about it and where we can find documentation. I haven't looked too deeply into this yet, but I see you've added an fw_depends libevent / but I don't see any libevent setup in the toolset. Thanks!

**Comment by knewmanTE** [comment]
@gkbrk, is it possible to pull down the relevant framework code from github (or wherever libevent is being hosted)? You've included a rather large file at `frameworks/C/libevent/json.h` when the only FrameworkBenchmark-specific code lives at `frameworks/C/libevent/server.c`. As a rule of thumb, we try to limit the code in the FrameworkBenchmarks repo to the actual test implementation and leave the task of downloading and organizing the framework itself to a setup script.

For example, if you look at [C/duda](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C/duda), it has `fw_depends duda` in its setup script, which automatically calls [this script](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/frameworks/duda.sh) to download and configure duda. (fw_depends is a custom function that will search through `toolset/setup/linux/*` for a script with the provided name and run that script if it exists)

**Comment by msmith-techempower** [comment]
ping @gkbrk

**Comment by nbrady-techempower** [comment]
@gkbrk Going to close this due to inactivity. We're going to start previews right after the new year for the next round. If you'd like to be included please open a new PR targeting the master branch and include the relevant src @knewmanTE mentioned above. Hope to see you in that round and thanks for the contribution! :)

**Pull request closed without merging**
