### PR TITLE
Vibe.d multi-core utilization

### PR DESCRIPTION
**Pull request by Dith3r**

### CODE REVIEW

**Comment by Dith3r** [comment]
mongodb failed to start.

**Comment by blee-techempower** [comment]
Failed localtest.

```
================================================================================
  Verification Summary

| Test: vibed
|       plaintext   : FAIL
|       query       : FAIL
|       json        : FAIL
|       db          : FAIL
================================================================================
```

Please resolve this issue.

**Comment by blee-techempower** [comment]
Localtest fail. 
Here is log: ( http://sprunge.us/QMUJ ).
Please resolve this issue.

**Comment by Dith3r** [comment]
Could you write what version of dmd and libphobos you are using for building it?

**Comment by msmith-techempower** [comment]
@Dith3r [Looks like 2.067.1](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/languages/dlang.sh#L11)

**Comment by msmith-techempower** [comment]
@Dith3r Please rebase from our latest master so Travis-CI can retest.

**Pull request closed without merging**
