### PR TITLE
Ur/Web version upgrade & change to number of server threads

### PR DESCRIPTION
**Pull request by achlipala**

### CODE REVIEW

**Comment by mcocciaTE** [comment]
@msmith-techempower It looks like everything is working on travis but it does not seem to work on my local machine. I think postgres is just not working for me.

**Comment by achlipala** [comment]
@msmith-techempower : I'm taking your last message to mean that this PR seems to be working for you, but please let me know if you'd like me to change anything.

**Comment by mcocciaTE** [comment]
Everything is working now for me locally. It wasn't working for me but that was a postgres issue locally I fixed so now just want to wait for @msmith-techempower to double check then should be good to go!

**Comment by achlipala** [comment]
Oh, sorry, I wasn't understanding from GitHub's notification which user had posted the comment.  I thought msmith was reporting the issue himself.

**Comment by mcocciaTE** [comment]
It's all good. When I realized what was happening I deleted the comment which probably was a bad idea and just made it more confusing.

**Pull request merged**
