### PR TITLE
Updating vert.x to the latest release 2.1.5

### PR DESCRIPTION
**Pull request by victorbriz**
Maintainer of vert.x seems to like to have vert.x back in FrameworkBenchmarks, maybe for Round 11?
https://groups.google.com/forum/#!msg/vertx/kism9YHbpTo/zSwWhs952dwJ
It is also important for us, developers who is using vert.x to have it in FrameworkBenchmarks.

### CODE REVIEW

**Comment by hamiltont** [comment]
Looks great! 

While we are here, can I ask you to move all of the code from `toolset/setup/linux/frameworks/vertx.sh` to `frameworks/Java/vertx/install.sh`, underneath the line for `fw_depends`

For various reasons, we are trying to be really restrictive about what goes under `toolset/`, so this change would move the installation process for vert.x into the specific install.sh file for vert.x. A copy/paste should be all that's required, with the final install.sh looking like the code below and vertx.sh being deleted

```
#!/bin/bash

fw_depends java7 

RETCODE=$(fw_exists ${IROOT}/vert.x-2.1.5.installed)
[ ! "$RETCODE" == 0 ] || { return 0; }

fw_get http://dl.bintray.com/vertx/downloads/vert.x-2.1.5.tar.gz?direct=true -O vert.x-2.1.5.tar.gz
fw_untar vert.x-2.1.5.tar.gz

touch ${IROOT}/vert.x-2.1.5.installed
```

**Comment by hamiltont** [comment]
By the way, take a look at the verification results from Travis-CI. Everything passes, but there are a few places you might be shooting your performance in the foot a bit with errors like this: 

```
  Response (trimmed to 40 bytes): "[{"id":8909.0,"randomNumber":3396.0},{"i"
   WARN for http://127.0.0.1:8080/queries?queries=2
     Response key 'id' contains extra quotations or decimal points.
             This may negatively affect performance during benchmarking
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

It's telling you that `8909.0` could be `8909` (e.g. saving two bytes) and still be considered a valid response

**Comment by victorbriz** [comment]
Done and done.

**Comment by hamiltont** [comment]
thanks!

**Comment by purplefox** [comment]
I would not like to see any results for Vert.x published until we have had time to do a proper submission based on Vert.x 3.

I discussed this with @bhauer some time back, so please don't publish this.

**Comment by purplefox** [comment]
BTW @victorbriz - I don't mean to rain on your parade - but if you're interested in helping get benchmarks together for Vert.x 3 I think that would be a better use of time.

I can help you optimise too. wdyt?

**Comment by martin-g** [comment]
See #1697

**Comment by bhauer** [comment]
Vert.x will be marked as "Removed at request of maintainer - outdated version" in the final for Round 11.  It may appear in previews, but we will continue to mark it as such in the final results for each round until it's updated and @purplefox signs off.

**Pull request merged**
