### PR TITLE
adding aah framework into benchmark [ci fw Go/aah]

### PR DESCRIPTION
**Pull request by jeevatkm**
Hello -

Thank you for the help over here #2854, I have finished tests.

I'm the author of [aah framework](https://aahframework.org), I would like to add my framework into benchmark test. I have implemented the tests per TFB requirements.

[Travis CI Build Reference](https://travis-ci.org/jeevatkm/FrameworkBenchmarks/jobs/241482301)
````
================================================================================
  Verification Summary
| Test: aahframework
|       fortune       : PASS
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS
================================================================================
````

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Thanks @jeevatkm 

I updated the name in the benchmark_config.json to just be `aah` unless you normally call it `aahframework` this way it can be run as `tfb --test aah`

Gonna let that commit get picked up by travis here and testing locally. I'll merge once those are done and it will be in for preview 2. Thanks! :)

**Comment by nbrady-techempower** [comment]
Passes local and travis tests. Merging in!

**Comment by jeevatkm** [comment]
@nbrady-techempower Thank you. Glad to hear it will be preview 2.

Is there possibility of accessing preview run result in raw format?

**Comment by nbrady-techempower** [comment]
We provide all the logs and raw output when we post the results.

**Comment by jeevatkm** [comment]
I understand, it means for final result not preview results. Thank you. I look forward to Round 15 results.

**Pull request merged**
