### PR TITLE
Update .NET Core to 2.0.0

### PR DESCRIPTION
**Pull request by mikeharder**
CC: @dougbu

### CODE REVIEW

**Comment by dougbu** [comment]
LGTM as long as the checks pass.

Great npgsql/Npgsql.EntityFrameworkCore.PostgreSQL#223 took less than a week to fix.

**Comment by mikeharder** [comment]
@nbrady-techempower: It appears that Travis is running too many tests for this PR.  I believe it should only be running `CSharp/aspnetcore`, but it also ran `CSharp/aspnet` and `C++/ffead-cpp`.

**Comment by nbrady-techempower** [comment]
@mikeharder We've put together quite the hack on the travis side to get around them not having a dynamic build matrix, so it happens every now and then. I usually dive in to the builds to see if the relevant tests pass. You guys are all set. Thanks!

**Comment by mikeharder** [comment]
Fixed in https://github.com/TechEmpower/FrameworkBenchmarks/pull/2939

**Pull request merged**
