### PR TITLE
Update Rust

### PR DESCRIPTION
**Pull request by steveklabnik**
Two things:

1. let's DRY this slightly so that we can change one version and update everything. Easier and more accurate.
2. Update to Rust 1.8.

### CODE REVIEW

**Comment by steveklabnik** [comment]
The rust tests are all passing, it's only other things that are failling.

**Comment by jadbox** [comment]
@steveklabnik Can you update this to Rust 1.9 (was released this week with several perf improvements, notably strings).

**Comment by steveklabnik** [comment]
I can and will! It'll be tomorrow though.

**Comment by steveklabnik** [comment]
I pushed a new commit that updates to 1.9, and upgrades some other versions. Let's see what CI says!

**Comment by steveklabnik** [comment]
All rust stuff passed, this should be good to go!

**Comment by nbrady-techempower** [comment]
Hi @steveklabnik  we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by steveklabnik** [comment]
Absolutely!

So you know what the schedule is? It'd be nice if we could maybe work on doing some work before the next benchmark is taken.

**Comment by nbrady-techempower** [comment]
@steveklabnik we won't be getting any work in for round-13 but with this new model we'll be able to do simultaneous testing and merging of current and future rounds so when, like now, a round is "frozen" we won't have PRs sitting waiting for feedback. We can get them tested and merged in to the round they're targeting. This also gets us closer to a continuous benchmarking goal. We want the contributors to see faster turnaround on all the hard work they do!

**Comment by steveklabnik** [comment]
Cool. :+1: sending new PR now

**Pull request closed without merging**
