### PR TITLE
Removed some tests + Performance optimizations

### PR DESCRIPTION
**Pull request by sumeetchhetri**

### CODE REVIEW

**Comment by sumeetchhetri** [comment]
@nbrady-techempower could you please review and merge this PR if found OK, before the Round 20 test run.

**Comment by nbrady-techempower** [comment]
@sumeetchhetri we have already captured round 20 results and are reviewing

**Comment by nbrady-techempower** [comment]
@sumeetchhetri I’ve mentioned before that you have too many test permutations. I won’t be adding any more. The new toolset, which we are switching to after we post round 20 results, will only allow 15 tests permutations per framework.

**Comment by sumeetchhetri** [comment]
@nbrady-techempower can we get this PR merged, after the next test run, I'll surely get the total number of tests below 15.

**Comment by nbrady-techempower** [comment]
@sumeetchhetri i am not adding more test permutations

**Comment by sumeetchhetri** [comment]
@nbrady-techempower Disabled a lot of tests that were no longer needed, this should hopefully be fine now.

**Comment by nbrady-techempower** [comment]
@sumeetchhetri thank you

**Pull request merged**
