### PR TITLE
Add Reindexer database server as database type

### PR DESCRIPTION
**Pull request by olegator77**
Hi!
I've introduced [Reindexer](https://github.com/restream/reindexer) database to toolset. 
Also there are added Golang fasthttp-reindexer test (as extra subtest of existing fasthttp test)

### CODE REVIEW

**Comment by olegator77** [comment]
Hi! I've investigated about CI error status - changes to toolset folder are force run of every framework tests in CI.
But It seems, that few frameworks tests in master branch can't pass CI tests their self.

So, please help - how to pass CI test in this case?

Tnx.
--
Oleg

**Comment by cjnething** [comment]
Hi @olegator77 would you mind resolving this merge conflict? Thanks!

**Comment by cjnething** [comment]
Thanks @olegator77! I'll request a reviewer

**Comment by olegator77** [comment]
@cjnething thanks, will wait for review!

**Comment by nbrady-techempower** [comment]
Thanks for taking the time to open this PR. Right now, we're not ready to add any new databases to the toolset. We're hoping in the near future to make it easier to add databases without touching the core toolset code (like simply dropping a new directory under databases). When that time comes, we'll be able to do a more thorough review of potential new databases.

**Pull request closed without merging**
