### PR TITLE
[aspnetcore] Bump to 6.0.0-rc.2

### PR DESCRIPTION
**Pull request by roji**
Also:

* Update EF Core 6.0 to use latest optimizations
* Use positional parameters in raw Npgsql tests

/cc @sebastienros @davidfowl @layomia @richlander @benaadams @MichalStrehovsky @ajcvickers

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
Please update to 6.0, as we now have a stable release.

**Comment by sebastienros** [comment]
@ShreyasJejurkar maybe something you can help with in a PR? There is also MySQLConnector, EF and Dapper that could be bumped.

**Comment by ShreyasJejurkar** [comment]
@sebastienros ohh can I? I thought only official owners of FW can tweek changes to benchmarks code!

OK. I will try to get this done!

**Comment by sebastienros** [comment]
Not even sure there is anything like "official owners", we just ping people who usually deal with each tech stack. But those who participate the most tend to influence the one who actually can merge the most.

**Comment by ShreyasJejurkar** [comment]
Ok @sebastienros, I will create PR for upgrade. Maybe a issue first and I will link all PR to it one by one.

Sorry, I never contributed to this repo before, so am not sure about guidelines. But as this is benchmarks repos and all people refer this, I was under impression that only people who won't on framework are allowed to contribute as they know most of the ins and outs of it.
But anyway I will open pr for this tommarow (it's late night here, in India). 😅

**Comment by roji** [comment]
@ShreyasJejurkar you can follow this PR as a model for updating the versions. No real need for an issue or multiple PRs here - a simple PR updating to 6.0 should be sufficient. A .NET dev like @sebastienros or myself will review and approve the PR.

**Pull request merged**
