### PR TITLE
Update Vala-based frameworks

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by michaelhixson** [comment]
@arteymix Do you know how to fix the build error reported by Travis?  I got the same error when I tried this PR locally.

```
Setup vsgi: Found ninja-1.8.2 at /home/travis/build/TechEmpower/FrameworkBenchmarks/installs/ninja/bin/ninja
Setup vsgi: ninja: Entering directory `build'
Setup vsgi: ninja: error: '../tests/tests/data/server-sent-events/send-expected-message', needed by 'tests/tests-resources.c', missing and no known rule to make it
Setup vsgi: ERROR: /toolset/setup/linux/frameworks/valum.sh: Command '( cd valum-${VALUM_VERSION}; rm -rf build; meson --prefix=${IROOT}/vala --buildtype=release --libdir=lib build; ninja -C build; ninja -C build install )' exited with status 1 (dependency=libsoup2.4-dev) (cwd=$FWROOT/installs)
```

**Comment by arteymix** [comment]
I fixed that in the trunk: it seems to be a bug with Meson. I'll release a patch version and it should work ok.

**Comment by arteymix** [comment]
I'm looking at this right now. It seems like the updated `valac` does not look in the standard VAPI folder.

**Comment by nbrady-techempower** [comment]
@arteymix Looks like this is still failing. I'm going to close this for now as we are close to getting everything moved to docker. If you happen to get this working, you can either re-open and let me know and I can help you move it to the docker implementation, or we'll just end up moving what we currently have to the docker implementation. Thanks!

**Comment by arteymix** [comment]
Sounds good to me. It's a bit easier to work out with Docker and I've got a hard time spinning the vagrant environment on my laptop.

**Pull request closed without merging**
