### PR TITLE
aspnetcore: add platform tests using libuv

### PR DESCRIPTION
**Pull request by n-stefan**
Added ASP.NET Core platform tests using the Libuv transport for Kestrel.

### CODE REVIEW

**Comment by sebastienros** [comment]
Need to talk with the team about this one. Also the perf will vary with the custom thread count, the default value won't make it justice on citrine.

**Comment by n-stefan** [comment]
Got it, thanks!

**Comment by sebastienros** [comment]
We discussed within the ASP.NET Core team and we feel that it’s best to leave out the libuv measurements from the TechEmpower numbers because it’s no longer a default scenario.

**Comment by n-stefan** [comment]
I see.
Thank you!

**Pull request closed without merging**
