### PR TITLE
fix Go/echo

### PR DESCRIPTION
**Pull request by methane**
This pull request uses [glide](https://github.com/Masterminds/glide) to version pinning.
I hope all other Go frameworks use same tool.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
This is perfect, thank you! Closing my removal PR. Yes, the others need this.

**Comment by methane** [comment]
travis build running on: https://travis-ci.org/methane/FrameworkBenchmarks/builds/187608729

**Comment by methane** [comment]
methane/FrameworkBenchmarks#8 is my local pull request for running Travis

**Comment by nbrady-techempower** [comment]
@methane why isn't this running travis here? That's preferable.

**Comment by methane** [comment]
Because queue is full.

**Comment by methane** [comment]
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds

**Comment by nbrady-techempower** [comment]
I don't know how I missed it in the PR build history. And for some reason it didn't integrate here. But it looks good. Merging! Thanks again @methane!

**Pull request merged**
