### PR TITLE
Initial push of ffead-cpp-2.0 to techempower benchmarks (https://github.com/sumeetchhetri/ffead-cpp)

### PR DESCRIPTION
**Pull request by sumeetchhetri**
Initial push of ffead-cpp-2.0 to techempower benchmarks
All Tests have been implemented and MongoDB is used as the database

### CODE REVIEW

**Comment by blee-techempower** [comment]
Localtest failed. ( http://sprunge.us/jVZX )
Please resolve the issue.

**Comment by sumeetchhetri** [comment]
Please check now.

**Comment by sumeetchhetri** [comment]
Are you still facing build issues locally?

**Comment by msmith-techempower** [comment]
There are a bunch of issues that need to be resolved before we can merge this in:

1. There are a bunch of extemporaneous files included such as static images and css etc. Remove all of these.
2. It seems like the entire source code for the framework is included; it should be handled as a dependency to be downloaded/installed via the toolset (to keep our repo size small); see [cppsp](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/frameworks/cppsp.sh) for reference.
3. Update `.travis.yml` to include the framework so that Travis-CI can automatically test it.

**Comment by sumeetchhetri** [comment]
Great to know that, I will update and raise a PR soon, Thanks Mike

**Comment by sumeetchhetri** [comment]
Opened a new PR https://github.com/TechEmpower/FrameworkBenchmarks/pull/1799, so closing this one

**Pull request closed without merging**
