### PR TITLE
Bump uws.js and use faster plaintext responding

### PR DESCRIPTION
**Pull request by uNetworkingAB**
This is faster.

Confirmed to work

### CODE REVIEW

**Comment by uNetworkingAB** [comment]
Please merge; tiny PR

**Comment by uNetworkingAB** [comment]
What's causing the holdup? It already passed testing

**Comment by uNetworkingAB** [comment]
Please merge

**Comment by uNetworkingAB** [comment]
Merge: please yes

**Comment by NateBrady23** [comment]
I get to PRs when I can. No need to make several comments about merging. Thanks.

**Comment by uNetworkingAB** [comment]
You have merged several other, newer, PRs and skipped this one which makes me think you will somehow block it by some arbitrary opinion. It's a super tiny PR that takes 3 seconds to review and given that I already tested it and is the author of the project, it's very strange to block changes like this.

**Comment by uNetworkingAB** [comment]
How are you even going to review it? You know nothing about the project so it's at most an ocular review by feeling. If you distribute responsibility based on incentive to make it right, things will just work without you being some central authority of what goes and not.

**Comment by uNetworkingAB** [comment]
lines changed:

+7 −7

**Comment by uNetworkingAB** [comment]
It's **undoubtedly** evident by looking at merged PRs, that you don't apply a fair merging. This is a tiny +7/-7 line change confirmed in testing, much older than MANY of the PRs you merge way more rapidly.

This PR is now on second month delay, while a lot of other PRs with similar size get merged in less than 2 weeks. So you actively decide not to merge this PR for some reason. You already, obviously saw it, so why you don't click "merge" is beyond me.

**Comment by NateBrady23** [comment]
I click "Approve and run" and then I do other things. You make changes, I have to click "Approve and run" again. When I see a green checkmark, I merge. 

I don't care about "fair merging." I don't have time for that.

Stop modifying the PR and I'll merge it when it's green.

I will tell you that you're the only person that has ever acted like this in the years we've been doing this, so if you want your PRs merged, just make the changes, let the green checkmark show up, and stop asking for it to be merged over and over again. I'll get to it when I get to it.

**Comment by uNetworkingAB** [comment]
It was green for a month and you did not click merge.

**Comment by NateBrady23** [comment]
Failing after 1m. Please fix. If you want to keep arguing about it, we're not going to accept this.

**Pull request merged**
