### PR TITLE
Update wrk to version 4.2.0

### PR DESCRIPTION
**Pull request by volyrique**
The `-mtune` compiler option does not have an effect on x86-64 (since we are already using `-march`), but it definitely affects other platforms, AArch64 in particular.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Thanks for doing this @volyrique!

**Comment by joanhey** [comment]
With the first frameworks in the actual run, look like they are slower with this change.
We will wait to finish, and check the results.

**Comment by volyrique** [comment]
I would like to wait till a full run has completed, so that I could look at the raw data (`results.zip`). My current suspicion is that the update to Ubuntu 22.04 is actually the culprit.

**Comment by joanhey** [comment]
I don't thing that is for Ubuntu 22.04.
It's a docker container, and they don't use the kernel. They use the kernel from the host.

More Req/s more content switch, that's the problem with #7321.
But with the hosts, not with the Wrk docker.

**Pull request merged**
