### PR TITLE
PHP optimitzations

### PR DESCRIPTION
**Pull request by joanhey**
Disabled opcache.validate_timestamps and removed php extra header.
Commented old apc config.

### CODE REVIEW

**Comment by joanhey** [comment]
Actually there isn't a way to config opcache per fw.
Neither for enabling and disabling extensions.
For example, Phalcon extension make all other php frameworks ~10% slower.

**Comment by msmith-techempower** [comment]
It seems that Travis-CI did not test anything for this branch; we will need to test before we can merge.

**Comment by nbrady-techempower** [comment]
Hi @joanhey we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by nbrady-techempower** [comment]
closed for #2106

**Pull request closed without merging**
