### PR TITLE
postgresql jdbc driver updated to 9.4-1200-jdbc41

### PR DESCRIPTION
**Pull request by zloster**
@hamiltont PostgreSQL JDBC updated again.

### CODE REVIEW

**Comment by kbrock** [comment]
I think the 2 failures for this were in sporadic mongodb failures, not related to postgres at all

**Comment by zloster** [comment]
@kbrock Thanks for the comment. When I've committed there was a build running for very long and I forgot to check the logs later.
I also think the 2 failures are not related to the change.

**Comment by hamiltont** [comment]
So I've re-run those two jobs ~3 times each now, and always the same result. I also suspect that there is almost no chance this PR is causing that, but need to spin up a local VM and double-check. If someone wants to proactively do that and gets a pass I'm happy to merge - I'll try to get to manually testing this today but no promises

**Comment by zloster** [comment]
I've played with this one today. The result is that it works fine on a local VM. Result logs are [here](https://github.com/zloster/logs/tree/master/FrameworkBenchmarks/results/ec2/latest).
What I have done?
```
cd Downloads/tmp
git clone --depth=50 git://github.com/TechEmpower/FrameworkBenchmarks.git TechEmpower/FrameworkBenchmarks
git fetch origin +refs/pull/1358/merge:
cd TechEmpower/FrameworkBenchmarks/
```
After this in the VM:
```
export TESTDIR=Java/undertow
cd FrameworkBenchmarks
./toolset/run-ci.py cisetup "$TESTDIR"
./toolset/run-ci.py prereq "$TESTDIR"
./toolset/run-ci.py install "$TESTDIR"
time ./toolset/run-ci.py verify "$TESTDIR"
```
and this (with some errors in the commands sequence):
```
export TESTDIR=Java/undertow-edge
./toolset/run-ci.py cisetup "$TESTDIR"
./toolset/run-ci.py install "$TESTDIR"
./toolset/run-ci.py prereq "$TESTDIR"
./toolset/run-ci.py install "$TESTDIR"
time ./toolset/run-ci.py verify "$TESTDIR"
```

**Comment by LadyMozzarella** [comment]
I ran the failing tests in Travis locally off of zloster/postgresql-jdbc-bump and they appear to be passing for me. These two tests do seem to be consistently failing in Travis.
undertow-tests

**Comment by LadyMozzarella** [comment]
Actually, after looking closer the failing tests are undertow-mongodb and undertow-edge-mongodb. They still look good.

Here are all of the undertow tests:
all-undertow-tests

**Comment by hamiltont** [comment]
Thanks for double-checking all, this LGTM

> What I have done?

@zloster You've encountered one of the rare and tricky-as-hell to debug travis-CI errors, I suspect :+1:

**Pull request merged**
