### PR TITLE
Fix issues with servant.

### PR DESCRIPTION
**Pull request by jkarni**
DB host was not being used. Max threads were being ignored.

### CODE REVIEW

**Comment by jkarni** [comment]
See #2205

**Comment by jkarni** [comment]
The failures aren't related to servant, or to these changes.

**Comment by jkarni** [comment]
Any updates on this? It'd be nice to have a working preview round...

**Comment by knewmanTE** [comment]
hey @jkarni, sorry for the delay! We've folded round-13 into master since my last comment on your old pull request. Would you mind doing one last pull request for your code into master? We'd really love to get your code in for our final round 13 run!

**Comment by jkarni** [comment]
Done in #2240 . Thanks!

**Pull request closed without merging**
