### PR TITLE
[php] Ubiquity update to PHP 8.3

### PR DESCRIPTION
**Pull request by joanhey**
~Ngx-php only to PHP 8.2~
Update ngx-php to 0.0.28, php 8.3, nginx 1.25.3 and ubuntu 22.04

- #8579

### CODE REVIEW

**Comment by joanhey** [comment]
Ping @jcheron

**Comment by jcheron** [comment]
Hi @joanhey 
Thanks, I'll look at it this weekend

**Comment by jcheron** [comment]
The `AllowDynamicProperties` attribute is missing from the `World` model.

**Comment by joanhey** [comment]
@jcheron check https://github.com/myaaghubi/PHP-Frameworks-Bench/pull/49

**Pull request merged**
