### PR TITLE
Add support for the Luna C++ framework

### PR DESCRIPTION
**Pull request by DEGoodmanWilson**
Adding support for the Luna C++ framework. Luna depends on the Conan package manager, so this PR also adds support for Conan in the systools. I expect it is this addition that will want a little extra scrutiny.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @DEGoodmanWilson! Glad to see you got the dev environment working for this. Looks like this didn't pass the travis test though.

**Comment by DEGoodmanWilson** [comment]
Bother, thanks for pointing that out. It had passed in my fork, so I hadn't bothered to check again here. I'm investigating now.

**Comment by DEGoodmanWilson** [comment]
That was easy. Let's see if the tests pass this time.

**Comment by DEGoodmanWilson** [comment]
That seems to have done it; the Luna tests have passed finally. I wonder why earlier tests on my own fork passed despite these issues. /shrug

**Comment by nbrady-techempower** [comment]
@DEGoodmanWilson Alright, looks good! I'll merge this in right after round 14 final is posted.

**Pull request merged**
