### PR TITLE
Update Sails app  (this is currently a WIP)

### PR DESCRIPTION
**Pull request by mikermcneil**
### Update

After further study, it looks like there are a few other things we need to update in the Sails benchmark (esp. setting up clustering so that the metrics are relevant vs. other frameworks in the list).   So rather than peppering y'all with individual pull requests, @irlnathan, @sgress454 and I will just put everything into this one PR so you can review it all at once.  I'll post a comment and edit the title of this PR when it's ready.  Thanks again!

>### Original post (about NODE_ENV)
>
>Hey guys, apologies if this is taken care of elsewhere, but I noticed it wasn't in here so wanted to raise the question.  For Sails.js to perform as expected in production, it's important to set the NODE_ENV environment variable accordingly.  See http://sailsjs.com/documentation/concepts/deployment#?set-the-nodeenv-environment-variable-to-production for more information.
>
>Thanks!
>
>P.S. I opened a [separate PR](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2398) for making the same change in the Express benchmark, where it is [also expected in production](https://expressjs.com/en/advanced/best-practice-performance.html#set-nodeenv-to-production).

### CODE REVIEW

**Comment by knewmanTE** [comment]
@mikermcneil could you update your repo with the latest from master? We recently merged in a fix that should get Travis working again so we can verify your test.

**Comment by nbrady-techempower** [comment]
@mikermcneil I'm going to close this pr for now as sailsjs is still having issues passing tests. Don't want to include updates to the app before verifying that it is working correctly. If you'd like to give that a shot (looks like there are some deprecated dependencies) feel free to open a new pull request targeting the master branch. We should be starting preview runs for the next round right after the new year. Thanks for all your contributions!

**Comment by mikermcneil** [comment]
@nbrady-techempower Thanks!  It'd be good to have it use Sails best practices (and particularly have it test our ORM instead of Sequelize).  We're [planning on](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2398#issuecomment-275270290) putting some effort into this soon, since we need some holistic benchmarks for Sails v1 anyway.  Really dig the way y'all laid out your spec!

**Comment by nbrady-techempower** [comment]
Thanks @mikermcneil 
Let us know if you need any help

**Pull request closed without merging**
