### PR TITLE
Ubiquity-workerman: Add memory_limit to php.ini

### PR DESCRIPTION
**Pull request by jcheron**
see https://github.com/TechEmpower/FrameworkBenchmarks/pull/5095#issuecomment-536919785

### CODE REVIEW

**Comment by joanhey** [comment]
The results are impresive, if the test is correct.
We need to update the plain workerman to reflect it.

**Comment by joanhey** [comment]
I think the code have anything wrong.
This result is impossible;
https://www.techempower.com/benchmarks/#section=test&runid=42f65a64-69b2-400d-b24e-20ecec9848bc&hw=ph&test=query

**Comment by jcheron** [comment]
I have the same doubts as you do...
The tests never check the content of the request or the content-length when there is concurrent access?

**Comment by joanhey** [comment]
The travis tests check all that.
But can't check any cache inside the code.
Perhaps you left any cache in the code.

**Comment by joanhey** [comment]
Anyway It will be good to investigate from where come that gain.
Even if it is from a cache.

**Comment by jcheron** [comment]
I'll check for the cache, but I don't think that's it. This should be explicitly stated in the configuration.

**Comment by joanhey** [comment]
Try to change to use PDO or pgsql instead of mysqli.
And we will check what happens.

**Comment by joanhey** [comment]
I will try in the plain workerman to use mysqli.

**Comment by jcheron** [comment]
Yes, and I would like workerman-mysqli to be much faster than the current Ubiquity-workerman

**Pull request merged**
