### PR TITLE
Increase pgsql connections

### PR DESCRIPTION
**Pull request by GMLudo**
As promised in #1394, I increase PostgreSQL max_connections.
Maybe it will be necessary to change maximum shared memory on server.

### CODE REVIEW

**Comment by GMLudo** [comment]
I've tested your configuration file with my PostgreSQL.
PostgreSQL doesn't start until I change kernel.sem: `sudo sysctl -w kernel.sem="250 32000 256 256"`

Where is your `/etc/sysctl.d/99-boost.conf` file in your repository to change kernel settings ?

Moreover, I've compared your `postgresql.conf` config file with mine, I've three extra parameters:
> shared_buffers = 128MB
> work_mem = 32MB
> maintenance_work_mem = 64MB

**Comment by msmith-techempower** [comment]
I don't know what any of this means >_<

Additionally, we want to touch the system as little as possible with the suite, so I'm unnerved by allowed changes to `/etc/sysctl.d/99-boost.conf`.

**Comment by GMLudo** [comment]
> I don't know what any of this means >_<

If you already have a PostgreSQL with 2000 max_connections, we must already change kernel settings somewhere ;-)

> Additionally, we want to touch the system as little as possible with the suite, so I'm unnerved by allowed changes to /etc/sysctl.d/99-boost.conf.

First, be cool, it's only a benchmark, no human lifes are in the game ;-)
Second, in fact, you already change kernel settings, not with a config file but with a command line, but it's the same effect at the end. It means, you're already agree to do that ;-)
See: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/benchmarker.py#L377
I've added in my PR the changes for that.
I can't test myself, do you plan to relaunch benchmarks before the D-day this Friday  ?

**Comment by hamiltont** [comment]
> Second, in fact, you already change kernel settings, not with a config file but with a command line, but it's the same effect at the end. 

Agreed - this is already happening. 

@GMLudo - IMO two excellent additions to the database sysctl settings would be 1) a link to some documentation for each parameter (or just a human-readable explanation?) and 2) adding something like `echo Printing kernel configuration && sudo sysctl -a` at the end. If you have a moment to add either of those it would help out

**Comment by GMLudo** [comment]
@hamiltont ok, I'll add that tomorrow, I need to sleep right now.
BTW, is it possible to launch something to test this script easily without launch all benchmark suite ?

**Comment by hamiltont** [comment]
Nothing easy. Your best bet is to test it using our [vagrant development setup](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/deployment/vagrant-development) which will launch a single virtual machine and configure it to be the application server, the database server, and the client load generation server.

**Comment by GMLudo** [comment]
Hi,

I've added explanations + add some parameters that seems to improve a little bit performance, at least on my postgresql setup.
I've issues to test that with vagrant, I've tested only on my setup.

Regards.

**Comment by hamiltont** [comment]
This LGTM

**Comment by GMLudo** [comment]
Thanks for the merge.

**Pull request merged**
