### PR TITLE
Phalcon-mongodb tag broken and faster sort

### PR DESCRIPTION
**Pull request by joanhey**
In the logs when verify the phalcon-mongodb:
`PHP Fatal error:  Uncaught Error: Class 'Phalcon\Mvc\Collection' not found in /phalcon/vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php`

I's a bug in Phalcon mongodb:
https://github.com/phalcon/incubator/issues/880
**So tag broken, till fixed.**

Faster sort in all variants for fortunes test.

### CODE REVIEW

**Comment by jenovateurs** [comment]
Hi @joanhey,
Thanks for fixing Phalcon tests.
I work on the Phalcon project so I can help you, if you need :-).
You can find me on Phalcon Discord.

**Comment by joanhey** [comment]
Hi,
You know more the framework, to optimize better.
Curiously the new v4 is slower.

Last run:
https://www.techempower.com/benchmarks/#section=test&runid=8dca2265-62dc-4532-854b-9959afe18652&hw=ph&test=json&l=zik073-1r

And the phalcon micro v4, have a problem that show the logs.
Perhaps you could help in update and optimize Phalcon.
https://tfb-status.techempower.com/unzip/results.2020-04-20-07-27-56-665.zip/results/20200415180849/phalcon-micro/run/phalcon-micro.log
It's passing the travis and local tests, so perhaps it is a problem in the benchmark stack.
But will be good the check it.

You can check the continuous runs in https://tfb-status.techempower.com/
And the Phalcon code:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/PHP/phalcon

Thank you

**Comment by joanhey** [comment]
And please check the core of your ORM.
It's creating a lot of unnecessary extra sql calls.
https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/675977136#L897-L1045

This benchmark is a really good tool to find problems.

**Comment by jenovateurs** [comment]
Thanks @joanhey. I will check that 👍

**Comment by joanhey** [comment]
Also I think the error in micro about connecting to the database.
Looks like the micro don't use persistent db connection.
That's only in v4, before was ok.

**Pull request merged**
