### PR TITLE
Update http4s to v0.18.7

### PR DESCRIPTION
**Pull request by felixmulder**
Hello! This PR simply updates http4s to the most recent version (0.18.7)

### CODE REVIEW

**Comment by felixmulder** [comment]
Failing tests are not http4s :)

**Comment by rossabaker** [comment]
@felixmulder Thanks!  @emilypi has done [quite a bit of work](https://github.com/emilypi/FrameworkBenchmarks), but I don't think has PR'ed her work yet.  Felix asked on Gitter about efficiency, which Emily has started addressing.  I think it would be best to focus on Emily's as a basis, refresh the patch versions, and then discuss any further improvements on that.

**Comment by felixmulder** [comment]
I'd be happy to close this in favor of merging @emilypi's branch instead.

@emilypi - if you don't have time to finalize this, let me know and I'll try to make time for it early the coming week.

**Comment by emilypi** [comment]
@felixmulder It's great to see other people working on this too and I'd be happy to work together on this 😄 

I've got time this week to finalize the few DB-related bits that are left. Feel free to submit a PR to my rewrite if you see any bits that can be improved.

**Pull request closed without merging**
