### PR TITLE
Upgrade to Blaze 0.14.0-M3 + replace Jackson by jsoniter-scala

### PR DESCRIPTION
**Pull request by plokhotnyuk**
It should be the most efficient setup for JSON and plaintext benchmarks of the Blaze server.
On my notebook I got quite acceptable results at 250K rate of incoming requests.
Here is output of wrk2 client:
```sh
$ ./wrk -c50 -d1m -t4 -R250000 -L -v http://localhost:8080/json
wrk 4.0.0 [epoll] Copyright (C) 2012 Will Glozer
Running 1m test @ http://localhost:8080/json
  4 threads and 50 connections
  Thread calibration: mean lat.: 8.455ms, rate sampling interval: 39ms
  Thread calibration: mean lat.: 9.254ms, rate sampling interval: 40ms
  Thread calibration: mean lat.: 5.579ms, rate sampling interval: 18ms
  Thread calibration: mean lat.: 6.755ms, rate sampling interval: 30ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.84ms    2.32ms  39.36ms   92.85%
    Req/Sec    63.84k     5.80k  107.94k    82.25%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.27ms
 75.000%    2.07ms
 90.000%    3.43ms
 99.000%   12.78ms
 99.900%   23.87ms
 99.990%   32.56ms
 99.999%   36.61ms
100.000%   39.39ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.016     0.000000            1         1.00
       0.368     0.100000      1250756         1.11
       0.616     0.200000      2497982         1.25
       0.847     0.300000      3748208         1.43
       1.060     0.400000      4994390         1.67
       1.270     0.500000      6243721         2.00
       1.390     0.550000      6869745         2.22
       1.526     0.600000      7494431         2.50
       1.681     0.650000      8117148         2.86
       1.860     0.700000      8741071         3.33
       2.069     0.750000      9367343         4.00
       2.189     0.775000      9677651         4.44
       2.331     0.800000      9989385         5.00
       2.509     0.825000     10303180         5.71
       2.735     0.850000     10613151         6.67
       3.033     0.875000     10925990         8.00
       3.217     0.887500     11081075         8.89
       3.435     0.900000     11236485        10.00
       3.705     0.912500     11393370        11.43
       4.047     0.925000     11549169        13.33
       4.499     0.937500     11705488        16.00
       4.787     0.943750     11783137        17.78
       5.135     0.950000     11861397        20.00
       5.559     0.956250     11938762        22.86
       6.119     0.962500     12016974        26.67
       6.847     0.968750     12094805        32.00
       7.315     0.971875     12134034        35.56
       7.859     0.975000     12172776        40.00
       8.527     0.978125     12212091        45.71
       9.279     0.981250     12250853        53.33
      10.239     0.984375     12289932        64.00
      10.815     0.985938     12309493        71.11
      11.479     0.987500     12328894        80.00
      12.255     0.989062     12348495        91.43
      13.159     0.990625     12367994       106.67
      14.255     0.992188     12387407       128.00
      14.903     0.992969     12397194       142.22
      15.583     0.993750     12406908       160.00
      16.311     0.994531     12416670       182.86
      17.119     0.995313     12426474       213.33
      18.015     0.996094     12436282       256.00
      18.527     0.996484     12441113       284.44
      19.087     0.996875     12445985       320.00
      19.775     0.997266     12450842       365.71
      20.591     0.997656     12455704       426.67
      21.327     0.998047     12460531       512.00
      21.695     0.998242     12462999       568.89
      22.111     0.998437     12465448       640.00
      22.591     0.998633     12467880       731.43
      23.183     0.998828     12470310       853.33
      23.983     0.999023     12472730      1024.00
      24.463     0.999121     12473924      1137.78
      25.007     0.999219     12475147      1280.00
      25.711     0.999316     12476358      1462.86
      26.511     0.999414     12477589      1706.67
      27.295     0.999512     12478811      2048.00
      27.727     0.999561     12479406      2275.56
      28.239     0.999609     12480019      2560.00
      28.767     0.999658     12480643      2925.71
      29.375     0.999707     12481243      3413.33
      29.983     0.999756     12481844      4096.00
      30.303     0.999780     12482150      4551.11
      30.623     0.999805     12482459      5120.00
      30.959     0.999829     12482767      5851.43
      31.423     0.999854     12483068      6826.67
      32.015     0.999878     12483371      8192.00
      32.351     0.999890     12483525      9102.22
      32.607     0.999902     12483675     10240.00
      32.991     0.999915     12483834     11702.86
      33.343     0.999927     12483978     13653.33
      33.791     0.999939     12484136     16384.00
      34.015     0.999945     12484208     18204.44
      34.303     0.999951     12484292     20480.00
      34.655     0.999957     12484363     23405.71
      35.039     0.999963     12484439     27306.67
      35.295     0.999969     12484511     32768.00
      35.391     0.999973     12484570     36408.89
      35.455     0.999976     12484598     40960.00
      35.615     0.999979     12484628     46811.43
      35.871     0.999982     12484670     54613.33
      36.095     0.999985     12484702     65536.00
      36.223     0.999986     12484723     72817.78
      36.319     0.999988     12484740     81920.00
      36.511     0.999989     12484760     93622.86
      36.735     0.999991     12484780    109226.67
      37.023     0.999992     12484797    131072.00
      37.151     0.999993     12484807    145635.56
      37.311     0.999994     12484818    163840.00
      37.439     0.999995     12484827    187245.71
      37.599     0.999995     12484837    218453.33
      37.759     0.999996     12484846    262144.00
      37.823     0.999997     12484850    291271.11
      37.919     0.999997     12484855    327680.00
      37.983     0.999997     12484860    374491.43
      38.079     0.999998     12484864    436906.67
      38.239     0.999998     12484870    524288.00
      38.303     0.999998     12484871    582542.22
      38.335     0.999998     12484873    655360.00
      38.431     0.999999     12484878    748982.86
      38.431     0.999999     12484878    873813.33
      38.591     0.999999     12484881   1048576.00
      38.687     0.999999     12484882   1165084.44
      38.751     0.999999     12484883   1310720.00
      38.815     0.999999     12484884   1497965.71
      38.879     0.999999     12484885   1747626.67
      39.039     1.000000     12484887   2097152.00
      39.039     1.000000     12484887   2330168.89
      39.135     1.000000     12484888   2621440.00
      39.135     1.000000     12484888   2995931.43
      39.199     1.000000     12484889   3495253.33
      39.263     1.000000     12484890   4194304.00
      39.263     1.000000     12484890   4660337.78
      39.263     1.000000     12484890   5242880.00
      39.263     1.000000     12484890   5991862.86
      39.327     1.000000     12484891   6990506.67
      39.327     1.000000     12484891   8388608.00
      39.327     1.000000     12484891   9320675.55
      39.327     1.000000     12484891  10485760.00
      39.327     1.000000     12484891  11983725.71
      39.391     1.000000     12484892  13981013.34
      39.391     1.000000     12484892          inf
#[Mean    =        1.840, StdDeviation   =        2.318]
#[Max     =       39.360, Total count    =     12484892]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  14992553 requests in 1.00m, 2.01GB read
Requests/sec: 249877.24
Transfer/sec:     34.32MB
```

### CODE REVIEW

**Comment by plokhotnyuk** [comment]
Also, I profiled it at that 250K rate with async-profiler and got less that 1% of CPU usage for whole jsoniter-scala stuff (it is highlighted by magenta in the flame graph bellow):
image
You can download it from the following gist and open as a file in browser (to explore it interactively by clicking on different stack frames and search methods by Ctrl+F): https://gist.github.com/plokhotnyuk/03c8fbe4c940a83ef05c1a598b22eafb

**Comment by plokhotnyuk** [comment]
For HTTP/1.1+pipelining the following Lua script was used:
```lua
local pipelineDepth = 1
local counter = 0
local maxRequests = -1

function init(args)
   if args[1] ~= nil then
      pipelineDepth = tonumber(args[1])
   end

   local r = {}
   for i = 1, pipelineDepth, 1 do
      r[i] = wrk.format(nil)
   end

   print("Pipeline depth: " .. pipelineDepth)

   if args[2] ~= nil then
      maxRequests = tonumber(args[2])
      print("Max requests: " .. maxRequests)
   end

   req = table.concat(r)
end

function request()
   return req
end

function response()
   if counter == maxRequests then
     wrk.thread:stop()
   end
   counter = counter + 1
end
```
Here are command to run wrk2 and its results:
```sh
 ./wrk --latency -d 15 -c 256 --timeout 8 -t 4 -s pipeline.lua -R500000 http://localhost:8080/plaintext -- 16
Pipeline depth: 16
Pipeline depth: 16
Pipeline depth: 16
Pipeline depth: 16
Running 15s test @ http://localhost:8080/plaintext
  4 threads and 256 connections
  Thread calibration: mean lat.: 1.635ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.626ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 2.042ms, rate sampling interval: 10ms
  Thread calibration: mean lat.: 1.680ms, rate sampling interval: 10ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.73ms    1.10ms  20.74ms   79.73%
    Req/Sec   132.07k    21.30k  262.89k    76.40%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    1.55ms
 75.000%    2.20ms
 90.000%    2.92ms
 99.000%    4.98ms
 99.900%   12.60ms
 99.990%   17.60ms
 99.999%   18.45ms
100.000%   20.75ms

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.046     0.000000            1         1.00
       0.665     0.100000       234498         1.11
       0.903     0.200000       468443         1.25
       1.120     0.300000       702403         1.43
       1.334     0.400000       936610         1.67
       1.554     0.500000      1169824         2.00
       1.669     0.550000      1286710         2.22
       1.789     0.600000      1403787         2.50
       1.914     0.650000      1521357         2.86
       2.051     0.700000      1639080         3.33
       2.205     0.750000      1755529         4.00
       2.291     0.775000      1813799         4.44
       2.385     0.800000      1872227         5.00
       2.491     0.825000      1930765         5.71
       2.609     0.850000      1988768         6.67
       2.749     0.875000      2046958         8.00
       2.833     0.887500      2076191         8.89
       2.925     0.900000      2105645        10.00
       3.029     0.912500      2134673        11.43
       3.149     0.925000      2164291        13.33
       3.295     0.937500      2193274        16.00
       3.385     0.943750      2208030        17.78
       3.479     0.950000      2222510        20.00
       3.599     0.956250      2237145        22.86
       3.739     0.962500      2251579        26.67
       3.895     0.968750      2266209        32.00
       3.989     0.971875      2273602        35.56
       4.089     0.975000      2280861        40.00
       4.207     0.978125      2288114        45.71
       4.339     0.981250      2295606        53.33
       4.499     0.984375      2302761        64.00
       4.611     0.985938      2306458        71.11
       4.735     0.987500      2310060        80.00
       4.879     0.989062      2313740        91.43
       5.067     0.990625      2317408       106.67
       5.299     0.992188      2321046       128.00
       5.431     0.992969      2322840       142.22
       5.627     0.993750      2324676       160.00
       5.927     0.994531      2326489       182.86
       6.279     0.995313      2328313       213.33
       6.779     0.996094      2330159       256.00
       7.147     0.996484      2331079       284.44
       7.507     0.996875      2331975       320.00
       8.183     0.997266      2332884       365.71
       8.943     0.997656      2333803       426.67
       9.863     0.998047      2334718       512.00
      10.303     0.998242      2335174       568.89
      10.687     0.998437      2335623       640.00
      11.471     0.998633      2336079       731.43
      12.095     0.998828      2336538       853.33
      12.679     0.999023      2336998      1024.00
      13.119     0.999121      2337227      1137.78
      13.519     0.999219      2337454      1280.00
      14.063     0.999316      2337681      1462.86
      14.527     0.999414      2337909      1706.67
      15.327     0.999512      2338138      2048.00
      15.463     0.999561      2338251      2275.56
      15.655     0.999609      2338365      2560.00
      15.863     0.999658      2338486      2925.71
      16.055     0.999707      2338599      3413.33
      16.703     0.999756      2338729      4096.00
      16.719     0.999780      2338767      4551.11
      16.959     0.999805      2338826      5120.00
      17.103     0.999829      2338882      5851.43
      17.199     0.999854      2338938      6826.67
      17.519     0.999878      2338993      8192.00
      17.567     0.999890      2339028      9102.22
      17.599     0.999902      2339058     10240.00
      17.791     0.999915      2339083     11702.86
      17.823     0.999927      2339113     13653.33
      17.951     0.999939      2339143     16384.00
      17.983     0.999945      2339161     18204.44
      17.999     0.999951      2339184     20480.00
      17.999     0.999957      2339184     23405.71
      18.015     0.999963      2339193     27306.67
      18.127     0.999969      2339209     32768.00
      18.255     0.999973      2339213     36408.89
      18.271     0.999976      2339225     40960.00
      18.431     0.999979      2339237     46811.43
      18.431     0.999982      2339237     54613.33
      18.447     0.999985      2339257     65536.00
      18.447     0.999986      2339257     72817.78
      18.447     0.999988      2339257     81920.00
      18.447     0.999989      2339257     93622.86
      18.447     0.999991      2339257    109226.67
      18.575     0.999992      2339269    131072.00
      18.575     0.999993      2339269    145635.56
      18.575     0.999994      2339269    163840.00
      18.575     0.999995      2339269    187245.71
      18.575     0.999995      2339269    218453.33
      18.575     0.999996      2339269    262144.00
      18.575     0.999997      2339269    291271.11
      18.591     0.999997      2339273    327680.00
      18.591     0.999997      2339273    374491.43
      18.591     0.999998      2339273    436906.67
      18.591     0.999998      2339273    524288.00
      18.591     0.999998      2339273    582542.22
      20.735     0.999998      2339275    655360.00
      20.735     0.999999      2339275    748982.86
      20.735     0.999999      2339275    873813.33
      20.735     0.999999      2339275   1048576.00
      20.735     0.999999      2339275   1165084.44
      20.751     0.999999      2339277   1310720.00
      20.751     1.000000      2339277          inf
#[Mean    =        1.732, StdDeviation   =        1.096]
#[Max     =       20.736, Total count    =      2339277]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  7316364 requests in 15.00s, 0.89GB read
Requests/sec: 487756.33
Transfer/sec:     60.47MB
```

**Comment by plokhotnyuk** [comment]
Flamegraph for HTTP/1.1+pipelining:
image
and corresponding *.svg of this graph: https://gist.github.com/plokhotnyuk/4eecd876132629237e67248587a116fc

**Comment by rossabaker** [comment]
Did you take any intermediate measurements?  It's hard to tell what the baseline was on this hardware, what's attributable to the JVM settings vs. the JSON library, etc.

**Comment by plokhotnyuk** [comment]
@rossabaker Yes, I tried with different rates and done it continuously during adding changes or step out from defaults.

You are right it is hard to find the best solution to all cases. Main goal here is to win round-16 of the contest with latest version of the Blaze server (0.14.0-M3), but some changes (like using separated thread pool for request handling) and intermediate results (like flame graphs) can be used for improvements in the blaze repo if you find them valuable.

Currently, all benchmarks run over the master branch on daily basis and you can get and analyze results of each run on both envs. from the following page: https://tfb-status.techempower.com/

Also, there is an intermediate report for round-16: 
- JSON (HTTP/1.1) https://www.techempower.com/benchmarks/previews/round16/#section=data-r16&hw=ph&test=json
- Plaintext (HTTP/1.1+pipelining) https://www.techempower.com/benchmarks/previews/round16/#section=data-r16&hw=ph&test=plaintext

**Pull request merged**
