### PR TITLE
Fix of unmetting dependencies of setup in preview4

### PR DESCRIPTION
**Pull request by treefrogframework**
Found setup-error in round 14 preview 4. Setup in preview2 has been successful.
http://tfb-logs.techempower.com/round-14/preview-4/treefrog/out.txt

CHANGES:
 Setup file updated.

### CODE REVIEW

**Comment by dantti** [comment]
hey @treefrogframework , I'd recommend you to use a more recent Qt build, instead of ubuntu-sdk-ppa could use 5.6.2 from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt562-trusty as I do for Cutelyst framework, for threaded applications 5.8 brings a few improvements but the PPA creator didn't enable PostgreSQL driver on 5.8 so I'm using the 5.6 as it's also LTS.

**Comment by nbrady-techempower** [comment]
@treefrogframework I'll get this merged in so you have working results. Feel free to open a new PR if what @dantti is saying works for you

**Comment by treefrogframework** [comment]
@nbrady-techempower Thanks for merging!
But the problem may not be resolved. Repositories of Qt packages are two or more, so I don't know whether apt-get command can resolve package dependencies when you perform benchmarking.
 - Cutelyst: ppa:beineri/opt-qt56
 - TreeFrog: ppa:ubuntu-sdk-team/ppa

I think one repository is best.

**Comment by dantti** [comment]
@treefrogframework The beineri PPA doesn't conflict with Ubuntu's Qt's because their naming and installation have 'opt' on in, you even need to source a file to properly point to the right location.
Also Cutelyst minimum Qt version is 5.6 due features and a behavior change in QUrl.

**Pull request merged**
