### PR TITLE
Share the results folder

### PR DESCRIPTION
**Pull request by joanhey**
in vagrant, for easier view and manage.
Still the contents in the folder are ignored by Git.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@joanhey I'd have to play with this on monday. My concern is what happens on windows when you run the `tfb --clean-all` command or otherwise try and remove the results directory. I don't think this would work.

**Comment by joanhey** [comment]
It is really useful, perhaps `tfb --clean-all`, will delete the contents in the folder and not the folder.
Because remove the directory, will give problems, the same that remove the toolset directory or any other.

**Comment by nbrady-techempower** [comment]
@joanhey Those are fair points. I believe there were some reasons for not doing this before, some other intricacies of the toolset that may be resolved now. I'll do some testing on this and make appropriate changes. I agree with you.

**Comment by nbrady-techempower** [comment]
Hey @joanhey closing for #2732 - Thanks for pointing this out. I did it in a way that doesn't require the results directory being in the repo as well.

**Pull request closed without merging**
