### PR TITLE
PostgreSQL JDBC driver version bump 

### PR DESCRIPTION
**Pull request by zloster**
Now using version 9.3-1102-jdbc41(for Java 7/8). See the [documentation](http://jdbc.postgresql.org/download.html).
Please note the file: ./installs/resin-4.0.41/webapps/servlet/META-INF/maven/hello.world/world/pom.xml also contains PostgreSQL JDBC driver dependency but it seems it is generated. So I'm not sure where it gets the dependencies. Someone should check.

### CODE REVIEW

**Comment by hamiltont** [comment]
LGTM, thanks!

**Comment by zloster** [comment]
It's a little funny but I've just checked and there is a newer version of the PostgreSQL JDBC: Version 9.4-1200 (2015-01-02) and Version 9.3-1103 (2015-01-02). See [Change log](https://jdbc.postgresql.org/documentation/changelog.html).

**Comment by hamiltont** [comment]
Oh lord. Well if you want to send in another PR, it's a quick merge

**Comment by zloster** [comment]
The new PR [TechEmpower/FrameworkBenchmarks#1358](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1358)

**Pull request merged**
