### PR TITLE
Improve Swift/Vapor Implementation

### PR DESCRIPTION
**Pull request by tanner0101**
This PR simplifies the implementation for Swift/Vapor's benchmark tests. It also updates the packages to their latest versions which have performance improvements.

### CODE REVIEW

**Comment by tanner0101** [comment]
Assuming everything looks good on your end, this is ready to be merged. Thanks!

**Comment by tanner0101** [comment]
Side question, is it noted anywhere what the maximum number of connections the built in PostgreSQL server can handle? I've currently set Vapor to use up to 8 connections per logical core. Depending on how the PostgreSQL server is configured it could make sense to change that number.

**Comment by nbrady-techempower** [comment]
Postgres config is located here: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/toolset/databases/postgres

And we run our continuous benchmarking and official rounds on the Citrine environment:
https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Environment#citrine-self-hosted

**Comment by tanner0101** [comment]
@nbrady-techempower wonderful, thanks!

**Comment by tanner0101** [comment]
Anything else this needs before we can merge?

**Comment by tanner0101** [comment]
Thanks!

**Pull request merged**
