### PR TITLE
Add Hanami framework to Ruby

### PR DESCRIPTION
**Pull request by Jesterovskiy**

### CODE REVIEW

**Comment by Jesterovskiy** [comment]
@jodosha you are welcome to review =)

**Comment by nbrady-techempower** [comment]
Hi @Jesterovskiy 

You're on fire lately! Thanks for all your contributions!

For this, would you mind removing some of the extraneous files and folders like `frameworks/Ruby/hanami/apps/web/assets/javascripts/.gitkeep` and any of the `development` or `test` files that aren't needed for this to run on our suite.

**Comment by jodosha** [comment]
@Jesterovskiy Thanks for adding Hanami!

You want to make sure to run `HANAMI_ENV=production bundle exec hanami assets precompile` before to start the project in production mode.

**Comment by Jesterovskiy** [comment]
@jodosha I don't use assets at all. Most of tests is JSON and only one use View and Template

**Comment by nbrady-techempower** [comment]
@Jesterovskiy thanks for shrinking that down. looks good :)

**Comment by nbrady-techempower** [comment]
@Jesterovskiy The fortune tests seem to be failing on all travis runs for hanami. Would you mind taking a look at it if you have some time?

**Comment by Jesterovskiy** [comment]
@nbrady-techempower thank you, I'll check tomorrow

**Pull request merged**
