### PR TITLE
Kemalyst - fix process count

### PR DESCRIPTION
**Pull request by drujensen**
This change changes the process count to match the number of processors.

### CODE REVIEW

**Comment by faustinoaq** [comment]
@drujensen `!shard.lock` on `.gitignore` is missing?

**Comment by drujensen** [comment]
@faustinoaq I failed the preview because there were changes to Kemalyst and without the shard.lock checked in, the updates caused the failure.

**Comment by drujensen** [comment]
@nbrady-techempower This is ready to be merged.  Thanks!

**Comment by RX14** [comment]
@drujensen `*.lock` is in the root `.gitignore` so `!shard.lock` is required in the local `.gitignore` to unignore `shard.lock`. I think the current `shard.lock` has been added to the index despite the gitignore.

**Comment by faustinoaq** [comment]
@drujensen Do you think version should be removed? Just like Amber version
in shard.yml

In Kemalyst:

```yaml
dependencies:
  kemalyst:
    github: kemalyst/kemalyst
    version: ~> 0.10.0

  kemalyst-model:
    github: kemalyst/kemalyst-model
    version: ~> 0.6.0
```

In Amber:

```
dependencies:
  amber:
    github: Amber-Crystal/amber

  granite_orm:
    github: Amber-Crystal/granite-orm
```

**Comment by drujensen** [comment]
@faustinoaq yes, thanks.  fixed.

**Comment by drujensen** [comment]
@nbrady-techempower This is ready.  Will these changes show up in preview 2 or preview 3?

**Comment by nbrady-techempower** [comment]
Thanks @drujensen More than likely, everything submitted over the next week will show up in Preview 3.

**Pull request merged**
