### PR TITLE
Scala with Akka HTTP with Circe and Slick and Postgres

### PR DESCRIPTION
**Pull request by sourcekick**
Hi,

being aware that there is already a variant with Akka HTTP online, I wrote a rather different implementation based on Akka HTTP in just the stack that I use.

It is based on

- Akka HTTP

- Akka Streams (I tried to go the streaming way as far as the requirements allowed for it, further improvements in this area might follow later)

- Slick (Funtional-Relational Mapping, there are some other variants online making use of it through the Play framework)

- Circe (JSON binding, based on functional programming and therefore uses Cats internally)

- Scalate (for rendering the Fortunes HTML, just as in the other existing AKKA HTTP implementation)

I am very interested to see how this implementation performs and how I can tune it more, and I hope the contribution is appreciated.

I studied the history of .travis.yml and I think that projects for Scala are automatically detected. Therefore I am not editing .travis.yml and please correct me if I am wrong.

Thank you for putting up and maintaining such a great benchmark framework!

Cheers,
Sven

PS: On my machine the verification went perfectly. Fingers crossed it works on the benchmark environments as well without issues.

### CODE REVIEW

**Comment by sourcekick** [comment]
While the overall job is still running, my contribution had a green run: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/486699409

**Comment by nbrady-techempower** [comment]
Hey @sourcekick This looks good. The only thing I'll ask is that you move it to the `akka-http` framework directory and add this configuration to that `benchmark_config.json`. `akka-http-slick-postgres` is a permutation and doesn't look right as a "new framework".

**Comment by sourcekick** [comment]
@nbrady-techempower Is there something specific I have to do so that the test (my akka-http permutation akka-http-slick-postgres) will actually be run on the benchmarks? Although I checked FAQs, docs and sources, I am still in the dark regarding this point. Perhaps I overlooked something. Is there a way to check locally whether this will happen also on the environments?

**Comment by sourcekick** [comment]
@nbrady-techempower I now from my point of view finished your requirement and pushed all changes. So you can check it out and answer my above question on the basis of the code.

PS: I also made some drive-by dependency updates in the existing akka-http.

**Comment by sourcekick** [comment]
Regarding verification it was successful:

https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/488585303

```
================================================================================
Verification Summary
--------------------------------------------------------------------------------
| akka-http
|       fortune       : PASS
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS
| akka-http-slick-postgres
|       fortune       : PASS
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS
================================================================================
```

**Comment by nbrady-techempower** [comment]
There is nothing more you need to do. When https://tfb-status.techempower.com starts the next run it will pull from this master branch and your permutation will be in there. Thanks!

**Pull request merged**
