### PR TITLE
Fix Nginx as the front end tests by putting uwsgi socket in /var/tmp …

### PR DESCRIPTION
**Pull request by dantti**
Most (maybe all) frameworks using Nginx and uwsgi are failing due /tmp being privately visible to uwsgi, the "proper" fix would be to put it in /run but it isn't writable by testuser so I'm putting it in /vat/tmp
bottle and flask are two I saw that need this kind of fix

### CODE REVIEW

**Comment by methane** [comment]
Python's uwsgi benches are suffered same issue.

I didn't understand what cause this issue.
Systemd has PrivateTmp feature. But we start nginx without systemd, am I wrong?

If PrivateTmp cause this, `/var/tmp` has same issue.
How about making `${FWROOT}/run` directory?

**Comment by dantti** [comment]
@methane I really dunno how exactly PrivateTmp works, but what I could see is that this is the exactly behavior happening in these runs, once I changed the directory nginx worked fine, I also needed to increase uwsgi listen backlog othewise there are some of resource unavailable

**Comment by msmith-techempower** [comment]
> failing due /tmp being privately visible

Wat. Are you saying that the permissions on `/tmp` need to be relaxed so the suite can write to it?

ping @ashawnbandy-te-tfb

**Comment by ashawnbandy-te-tfb** [comment]
@methane @dantti I'm not sure that I am following.  Will opening up the permissions on /tmp to make it writable by all negate the need for a workaround?  If, so I just made the change in our testing environment that should be included in the next preview run which is coming up shortly.

**Comment by dantti** [comment]
@aschneider-techempower the nginx log lists that it coult not connect to the unix socket, giving no such file or directory, so in fact I'm not sure if it's just a permissions issue. It looks like there is some different feature in use here, that gets better described by "temporary namespaced directory" which is a feature distros like Fedora has by default so that one application doesn't see other app's /tmp. This improves security as lots of CVE are due insecure /tmp writes...

**Comment by msmith-techempower** [comment]
This FEELS like a permissions issue on the `/tmp` dir and nothing more.

**Comment by dantti** [comment]
For the record I wrote this workaround for Cutelyst due:
http://stackoverflow.com/questions/32974204/got-no-such-file-or-directory-error-while-configuring-nginx-and-uwsgi
Which has a link to another SO page containing this other link:
http://fedoraproject.org/wiki/Features/ServicesPrivateTmp
Which feels like this issue, because if it was a permission issue the error would be permission denied:

> 2014/02/17 03:42:20 [crit] 5455#0: *1 connect() to unix:/tmp/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: xx.xx.x.xxx, server: localhost, request: "GET /users HTTP/1.1", upstream: "uwsgi://unix:/tmp/uwsgi.sock:", host: "EC2.amazonaws.com"

**Comment by msmith-techempower** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOOOKAY

I get it now.

@ashawnbandy-te-tfb We MAY need to look deeper into this... may be the cause of some of our handle-problems.

**Comment by methane** [comment]
@ashawnbandy-te-tfb @msmith-techempower Should I update Python frameworks too?

**Comment by msmith-techempower** [comment]
@methane I think we need to do an audit across **any** framework that uses nginx... scary.

**Comment by ashawnbandy-te-tfb** [comment]
@methane @msmith-techempower I agree.  At a minumum, we should start with uwsgi and nginx.

**Comment by dantti** [comment]
@aschneider-techempower @msmith-techempower I was checking the new preview run to see how Cutelyst threaded was performing now that when it segfaults (as master if freeze for the fix) the --master workaround will restart it and found the following line:
--------------------------------------------------------------------------------
  Error: Could not empty /tmp
--------------------------------------------------------------------------------
Isn't your scripts cleaning /tmp at the wrong time so when nginx runs the socket isn't there?
Because when --mode test runs it works...

**Comment by msmith-techempower** [comment]
That is a known issue, but should not impact your run.

**Pull request merged**
