### PR TITLE
Use .NET Core 2.0.0-preview1

### PR DESCRIPTION
**Pull request by dougbu**
- move from dotnet-dev-1.0.0-preview2.1-003177 to dotnet-dev-2.0.0-preview1
- convert .NET Core Benchmarks project from project.json to .csproj
  - use latest available versions of all dependencies
- catch up with latest code in Microsoft ASP.NET fork
  - do not grab scoped services when constructing singletons; primarily affects DbContexts
  - compile EF queries
  - WebListener -> HttpSys
  - enable specific requested scenarios e.g. don't support /mvc/plaintext when plaintext requested
  - remove hack and use `response.ContentLength` property; hack no longer a significant optimization
  - remove use of old PlatformAbstractions package
- publish as part of test scenarios and enable MVC Razor Precompilation
- change `DebugInfoPageMiddleware` to return 404 status code
  - prevent apparent success when "benchmarking" incorrect URLs
- add appsettings.json file for Windows runs; use LocalDb by default on Windows

Improve database scenario performance (beyond compiling EF queries)
- enforce Max Auto Prepare for PostgreSQL EF/Dapper
  - merge from https://github.com/roji/FrameworkBenchmarks.git dougbu/update.net.core-autoprepare
  - thanks @roji!
  - The "Max Auto Prepare" connection string parameter is important for PostgreSQL performance when running
    EF/Dapper benchmarks. Added this parameter in appsetings.postgresql.json and a check for its existence
    on benchmark startup.
- `Prepare()` the update command in `RawDb.LoadMultipleUpdatesRows()`
  - may improve performance with Postgres even though the command is executed just once
- remove `NoTransactionSqlServerConnection` hack; leave auto transactions enabled

nits:
- remove unused tool dependencies
- display where `WebHostBuilder` is found during startup; confirms use of publish folder
- slightly improve Windows scripts
- add appsettings.postgresql.json to csproj
- remove obsolete launchSettings.json
- add and correct links in README.md
- remove duplicate property setting from benchmark_config.json
- clean up whitespace
- more `var`

- simplify `services.AddDbContextPool<TContext>()` delegate

### CODE REVIEW

**Comment by dougbu** [comment]
See aspnet/FrameworkBenchmarks#3 and aspnet/FrameworkBenchmarks#4 for discussion of these changes.

Easier to see what's really changing using `?w=1` in the URL.

**Comment by nbrady-techempower** [comment]
Wow, thanks @dougbu ! It does look like the update tests are failing.

**Comment by dougbu** [comment]
> t does look like the update tests are failing.

Yup, I'm investigating&hellip;

**Comment by dougbu** [comment]
:up::date:

**Comment by dougbu** [comment]
:up::date: Travis finds this version acceptable

**Comment by nbrady-techempower** [comment]
Thanks! Preview 1 is running right now so this will be in Preview 2!

**Comment by patricka2** [comment]
.NET Core enable "LogLevel" default to "Error" by default even by clear "LogLevel" in appsettings.json (Like now) in both production and development mode.
Is not it better to set "LogLevel" default to "Error" instant "Warring" to disable logging like this:
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Pull request merged**
