### PR TITLE
add new test [Java/baseio]

### PR DESCRIPTION
**Pull request by kyle2008**
hi, would you mind merge my pr for a new test "java/baseio"

### CODE REVIEW

**Comment by kyle2008** [comment]
can anyone merge this pr ？

**Comment by kyle2008** [comment]
@nbrady-techempower

**Comment by nbrady-techempower** [comment]
looks good @kyle2008 thanks for your first contribution!

**Comment by kyle2008** [comment]
> looks good @kyle2008 thanks for your first contribution!

thank you!

**Pull request merged**
