### PR TITLE
Bring Spring benchmarks to latest generation.

### PR DESCRIPTION
**Pull request by odrotbohm**
Updated the Spring benchmarks to the latest 3.2 release candidate. Removed obsolete manual configuration. Upgrade Java to 21 and switch back to Tomcat to benefit from virtual threads. Let Docker files consistently use Eclipse Temurin 21.

### CODE REVIEW

**Comment by sdeleuze** [comment]
I am working on additional refinements in collaboration with @odrotbohm, so please wait before merging this PR. We will comment when it will be reader to merge.

**Comment by nbrady-techempower** [comment]
@odrotbohm @sdeleuze Please use the draft functionality if it's not ready

**Comment by odrotbohm** [comment]
Switched to draft as recommended.

**Comment by odrotbohm** [comment]
@sdeleuze is taking over this one to further polish it and create a new request.

**Pull request closed without merging**
