### PR TITLE
upgrade openresty and luarocks

### PR DESCRIPTION
**Pull request by tiwarivikash**

### CODE REVIEW

**Comment by cdbattags** [comment]
@nbrady-techempower how often are y'all going to run updates for micro comparisons like these?

Would love to get the cloud results from this change alone.

**Comment by nbrady-techempower** [comment]
We run continuously on our citrine environment. Do you know about https://tfb-status.techempower.com ?

**Comment by cdbattags** [comment]
Oohoo, I did not know of this! Thank you. Any good place to visualize the results.json output? Or shall I write up a mini +/- table myself for this commit compared to last?

**Comment by nbrady-techempower** [comment]
You can visualize it here https://www.techempower.com/benchmarks/#section=test

**Comment by cdbattags** [comment]
@nbrady-techempower looks like https://www.techempower.com/benchmarks/#section=test is quite unstable with JSON of a certain size

any other way for quick comparisons?

maybe an endpoint to render the comparison page given the raw JSON url?

**Comment by cdbattags** [comment]
Aha! Just found the button. Sorry for my ignorance haha

image

**Pull request merged**
