### PR TITLE
Added SWI-Prolog Http Server

### PR DESCRIPTION
**Pull request by sumeetchhetri**

### CODE REVIEW

**Review by joanhey — CHANGES_REQUESTED** [review]
Add Prolog to the travis tests.
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml

`- "TESTLANG=Prolog"`

**Comment by sumeetchhetri** [comment]
Done

**Comment by nbrady-techempower** [comment]
Please add a README.md here as well. I have no idea what prolog is ;)

**Review by joanhey — CHANGES_REQUESTED** [review]
https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/743172469#L1849-L1853

**Comment by sumeetchhetri** [comment]
Fixed.

**Comment by sumeetchhetri** [comment]
> Please add a README.md here as well. I have no idea what prolog is ;)

Done

**Pull request merged**
