### PR TITLE
Add Oj to Ruby On Rails

### PR DESCRIPTION
**Pull request by jonathantribouharet**
Hi,
I made a little change to the configuration of the Ruby On Rails framework.
You are using the default serializer of Ruby which is known to not be performant.
The Oj gem is not provided out of the box with Rails but it's a must have that every Rails developers have installed.
It's not an opinatied choice, there are only 2 major known / used serializers in Ruby, the default of Ruby and Oj.

Regards,
John

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@jonathantribouharet We've recently enforced this requirement in #4291 

It looks like rails is one of those frameworks that is caching the date header. I doubt the gem you added is responsible for this, but it won't pass until that's taken care of.

**Comment by jonathantribouharet** [comment]
The problem is `config.action_dispatch.default_headers.merge!('Date' => Time.now.httpdate, 'Server' => 'WebServer')` in `config/application.rb`, this line set a header, so the header 'Date' will always be the same value.
I have two questions:
- what is the usage / goal of this header?
- do you want me to fix it in this PR or another?

**Comment by nbrady-techempower** [comment]
@jonathantribouharet In this PR is fine, as we don't want to merge anything new until it passes the travis tests. The headers are just required as part of the tests:

 - The response headers must include either Content-Length or Transfer-Encoding.
 - The response headers must include Server and Date.

We generally don't do the test implementations; we leave that up to the community. So feel free to adjust as you see fit. Thanks!

**Comment by nbrady-techempower** [comment]
Nice work! Thanks for the updates!

**Pull request merged**
