### PR TITLE
[Ktor] Latest Ktor, serializer, html dsl versions

### PR DESCRIPTION
**Pull request by inemtsev**
Updated all Ktor tests to use latest versions and JVM 17.

Kotlin 1.6.21 -> 1.9.22
Ktor 2.0.1 -> 2.3.11
Kotlinx Serializer 1.3.2 -> 1.6.3
Kotlinx Html 0.7.3 -> 0.11.0

JVM 11 -> 17

### CODE REVIEW

**Comment by inemtsev** [comment]
Looks much more up-to-date. Ready to merge.

**Comment by inemtsev** [comment]
Modernized other Ktor-related apps to use the same JVM version and latest dependencies, fixed breaking changes

**Comment by inemtsev** [comment]
**reactivepg-clien**t test is redundant because that library has evolved into **pg-client,** and there is already a test for that.

**Comment by inemtsev** [comment]
Should be ready for tests, runs fine on my machine 😛

**Comment by inemtsev** [comment]
I fixed the config, ready to go

**Comment by inemtsev** [comment]
My apologies, there was more cleanup required to remove legacy test. Should be good now 👍

**Comment by NateBrady23** [comment]
No worries!

**Pull request merged**
