### PR TITLE
Update Clojure/Reitit

### PR DESCRIPTION
**Pull request by ikitommi**
update server & keep just test for best pool size

### CODE REVIEW

**Comment by ikitommi** [comment]
The build seems to fail on something strange:

> techempower/postgres:latest: E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device) [IP: 91.189.88.24 80]

Ideas most welcome how to fix this.

**Comment by nbrady-techempower** [comment]
I'll dig in to this tomorrow @ikitommi -- I've restarted a few times and it looks like a keyserver issue

**Comment by ikitommi** [comment]
Tried to fix this on my side, with no luck.

**Comment by nbrady-techempower** [comment]
@ikitommi Fix is in and tests pass; thanks!

**Comment by ikitommi** [comment]
Awesome, thanks!!

**Pull request merged**
