### PR TITLE
Some Nancy updates

### PR DESCRIPTION
**Pull request by khellang**
This PR includes the following changes:
 - Update Nancy packages to the latest version (1.2)
 - Switch to the JSON.NET based serializer
 - Added Plaintext test, in `PlaintextModule`
 - Made some updates to `DbModule` to leverage async/await

I have no idea if these changes work, since I wasn't able to run the tests. Here's the output I got:

```bash
vagrant@TFB-all:~/FrameworkBenchmarks$ python toolset/run-tests.py --install server --mode verify --test nancy
config/benchmark_profile: line 2: $'\r': command not found
config/benchmark_profile: line 51: syntax error: unexpected end of file
CRITICAL: Loading config/benchmark_profile returned non-zero exit
FWROOT is /home/vagrant/FrameworkBenchmarks
WARNING:root:results.json for test ec2 not found.

INSTALL: Installing server software (strategy=unified)

INSTALL: . $FWROOT/toolset/setup/linux/bash_functions.sh && . $FWROOT/toolset/setup/linux/prerequisites.sh (cwd=$FWROOT/installs)
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 2: $'\r': command not found
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 9: $'\r': command not found
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 10: syntax error near unexpected token `$'{\r''
'home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 10: `fw_get () {

INSTALL ERROR: CalledProcessError: Command '. $FWROOT/toolset/setup/linux/bash_functions.sh && . $FWROOT/toolset/setup/linux/prerequisites.sh' returned non-zero exit status 1


INSTALL: sudo chown -R testrunner:testrunner /home/vagrant/FrameworkBenchmarks/installs (cwd=$FWROOT/installs)
INFO:root:Running installation for directory /home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy (cwd=/home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy)
/home/vagrant/FrameworkBenchmarks/config/benchmark_profile: line 2: $'\r': command not found
/home/vagrant/FrameworkBenchmarks/config/benchmark_profile: line 51: syntax error: unexpected end of file
CRITICAL: Loading $FWROOT/config/benchmark_profile returned non-zero exit
INFO:root:To run installation manually, copy/paste this:
        export FWROOT=/home/vagrant/FrameworkBenchmarks && \
        export TROOT=/home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy && \
        export IROOT=/home/vagrant/FrameworkBenchmarks/installs && \
        cd $IROOT && \
        sudo -u testrunner -E -H bash -c "source $FWROOT/toolset/setup/linux/bash_functions.sh && source /home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy/install.sh"
INSTALL: sudo -u testrunner -E -H bash -c "source $FWROOT/toolset/setup/linux/bash_functions.sh && source /home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy/install.sh" (cwd=$FWROOT//installs)
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 2: $'\r': command not found
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 9: $'\r': command not found
/home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 10: syntax error near unexpected token `$'{\r''
'home/vagrant/FrameworkBenchmarks/toolset/setup/linux/bash_functions.sh: line 10: `fw_get () {

INSTALL ERROR: CalledProcessError: Command 'sudo -u testrunner -E -H bash -c "source $FWROOT/toolset/setup/linux/bash_functions.sh && source /home/vagrant/FrameworkBenchmarks/frameworks/CSharp/nancy/install.sh"' returned non-zero exit status 1


INSTALL: sudo apt-get -yq autoremove (cwd=$FWROOT/installs)
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

INSTALL: Finished installing server software

================================================================================
  Preparing Server, Database, and Client ...
================================================================================

bash: cpu0/cpufreq/scaling_governor: No such file or directory
bash: cpu1/cpufreq/scaling_governor: No such file or directory
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-49-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Apr 23 11:25:01 UTC 2015

  System load:  0.08              Processes:           89
  Usage of /:   3.0% of 39.34GB   Users logged in:     1
  Memory usage: 5%                IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 172.16.0.16

  Graph this data and manage this system at:
    https://landscape.canonical.com/


net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
kernel.sched_autogroup_enabled = 0
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
kernel.shmmax = 2147483648
kernel.shmall = 2097152
kernel.sem = 250 32000 256 512
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-49-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Thu Apr 23 11:29:43 UTC 2015

  System load:  0.08              Processes:           88
  Usage of /:   3.0% of 39.34GB   Users logged in:     1
  Memory usage: 5%                IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 172.16.0.16

  Graph this data and manage this system at:
    https://landscape.canonical.com/


net.ipv4.tcp_max_syn_backlog = 65535
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
kernel.shmmax = 2147483648
kernel.shmall = 2097152
================================================================================
  Running Tests...
================================================================================

verify:   0% |                                                                                                                         | Rough ETA:  --:--:----------------------------------------------------------------------------------
  Running Test: nancy
--------------------------------------------------------------------------------

verify: 100% |#########################################################################################################################| Rough Time: 00:00:00

================================================================================
  Verification Summary

| Test: nancy
|      NO RESULTS (Did framework launch?)
================================================================================

Time to complete: 2 seconds
Results are saved in results/ec2/20150423112941
```

### CODE REVIEW

**Comment by hamiltont** [comment]
Thanks! A few things: 

 * You'll want to use `nancy-mono` instead of `nancy` - the latter requires a windows OS, and you appear to be using our vagrant setup. Try this instead `python toolset/run-tests.py --install server --mode verify --test nancy-mono`. You can also use `python toolset/run-tests.py --install server --mode verify --test nancy-mono nancy-libevent2` as the libevent2 config appears to use a linux OS
 * You've added binary files to `frameworks/CSharp/nancy/lib/*`. This won't work for us - our repository is already quite large as is. Can these libraries be downloaded from somewhere like nuget? Check out how [aspnet](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnet) does this for a reference

> I have no idea if these changes work

Hopefully the above let's you run your changes using our vagrant setup. Just FYI though, you can rely on travis-ci to check the PR for you. E.g. your last push ran on travis-ci and shows that nancy-mono has some PASS and some FAIL, while nancy-libevent2 is currently all FAIL.

**Comment by hamiltont** [comment]
Thanks for dropping the binaries! Looks like the current issues are all simple path issues. Here's what you can do - for all lines like `sed -i 's|localhost|'"${DBHOST}"'|g' src/Web.config`, use the `TROOT` variable that we set for you. E.g. `sed -i 's|localhost|'"${DBHOST}"'|g' $TROOT/src/Web.config`. Use that for the `rm`, `xbuild`, and any other commands

Also, you can completely remove the `setup_*.py` files, we have totally switched to `setup*.sh` files so the python ones are just historical junk at this point

**Comment by msmith-techempower** [comment]
Looks like the build process failed.

**Comment by khellang** [comment]
Yeah, I'll give this another shot next week :smile:

**Comment by msmith-techempower** [comment]
@ssmith-techempower This is an old one, but try pulling it into a new branch off our latest master and seeing what you find.

**Comment by khellang** [comment]
I can probably redo this PR if it makes things easier. It seems like these particular benchmarks are a bit of a mess right now...

**Comment by msmith-techempower** [comment]
@khellang That would be very helpful - I believe the latest master has Travis-CI issues resolved, so it should be as simple as rebasing and HOPEFULLY it just works.

**Comment by khellang** [comment]
:+1: I'll leave this open as a reminder until I can get around to it :smile:

**Comment by blee-techempower** [comment]
@khellang I modified CSharp related environment setting files: mono.sh, xsp.sh and etc. As a result, everything work correctly, but nancy-mono-libevent2. I am pretty sure there is some issues with it, but I have not figure it out. For this reason, I excluded nancy-mono-libevent2 from benchmark_config.json file in nancy project.  

https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/98843631

If you like to continue your work, you can start from this branch: "blee-temp-nancy"
At least you will not have environment issue.

**Comment by msmith-techempower** [comment]
@khellang We just merged in a fix to get Mono working, and it seems like you should be able to rebase off the latest master to get this working.

No pressure, but yours in the last open pull request :-)

**Comment by khellang** [comment]
I'll get to this another time. I'll probably have to start over anyway :smile:

**Pull request closed without merging**
