### PR TITLE
Change max children processes

### PR DESCRIPTION
**Pull request by joanhey**
There are almost no differences in req/s and the latency is greater.
So we revert the change to 1024 again.
Perhaps we will try with less children later.

And also introduced errors when using postgresql.

### CODE REVIEW

**Comment by joanhey** [comment]
Hi, again
I was really busy the last 6 months, but I will continue optimizing the php stack.

**Comment by joanhey** [comment]
The job exceeded the maximum time limit for jobs, and has been terminated.

Possibly it will be necessary to separate the php fws in 2 jobs.

**Comment by nbrady-techempower** [comment]
Welcome back @joanhey! If you'd like to take a crack at separating PHP out into two or three jobs in the `.travis.yml` in this PR that'd be great! Keeping in mind, it'd be good to keep closely related frameworks together to utilize the docker cache in each job. Otherwise I can probably get to it by Tuesday.

**Comment by joanhey** [comment]
Separated PHP frameworks in two jobs for travis.

@vasily-kartashov Could you check hamlet-amp and hamlet-roadrunner?

**Comment by vasily-kartashov** [comment]
@joanhey both will be removed very soon. Will submit a PR in a couple of days

**Comment by joanhey** [comment]
@javiereguiluz Could anybody check the symfony test fail ?
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/461202934#L5350

Thank you

**Comment by ostrolucky** [comment]
symfony test works for me locally. try restarting the job

**Comment by joanhey** [comment]
It's working for me too locally.
For that I send an small commit `Changed php fortune with <?=` for rerun the job and failed again.

Like I will add another job only for the php (for add more servers with php raw), we will check if happen again.

**Comment by joanhey** [comment]
The funny thing is that symfony also fails in the continuous bechmark.
Exactly with the update test too.
https://tfb-status.techempower.com/results/663adbe9-d01e-47d6-aedd-26b7415800f5

**Comment by joanhey** [comment]
Hamlet-amp and hamlet-roadrunner also fail without this PR.

Deleted changes in zen1 and kohana to avoid merge conflicts.

This PR is ready to be merged.

**Pull request merged**
