### PR TITLE
Update ringojs and ringojs-convenient

### PR DESCRIPTION
**Pull request by grob**
* updated dependencies
* re-added tests in benchmark config of ringojs
* fixed an issue with fortunes test in ringojs-convenient
* removed explicit transaction usage in updates test of ringojs-convenient (ringo-sqlstore uses transactions by default)
* update to mysql-connector-java-5.1.39.jar

### CODE REVIEW

**Comment by msmith-techempower** [comment]
All tests pass in Travis-CI.

**Comment by nbrady-techempower** [comment]
Hi @grob we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by grob** [comment]
Oh, i thought this would be merged for round 13? I'm currently on vacation and won't be able to do the change within the next weeks, but maybe @oberhamsi could do it?

**Comment by nbrady-techempower** [comment]
@grob unfortunately no, we've had round-13 frozen for quite some time. We added the Post Rnd 13 milestone to this when you first made the PR. The way we are setting up things now, this won't be a problem in the future. PR's for upcoming rounds will be tested and merged into the proper branch as soon as they are tested :) If you or @oberhamsi can't do that, I can certainly pull this and target it to round-14 for you and tag this as a reference. Whatever you'd like to do in that regard is fine. Thanks for your support!

**Comment by nbrady-techempower** [comment]
Took care of that for you guys #2105

**Comment by oberhamsi** [comment]
@nbrady-techempower thanks a bunch!

**Pull request closed without merging**
