### PR TITLE
Improve the axum entry

### PR DESCRIPTION
**Pull request by jplatte**
Mainly: Upgrade dependencies, use state instead of extensions.

### CODE REVIEW

**Comment by jplatte** [comment]
No idea what's broken in CI, seems to be about Docker which I didn't modify.

**Comment by joanhey** [comment]
Yes, the toolset is failing. Check #8013

**Comment by volyrique** [comment]
@jplatte You can also rebase on top of 110b441205b2b62bb6eeb5ebcbc37ac6c95db09a.

**Comment by jplatte** [comment]
@volyrique That commit is already part of the history on my branch.

**Comment by volyrique** [comment]
The point is that that commit should be the last commit before your changes - right now your PR is on top of a broken commit.

**Comment by jplatte** [comment]
Okay. Just doing `git rebase 110b441` would be a no-op, so I was a bit confused what you meant.

**Comment by jplatte** [comment]
I suspect it will still fail though. The `checkout` action by default checks out a merge commit, not the PR head for running tests.

**Pull request merged**
