### PR TITLE
added JLHTTP benchmark

### PR DESCRIPTION
**Pull request by amichair**
Can you please add JLHTTP to the benchmarks?

### CODE REVIEW

**Comment by msmith-techempower** [comment]
You must add JLHTTP to the `.travis.yml` file for Travis-CI to be tested.

**Comment by amichair** [comment]
Ok, I added a line for it.

btw I didn't see Travis mentioned in [the docs](https://frameworkbenchmarks.readthedocs.io/en/latest/Development/Add-Frameworks-or-Tests/), you should update the instructions (unless I missed it).

**Comment by LadyMozzarella** [comment]
@amichair I submitted a pull request against the docs to help clarify this `.travis.yml` requirement. Thank you for bringing it to our attention. See TechEmpower/TFB-Documentation#40.

**Comment by nbrady-techempower** [comment]
Hi @amichair we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by amichair** [comment]
To be continued in PR #2062.

**Pull request closed without merging**
