### PR TITLE
Include Comsat webactors framework

### PR DESCRIPTION
**Pull request by circlespainter**
Could you also help me with some questions https://groups.google.com/forum/#!topic/framework-benchmarks/Gujdipuua7Q?

### CODE REVIEW

**Comment by circlespainter** [comment]
It actually runs fine in my Vagrant env (tried with the latest `ubuntu/trusty64` box but also previously) but it fails on CI; it looks like the `java8` dependency can't be setup for some reason:

```
'ERROR: /toolset/setup/linux/languages/java8.sh: Command '\''sudo update-alternatives --set java $J7_HOME/jre/bin/java'\'' exited with status 2 (dependency=java8) (cwd=$FWROOT/installs)'
Setup comsat-webactors-servlet-tomcat: ERROR: /toolset/setup/linux/languages/java8.sh: Command 'sudo update-alternatives --set java $J7_HOME/jre/bin/java' exited with status 2 (dependency=java8) (cwd=$FWROOT/installs)
```

Do you see anything in the framework's build source that could cause this (apart from the dependency to java8 - which is there only because it's more performant, although the framework support java7 too)?

**Comment by blee-techempower** [comment]
Localtest failed. ( http:////sprunge.us/IOWX ) 
Please resolve the issue.

**Comment by circlespainter** [comment]
I have merged upstream's master and re-run successfully the following tests in the `vagrant-development` environment:

``` bash
cd FrameworkBenchmarks
toolset/run-tests.py --mode verify --test comsat-webactors
toolset/run-tests.py --mode verify --test comsat-webactors-netty
toolset/run-tests.py --mode verify --test comsat-webactors-servlet-undertow
toolset/run-tests.py --mode verify --test comsat-webactors-servlet-jetty
toolset/run-tests.py --mode verify --test comsat-webactors-servlet-tomcat
```

**Comment by circlespainter** [comment]
@blee-techempower Re-merged the most recent master and it still runs OK in `vagrant-development` but I still have a failure on CI (where, according to the message at the end of their build, other frameworks run fine because they haven't changed). The error says `Usernames (e.g. --client-user, --runner-user, and --database-user) are required!` and I could see that the `run-ci.py` script is indeed aborting if they're not defined (through `benchmark.cfg` or env variables if I understand correctly).

I tried to run them just as Travis would on my physical Mint box: I copied over  and with the `benchmark.cfg` file in place (project root dir, I also replaced usernames with my own) they seem to succeed without problems. Not really sure if I should commit&push though, or with which settings exactly.

What am i missing in order to have Travis CI run OK too? Thanks.

**Comment by msmith-techempower** [comment]
@circlespainter We have recently fixed a lot of issues on Travis; please rebase from our latest master and push to have Travis-CI retest.

**Comment by circlespainter** [comment]
Rebased and squashed, now it builds ok. Thanks

**Comment by msmith-techempower** [comment]
Awesome! Both Travis-CI tests passed; LGTM!

**Pull request merged**
