### PR TITLE
Fix http headers spring

### PR DESCRIPTION
**Pull request by dreis2211**
Hey,

when working on a different merge request I noticed that the Spring suite doesn't include the **Server** header and sends the encoding along with the **Content-Type** header. Both result in a warning in the builds for all requests.

WARN for http://127.0.0.1:8080/json
`Required response header missing: Server`

WARN for http://127.0.0.1:8080/json
`Content encoding found in "application/json;charset=UTF-8" where "application/json" is acceptable.`

I needed to upgrade to Spring-Boot 1.3.3 to set the server header in Undertow via `server.server-header`.

Cheers,
Christoph

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @dreis2211 we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by dreis2211** [comment]
Hi @nbrady-techempower,

well - it is basically a bugfix, so according to the documentation this should go into master!? But I will branch of the newly created round branches, if needed.

Cheers

**Comment by nbrady-techempower** [comment]
Hi @dreis2211, yes from here on that will be correct. We're in kind of a weird state since we're setting this new branch system up for the first time. @msmith-techempower added the Post Round 13 milestone to this so we're probably better off moving it there. Once you do that, tomorrow I'll test it against our local environments and get it merged in to the Round 14 branch. We're doing this in an effort to better streamline making these changes and so we don't have to leave PR's open during the time between freezing a round and running the final benchmark tests.

**Comment by dreis2211** [comment]
Closed in favor of #2071

**Pull request closed without merging**
