### PR TITLE
Update aspnet core benchmarks

### PR DESCRIPTION
**Pull request by sebastienros**
Minimal APIs implementation added, using Dapper only.
MVC updated, using Entity Framework only.
Platform updated, using ADO.NET only.
Middleware implementation is being removed.

Kept for future PRs for simplicity:
- AOT
- Cached Worlds in MVC and Minimal APIs

### CODE REVIEW

**Comment by sebastienros** [comment]
@DamianEdwards @roji @davidfowl

**Comment by joanhey** [comment]
As your removing tests, perhaps it'll be good to remove also the aspnetcore with only plaintext and json.

image

Per #8420 "No longer accepting plaintext only frameworks / Limited number of tests mutations"

**Comment by sebastienros** [comment]
@joanhey maybe I made a mistake in the config files, but the other scenarios are implemented for it, in a distinct docker file. Will check why it doesn't run.

**Comment by sebastienros** [comment]
@joanhey it's run with the aspnetcore-pg name

image

Did I miss something to group them, or is this only a behavior from the tests?

**Comment by joanhey** [comment]
Also while don't maintain almost one mysql permutation?
So the future users will know the difference about using Mysql vs Postgresql.

**Comment by joanhey** [comment]
Why use the time to create 2 docker images to run the same benchmark.
Exist a issue about that, if we create a bench for every endpoint, we can have better numbers thanks to the JIT.
We need to clarify this situation, that help the synthetic bench but it isn't realistic in a normal app.

image

**Comment by joanhey** [comment]
Some time ago, I separated the name of aspnetcore to identify it in the composite score.
Because before exist only one, and that it wasn't realistic to identify that mvc is not as fast as the hard coded platform.
To help the users choose the right permutation.

image

I think that still need to be separated this classification.

**Comment by sebastienros** [comment]
@joanhey Thanks for the feedback.

I have grouped the the default runs in the same docker file, and added MySQL as a separate one, with only the database benchmarks.

> I think that still need to be separated this classification

I am not sure if you are asking me to change anything in the config files. Right now the "default" profile should be used for this and it contains all the scenarios. I just know that how it looks like today on the public tables is great, thanks for whatever you did here.

**Comment by joanhey** [comment]
I only changed the framework name. And this PR now have it OK.
image

**Comment by sebastienros** [comment]
@joanhey I am ready to get it mergeg then if you are ok with it

**Review by joanhey — APPROVED** [review]

**Pull request merged**
