### PR TITLE
new finch version

### PR DESCRIPTION
**Pull request by whiplash**

### CODE REVIEW

**Comment by blee-techempower** [comment]
Has error. Please resolve the error.

**Comment by whiplash** [comment]
It should be ok now

**Comment by blee-techempower** [comment]
Localtest failed again. ( http://sprunge.us/eAcS )
Please resolve this issue.

**Comment by whiplash** [comment]
Fixed mistake specifying `localhost`

**Comment by blee-techempower** [comment]
Passed localtest.
```
================================================================================
  Verification Summary

| Test: finch
|       plaintext   : WARN
|       json        : WARN
================================================================================
```

**Pull request merged**
