### PR TITLE
Php swoole less verbose make

### PR DESCRIPTION
**Pull request by joanhey**
And fix plaintext header in phpixie

### CODE REVIEW

**Comment by joanhey** [comment]
The test passed in my fork:
https://travis-ci.org/joanhey/FrameworkBenchmarks/builds/370668427

Ping @nbrady-techempower 
One question.
The nginx.conf use the `root` user.
Is it for anything in particular ?

I tried in local with `www-data` user, a more secure and production ready, without problems.
Because I will optimize and clean the nginx.conf and I will add this change too.

**Comment by joanhey** [comment]
OK
Tomorrow I will try the changes in the nginx.conf.
The php-fpm use by default `www-data` user 
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/PHP/php/deploy/conf/php-fpm.conf#L151

**Comment by joanhey** [comment]
Now I go to drink some :beers: in front of the beach.

**Comment by msmith-techempower** [comment]
I like this guy.

**Comment by msmith-techempower** [comment]
@joanhey Is this ready to merge and you will open a new pull request at a later time, or do you want to leave this open and continue it as a work-in-progress?

**Pull request merged**
