### PR TITLE
ASP.NET Core Platform Sync

### PR DESCRIPTION
**Pull request by benaadams**
The two repositories had become desynchronized

Corresponding ASP.NET Core sync https://github.com/aspnet/Benchmarks/pull/1472

/cc @adamsitnik @sebastienros @halter73

### CODE REVIEW

**Comment by sebastienros** [comment]
It failed for me on the aspnet repos as the MySql assembly is used in `RawDb.cs` but the conditional directive is not used.

Also IMO kind of risky to change at that point since it will only improve plaintext which is already saturated on network on TE machines.

**Comment by benaadams** [comment]
> It failed for me on the aspnet repos as the MySql assembly is used in RawDb.cs but the conditional directive is not used.

They aren't conditionally included here; aspnet repo has a more complex reference include policy that I may have not got right. All tests pass for TE including the MySql ones.

> it will only improve plaintext 

Also will effect JSON from one of the earlier changes https://github.com/aspnet/Benchmarks/pull/1464

> which is already saturated on network on TE machines.

YMMV

image

**Comment by sebastienros** [comment]
Off topic: pico.v results is a mistery. Ulib can reach 15M on our machines with two clients. Maybe there is something in the payload that differs, like less headers, smaller url (`/p`, `/j`) and at this rate it matters.

**Comment by sebastienros** [comment]
OK for the IsDatabase, that's what i ended up doing in aspnet.

**Comment by sebastienros** [comment]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/V/pico.v/benchmark_config.json#L6-L7

Header sizes might also explain the order of the first 10 results.

**Pull request merged**
