### PR TITLE
Uvicorn remaining test types

### PR DESCRIPTION
**Pull request by tomchristie**
Adds single queries, multiple queries, and updates.

Thanks to @maximilianhurl 😎

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Thanks for adding these test types! Would love to see more caching tests if you are able to implement that as well!

**Comment by tomchristie** [comment]
Not sure what you mean wrt caching tests? Is that a different test type that we've missed, or something else?

**Comment by tomchristie** [comment]
Ah gotcha I see that now. Yup I'll take a crack, tho will prob treat it as a seperate pull request. 👍

**Comment by tomchristie** [comment]
@nbrady-techempower Having taken a look at the caching test I'm going to punt on that. We could use in-memory caching for the test, but it's not something that'd reflect production usage given that you'd typically want the ability to scale past a single process on a single instance, and at least two instances for redundancy. I'd be more than happy to implement a caching test type if distributed caching ends up getting added at a later point. Welcome to take any further discussion on this off of this thread and onto the discussion group if that's helpful! 😄

**Comment by nbrady-techempower** [comment]
@tomchristie No worries, that all makes sense! Thanks again for the contributions! :)

**Pull request merged**
