### PR TITLE
Rails tweaks

### PR DESCRIPTION
**Pull request by spizm**
Cleaning up the rails build a little more:

- update to latest gems
- add gitignore to rails subdirectory
- simplify some of the benchmark code
- set up a redis server to share cache between processes

I also added a gitignore to the toolset directory to avoid ignore .pyc files

### CODE REVIEW

**Comment by spizm** [comment]
It looks like all the broken checks are unrelated to this PR

**Comment by nbrady-techempower** [comment]
Thanks @spizm ! I'll try and take a look in the next couple of days. Can you remove the .gitignore file here? Shouldn't be necessary since those would be within docker.

**Comment by spizm** [comment]
@nbrady-techempower I removed the gitignore in the rails dir. The one in the toolset is outside of docker and git keeps noticing *.pyc files whenever I run the suite, so that one should still be present.

**Comment by nbrady-techempower** [comment]
@spizm The toolset is also run inside a docker container, so that shouldn't be happening. How are you running things?

**Comment by spizm** [comment]
@nbrady-techempower I'm just running the `tfb` tool (`./tfb --mode verify --test rails`) from the root of the repo. It immediately generates pyc files.

**Comment by nbrady-techempower** [comment]
Are you sure you’re running a recent version of the toolset? What pyc files are being generated? Python isn’t being run on the host.

**Comment by spizm** [comment]
I'm running off the latest master build from an M1 Mac with Docker installed. The `tfb` tool runs inside a docker container, but it [mounts the whole project](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/tfb#L106) into a directory on the container, so I suspect that's where the files are coming from. 

These files show up whenever I run the `tfb` tool:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	toolset/__init__.pyc
	toolset/benchmark/__init__.pyc
	toolset/benchmark/benchmarker.pyc
	toolset/benchmark/framework_test.pyc
	toolset/databases/__init__.pyc
	toolset/databases/abstract_database.pyc
	toolset/databases/mongodb/mongodb.pyc
	toolset/databases/mysql/mysql.pyc
	toolset/databases/postgres/postgres.pyc
	toolset/test_types/__init__.pyc
	toolset/test_types/abstract_test_type.pyc
	toolset/test_types/cached-query/cached-query.pyc
	toolset/test_types/db/db.pyc
	toolset/test_types/fortune/__init__.pyc
	toolset/test_types/fortune/fortune.pyc
	toolset/test_types/fortune/fortune_html_parser.pyc
	toolset/test_types/json/json.pyc
	toolset/test_types/plaintext/plaintext.pyc
	toolset/test_types/query/query.pyc
	toolset/test_types/update/update.pyc
	toolset/test_types/verifications.pyc
	toolset/utils/__init__.pyc
	toolset/utils/audit.pyc
	toolset/utils/benchmark_config.pyc
	toolset/utils/cleaner.pyc
	toolset/utils/docker_helper.pyc
	toolset/utils/metadata.pyc
	toolset/utils/output_helper.pyc
	toolset/utils/popen.pyc
	toolset/utils/results.pyc
	toolset/utils/scaffolding.pyc
	toolset/utils/time_logger.pyc
```

I'm happy to remove the gitignore if it seems like something specific to my environment.

**Comment by nbrady-techempower** [comment]
Yeah, I haven't seen this happen on ubuntu or windows. I'll check it out on a mac later today.

**Comment by nbrady-techempower** [comment]
I haven't been able to confirm this, but I'll just get this in so you can see it running. We'll be updating to the rust toolset soon so this won't be a problem after that.

**Pull request merged**
