### PR TITLE
Rename API-Hour folder to AsyncIO and prepare the arrival of new AsyncIO/API-Hour daemons

### PR DESCRIPTION
**Pull request by GMLudo**
Hi guys,

I've prepared some new AsyncIO/API-Hour daemons for the next round, I will push that as pull requests in FrameworkBenchmarks this week-end.

However, before to launch my gatling, I wish to know your opinion about folder organization: To avoid to pollute too much the first level of `frameworks/Python` with my daemons around AsyncIO, I thought to have a generic `AsyncIO` folder, where I can push my experimentations, one folder by architecture, like you did for `historical` folder.

Are you agree with that ?
If yes, it means I'll also split `aiohttp.web` folder in several folders, because for now, it's an all-in-one application with several architectures.

Regards.

### CODE REVIEW

**Comment by GMLudo** [comment]
Hi,

Finally, I've pushed new tests in the same branch.
I don't have the time right now to implement all of my ideas, it will wait the next round.

Thanks for the merge.

Regards.

**Comment by msmith-techempower** [comment]
Looks like the `fortunes` formatting is off from our requirements: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/64829948

Otherwise, would love to merge. Hopefully, you can get this updated soon.

**Comment by GMLudo** [comment]
Ok, I've missed that.

I'm under the fire of the production, no time to fix that right now, I've disabled this test, it should pass.
I'll fix that ASAP, but at least, you should already merge this PR.

Regards.

**Comment by msmith-techempower** [comment]
Looks good; LGTM!

**Pull request merged**
