### PR TITLE
updates to latest Luminus

### PR DESCRIPTION
**Pull request by yogthos**

### CODE REVIEW

**Comment by k-r-g** [comment]
It looks like benchmark_config.json needs the "port" value to be changed from 8080 to 3000. However, even after I make that change the database tests don't work for me.

From the verify script, I get:

Accessing URL http://127.0.0.1:3000/queries/2:
Server luminus: [2016-01-15 17:43:03,902][ERROR][hello.middleware] #error {
Server luminus:  :cause No database selected
Server luminus:  :via
Server luminus:  [{:type java.sql.SQLException
Server luminus:    :message No database selected
Server luminus:    :at [com.mysql.jdbc.SQLError createSQLException SQLError.java 996]}]
Server luminus:  :trace
Server luminus:  [[com.mysql.jdbc.SQLError createSQLException SQLError.java 996]
Server luminus:   [com.mysql.jdbc.MysqlIO checkErrorPacket MysqlIO.java 3887]
Server luminus:   [com.mysql.jdbc.MysqlIO checkErrorPacket MysqlIO.java 3823]
Server luminus:   [com.mysql.jdbc.MysqlIO sendCommand MysqlIO.java 2435]
Server luminus:   [com.mysql.jdbc.MysqlIO sqlQueryDirect MysqlIO.java 2582]
...

**Comment by yogthos** [comment]
ah ok, I put in a full jdbc url, but it looks like it actually gets rewritten in `setup.sh`:

```
sed -i 's|:subname "//.*:3306|:subname "//'"${DBHOST}"':3306|g' hello/src/hello/db/core.clj
```

I've updated the URL to match that and put the port 3000 in, so hopefully that should be it.

**Comment by yogthos** [comment]
I switched to using postgres, and cleaned up the connections settings. Looks like the build passes for Luminus now.

**Comment by msmith-techempower** [comment]
Looks good minus a few repeatability bugs, but I'll clean those up and manually merge; LGTM!

**Comment by yogthos** [comment]
Fantastic, looking forward to seeing the performance in the next round. :)

**Pull request merged**
