### PR TITLE
fix host to 0.0.0.0 and tests for plaintext, json, db, update, query and fortune 

### PR DESCRIPTION
**Pull request by nathantippy**

### CODE REVIEW

**Comment by nathantippy** [comment]
Unable to get travis-ci to pass all checks.  This GreenLightning test works well however other tests are failing causing an issue.   Is the CI process stable?

**Comment by nbrady-techempower** [comment]
@nathantippy Yes, those other failures are being reported correctly. Some frameworks need to be updated. We have a script that checks which tests need to be run based on the git log history in your pull request. You can add `[ci fw-only Java/greenlightning]` to your commit messages and travis will skip the other tests, giving you that green check mark. Will review this PR shortly. Thanks for the updates!

**Comment by nathantippy** [comment]
great to know, thanks.

**Comment by nathantippy** [comment]
OK, I now have all the tests (plaintext, json, db, update, query and fortune) working local and on travis. I do not plan to make any more changes unless I get some feedback needing attention.

**Comment by nbrady-techempower** [comment]
@nathantippy i updated your readme to check off the other two tests. merging now, thanks!

**Pull request merged**
