### PR TITLE
Upgrade Crystal and Kemal

### PR DESCRIPTION
**Pull request by sdogruyol**
This pull request updates

- Crystal to 0.18.7
- Kemal to 0.14.0

and other shards.

### CODE REVIEW

**Comment by knewmanTE** [comment]
Thanks for the pull request @sdogruyol, and sorry for the delayed response! A couple things:

1) it looks like both the `Crystal/crystal-raw` test and the `Crystal/kemal` tests are failing on Travis. Could you take a look at the output logs to see what might be causing them to break?

2) We've also made a bunch of fixes on the master branch that fix some bugs we were having on Travis, so it might be worth merging those changes into your branch and seeing if that helps at all.

**Comment by nbrady-techempower** [comment]
hey @sdogruyol was wondering if you could rebase this so we can give it another run against travis.

**Comment by sdogruyol** [comment]
@nbrady-techempower i just rebased this

**Comment by knewmanTE** [comment]
looks good to me!

**Comment by sdogruyol** [comment]
Thanks 👍

**Comment by sdogruyol** [comment]
BTW @knewmanTE what's the expected date for Round 13?

**Comment by knewmanTE** [comment]
@sdogruyol we've been tied up lately with other projects at TechEmpower, but round 13 should be soon! We've got preview data for our high-performance environment that we're hoping to post soon, and then the round 13 final results for both environments should follow shortly after.

**Comment by sdogruyol** [comment]
@knewmanTE just to be sure. Is this gonna be in Round 13?

**Comment by knewmanTE** [comment]
@sdogruyol yes! It might not end up in our second preview round (depends on whether we do a new run before posting the results), but it will be in the round 13 final run!

**Comment by sdogruyol** [comment]
@knewmanTE that's great to hear 😃  Can't wait for Round 13. Keep up the good work 👍

**Comment by knewmanTE** [comment]
@sdogruyol likewise! And we've also got some really cool continuous benchmarking tools in the works that should allow for some interim results to be published much more frequently!

**Pull request merged**
