### PR TITLE
Add ntex-raw fortunes with yarte 

### PR DESCRIPTION
**Pull request by botika**
Add first approach for this implementation.

Merge after https://github.com/TechEmpower/FrameworkBenchmarks/pull/6233 and wait for force push
Require approved by @fafhrd91 
```json
 "ntex-db": [
        {
          "latencyAvg": "346.56us", 
          "latencyMax": "9.24ms", 
          "latencyStdev": "233.77us", 
          "totalRequests": 708598, 
          "startTime": 1609084906, 
          "endTime": 1609084921
        }, 
        {
          "latencyAvg": "610.04us", 
          "latencyMax": "9.60ms", 
          "latencyStdev": "388.27us", 
          "totalRequests": 814948, 
          "startTime": 1609084923, 
          "endTime": 1609084938
        }, 
        {
          "latencyAvg": "1.10ms", 
          "latencyMax": "11.79ms", 
          "latencyStdev": "791.21us", 
          "totalRequests": 921622, 
          "startTime": 1609084940, 
          "endTime": 1609084955
        }, 
        {
          "latencyAvg": "2.11ms", 
          "latencyMax": "22.13ms", 
          "latencyStdev": "1.80ms", 
          "totalRequests": 1012448, 
          "startTime": 1609084957, 
          "endTime": 1609084972
        }, 
        {
          "latencyAvg": "3.77ms", 
          "latencyMax": "32.48ms", 
          "latencyStdev": "2.85ms", 
          "totalRequests": 1080537, 
          "startTime": 1609084974, 
          "endTime": 1609084989
        }, 
        {
          "latencyAvg": "6.82ms", 
          "latencyMax": "40.66ms", 
          "latencyStdev": "4.13ms", 
          "totalRequests": 1130800, 
          "startTime": 1609084991, 
          "endTime": 1609085006
        }
      ]
```
```json
"ntex-yarte": [
        {
          "latencyAvg": "330.48us", 
          "latencyMax": "8.36ms", 
          "latencyStdev": "214.57us", 
          "totalRequests": 742358, 
          "startTime": 1609084402, 
          "endTime": 1609084417
        }, 
        {
          "latencyAvg": "572.86us", 
          "latencyMax": "20.95ms", 
          "latencyStdev": "472.97us", 
          "totalRequests": 878676, 
          "startTime": 1609084419, 
          "endTime": 1609084434
        }, 
        {
          "latencyAvg": "1.04ms", 
          "latencyMax": "14.92ms", 
          "latencyStdev": "821.18us", 
          "totalRequests": 993301, 
          "startTime": 1609084436, 
          "endTime": 1609084451
        }, 
        {
          "latencyAvg": "1.98ms", 
          "latencyMax": "22.83ms", 
          "latencyStdev": "1.70ms", 
          "totalRequests": 1079126, 
          "startTime": 1609084453, 
          "endTime": 1609084468
        }, 
        {
          "latencyAvg": "3.49ms", 
          "latencyMax": "28.69ms", 
          "latencyStdev": "2.48ms", 
          "totalRequests": 1148039, 
          "startTime": 1609084470, 
          "endTime": 1609084485
        }, 
        {
          "latencyAvg": "6.38ms", 
          "latencyMax": "34.59ms", 
          "latencyStdev": "3.80ms", 
          "totalRequests": 1207645, 
          "startTime": 1609084487, 
          "endTime": 1609084502
        }
      ]
```

### CODE REVIEW

**Comment by fafhrd91** [comment]
i dont want to have separate bench for each template. i am fine to have yarte as default template and remove everything else.

**Comment by botika** [comment]
@fafhrd91  I did not understand. What I do? I close the PR? Do I delete fortunes from `ntex-db` and leave only this one? Change name of bench? Anything else?

**Comment by fafhrd91** [comment]
lets just keep ntex-db without specialized -yarte bench

**Comment by botika** [comment]
Ok, so if I understood correctly, I close this PR

**Pull request closed without merging**
