### PR TITLE
Cutelyst no sudo

### PR DESCRIPTION
**Pull request by dantti**
This should allow for Cutelyst make install to work without `sudo`

### CODE REVIEW

**Comment by michaelhixson** [comment]
Thanks for looking into this.

The `cutelyst-nginx-mysql-raw` and `cutelyst-nginx-postgres-raw` tests appear to fail with this change.  I see errors like this when the tests are running:

```
Server cutelyst-nginx-mysql-raw: default[warning] QSqlQuery::prepare: database not open
Server cutelyst-nginx-mysql-raw: cutelyst.utils.sql[critical] Failed to prepare query: "SELECT id, message FROM fortune" "Driver not loaded"
```

```
Server cutelyst-nginx-postgres-raw: default[warning] QSqlQuery::prepare: database not open
Server cutelyst-nginx-postgres-raw: cutelyst.utils.sql[critical] Failed to prepare query: "SELECT id, message FROM fortune" "Driver not loaded"
```

The `cutelyst-thread-mysql-raw` and `cutelyst-thread-postgres-raw` tests still pass though.

Also, we would still like to keep cutelyst's installed files as isolated as possible.  Putting the files in IROOT/cutelyst was a desirable change by itself, separate from the sudo issue.  We don't want frameworks to create files or directories like IROOT/bin, IROOT/lib, IROOT/include, IROOT/config.ini, IROOT/nginx.conf, for example.  (It's not important that the directory is named exactly IROOT/cutelyst or that there's a variable in the code named CROOT.)

**Comment by dantti** [comment]
Ok, I'll remove the revert then and investigade why did it failed..

**Comment by dantti** [comment]
I could not reproduce the issue on vagrant, let's see if it works now that I didn't reverted your changes on Travis

**Comment by dantti** [comment]
great it passed... :stuck_out_tongue:

**Comment by michaelhixson** [comment]
It passes on our in-house TFB machines now too.  Thanks!

**Pull request merged**
