### PR TITLE
Upgrade Play Framework projects to Play 2.8

### PR DESCRIPTION
**Pull request by mkurz**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@mkurz a couple of fortune errors and an updates error coming from this. Would you mind taking a look when you have a chance?

**Comment by mkurz** [comment]
@nbrady-techempower Yes I will update the pull request when I find time.

**Comment by nbrady-techempower** [comment]
Im going to merge this because the play2 scala fortunes are failing off and on in master anyway and this is a net positive PR for Round 19. Just a reminder that there are some errors that could be looked at.

**Comment by mkurz** [comment]
I will have a look asap.

**Pull request merged**
