### PR TITLE
[Go]Add Hertz framework

### PR DESCRIPTION
**Pull request by FlameMida**
I verified it on my machine using
```bash
./tfb --mode verify --test hertz
./tfb --mode verify --test hertz-gorm
```
all passed

### CODE REVIEW

**Comment by FlameMida** [comment]
@nbrady-techempower Would you please help me re-run the CI？

**Comment by FlameMida** [comment]
@nbrady-techempower Ubuntu-18.04 causes CI failure what should i do?

**Comment by rogerogers** [comment]
Is there any progress on this?

**Comment by FlameMida** [comment]
> Is there any progress on this?
Already done

**Pull request merged**
