### PR TITLE
Improve performance at ntex fortunes

### PR DESCRIPTION
**Pull request by botika**
@fafhrd91 Gain ~5% performance in my i7-7700HQ @ 2.8GHz
### Old result:
```json
{
          "latencyAvg": "353.39us", 
          "latencyMax": "9.02ms", 
          "latencyStdev": "214.34us", 
          "totalRequests": 688911, 
          "startTime": 1592709348, 
          "endTime": 1592709363
}, 
{
          "latencyAvg": "627.53us", 
          "latencyMax": "15.28ms", 
          "latencyStdev": "398.60us", 
          "totalRequests": 786430, 
          "startTime": 1592709365, 
          "endTime": 1592709380
}, 
{
          "latencyAvg": "1.12ms", 
          "latencyMax": "26.11ms", 
          "latencyStdev": "815.75us", 
          "totalRequests": 896048, 
          "startTime": 1592709382, 
          "endTime": 1592709397
}, 
{
          "latencyAvg": "2.13ms", 
          "latencyMax": "20.07ms", 
          "latencyStdev": "1.73ms", 
          "totalRequests": 983991, 
          "startTime": 1592709399, 
          "endTime": 1592709415
}, 
{
          "latencyAvg": "3.83ms", 
          "latencyMax": "29.24ms", 
          "latencyStdev": "2.84ms", 
          "totalRequests": 1057442, 
          "startTime": 1592709417, 
          "endTime": 1592709432
},
{
          "latencyAvg": "6.94ms", 
          "latencyMax": "47.57ms", 
          "latencyStdev": "4.11ms", 
          "totalRequests": 1106248, 
          "startTime": 1592709434, 
          "endTime": 1592709449
}
```

### New results
```json
 {
          "latencyAvg": "336.84us", 
          "latencyMax": "8.60ms", 
          "latencyStdev": "198.18us", 
          "totalRequests": 721340, 
          "startTime": 1592718009, 
          "endTime": 1592718024
}, 
{
          "latencyAvg": "592.72us", 
          "latencyMax": "9.30ms", 
          "latencyStdev": "352.86us", 
          "totalRequests": 827659, 
          "startTime": 1592718026, 
          "endTime": 1592718041
}, 
{
          "latencyAvg": "1.06ms", 
          "latencyMax": "12.49ms", 
          "latencyStdev": "708.47us", 
          "totalRequests": 940365, 
          "startTime": 1592718043, 
          "endTime": 1592718058
}, 
{
          "latencyAvg": "2.04ms", 
          "latencyMax": "22.55ms", 
          "latencyStdev": "1.67ms", 
          "totalRequests": 1031379, 
          "startTime": 1592718060, 
          "endTime": 1592718075
}, 
{
          "latencyAvg": "3.70ms", 
          "latencyMax": "29.77ms", 
          "latencyStdev": "2.78ms", 
          "totalRequests": 1097643, 
          "startTime": 1592718077, 
          "endTime": 1592718092
 },
 {
          "latencyAvg": "6.68ms", 
          "latencyMax": "39.30ms", 
          "latencyStdev": "3.92ms", 
          "totalRequests": 1151051, 
          "startTime": 1592718094, 
          "endTime": 1592718109
}
```
I will do another commit where I will add the buffer reserve logic and avoid Option.

### CODE REVIEW

**Comment by botika** [comment]
With `BytesMut` integrate in template engine runs a little faster:
```json
{
          "latencyAvg": "324.46us", 
          "latencyMax": "8.27ms", 
          "latencyStdev": "192.57us", 
          "totalRequests": 748192, 
          "startTime": 1592815867, 
          "endTime": 1592815882
}, 
{
          "latencyAvg": "567.66us", 
          "latencyMax": "8.75ms", 
          "latencyStdev": "338.21us", 
          "totalRequests": 864023, 
          "startTime": 1592815884, 
          "endTime": 1592815899
}, 
{
          "latencyAvg": "1.04ms", 
          "latencyMax": "14.21ms", 
          "latencyStdev": "725.74us", 
          "totalRequests": 963011, 
          "startTime": 1592815901, 
          "endTime": 1592815916
}, 
{
          "latencyAvg": "2.02ms", 
          "latencyMax": "18.36ms", 
          "latencyStdev": "1.67ms", 
          "totalRequests": 1042912, 
          "startTime": 1592815918, 
          "endTime": 1592815933
}, 
{
          "latencyAvg": "3.67ms", 
          "latencyMax": "31.27ms", 
          "latencyStdev": "2.78ms", 
          "totalRequests": 1110324, 
          "startTime": 1592815935, 
          "endTime": 1592815950
}, 
{
          "latencyAvg": "6.65ms", 
          "latencyMax": "48.33ms", 
          "latencyStdev": "3.97ms", 
          "totalRequests": 1156420, 
          "startTime": 1592815952, 
          "endTime": 1592815967
}
```

**Comment by fafhrd91** [comment]
@botika could try &str instead Cow

**Comment by botika** [comment]
@fafhrd91 I don't know how. You mean to have 2 `SmallVector`, like before the first commit?

**Comment by botika** [comment]
### Results at https://github.com/TechEmpower/FrameworkBenchmarks/pull/5789/commits/9828d442a15afcb31e1130d74bec78dcc995c684
```json
{
          "latencyAvg": "337.05us", 
          "latencyMax": "9.22ms", 
          "latencyStdev": "204.36us", 
          "totalRequests": 721050, 
          "startTime": 1592825212, 
          "endTime": 1592825227
        }, 
        {
          "latencyAvg": "599.83us", 
          "latencyMax": "9.59ms", 
          "latencyStdev": "360.05us", 
          "totalRequests": 819893, 
          "startTime": 1592825229, 
          "endTime": 1592825244
        }, 
        {
          "latencyAvg": "1.08ms", 
          "latencyMax": "11.02ms", 
          "latencyStdev": "746.64us", 
          "totalRequests": 932176, 
          "startTime": 1592825246, 
          "endTime": 1592825261
        }, 
        {
          "latencyAvg": "2.05ms", 
          "latencyMax": "23.92ms", 
          "latencyStdev": "1.67ms", 
          "totalRequests": 1025227, 
          "startTime": 1592825263, 
          "endTime": 1592825278
        }, 
        {
          "latencyAvg": "3.70ms", 
          "latencyMax": "29.69ms", 
          "latencyStdev": "2.73ms", 
          "totalRequests": 1093736, 
          "startTime": 1592825280, 
          "endTime": 1592825296
        }, 
        {
          "latencyAvg": "6.70ms", 
          "latencyMax": "35.35ms", 
          "latencyStdev": "3.89ms", 
          "totalRequests": 1143871, 
          "startTime": 1592825298, 
          "endTime": 1592825313
        }
```
I don't know what you mean. If you can do a PR to my branch or I reverse https://github.com/TechEmpower/FrameworkBenchmarks/pull/5789/commits/9828d442a15afcb31e1130d74bec78dcc995c684?

**Comment by fafhrd91** [comment]
hmm, it is slower. lets use your version without https://github.com/TechEmpower/FrameworkBenchmarks/commit/9828d442a15afcb31e1130d74bec78dcc995c684

**Comment by nbrady-techempower** [comment]
@botika @fafhrd91 is this PR ready?

**Comment by botika** [comment]
@nbrady-techempower It's ready

**Pull request merged**
