### PR TITLE
Fix random IDs

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Avoid duplicate IDs in Python tests.

Is it permittable to randomise it once at the top of the file, and avoid doing any random functions within the handlers?

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Appears this fails to fix the issue. Looks like all the python examples consistently get to:
`Rows updated: 10128/10240`

But, sometimes it comes out at 10126, which then fails the test. I suspect this is because of the random value being set. When we update the values, we pick a random number between 0-10000 and update the object. If that number is the same as the previously set number, then I'd expect sqlalchemy to drop the update statement again.
With over 10000 updates happening, it's normal to have anywhere from 0-2 duplicates like this.

**Comment by Dreamsorcerer** [comment]
@nbrady-techempower ^^^

**Comment by Dreamsorcerer** [comment]
Running the maths, there should be only a 36% chance that 0 collisions happen and the test succeeds.

**Comment by nbrady-techempower** [comment]
> Is it permittable to randomise it once at the top of the file, and avoid doing any random functions within the handlers?

There needs to be a mechanism in place that replenishes this array with a new set of randomly ordered numbers in the event is it exhausted. 

> Appears this fails to fix the issue. 

It may be worthwhile to wait a few days. We're still in the process of switching over to the new toolset and this might give you more insight into what's happening.

**Comment by Dreamsorcerer** [comment]
> > Is it permittable to randomise it once at the top of the file, and avoid doing any random functions within the handlers?
> 
> There needs to be a mechanism in place that replenishes this array with a new set of randomly ordered numbers in the event is it exhausted.

The current code just reuses the beginning of the array every time. So, multiple requests would get the same set of IDs. So, my question is more does it have to be shuffled on every request to give a different set of ids?

> It may be worthwhile to wait a few days. We're still in the process of switching over to the new toolset and this might give you more insight into what's happening.

Given the frequency, my theory that it is caused by the random number matching the existing value in the DB seems pretty likely. If a single update is missing, the test fails.

**Comment by nbrady-techempower** [comment]
> The current code just reuses the beginning of the array every time. So, multiple requests would get the same set of IDs. So, my question is more does it have to be shuffled on every request to give a different set of ids?

Yes, it needs to be randomized on each request.

**Comment by nbrady-techempower** [comment]
Hey @Dreamsorcerer ! It's been a bit since we talked about this. Any time to take a look at it or should I close it up for now?

**Comment by Dreamsorcerer** [comment]
Well, I don't know how to fix the issue, as I mentioned before the tests should probably fail with about a 64% chance. I'm not sure if there's maybe some option to sqlalchemy or something that could disable the optimisations, otherwise I don't see a fix.

Feel free to close the PR given that it doesn't resolve the issue.

**Pull request closed without merging**
