### PR TITLE
Add velocy, a minimal javascript framework

### PR DESCRIPTION
**Pull request by ishtms**
Hi, 
I would like to add Velocy, a new framework that I am building as a part of my open source book - [Learn Node.js the hard way](https://github.com/ishtms/learn-nodejs-hard-way)

### CODE REVIEW

**Comment by ishtms** [comment]
Hey @nbrady-techempower 
Any chance that this could be a part of the upcoming round? Would be great if possible.

**Comment by nbrady-techempower** [comment]
@ishtms Thanks for your submission. Could you please add the json test or at least one db test. We are not accepting any new frameworks that only include the plaintext test.

**Comment by ishtms** [comment]
> @ishtms Thanks for your submission. Could you please add the json test or at least one db test. We are not accepting any new frameworks that only include the plaintext test.

Definitey @nbrady-techempower

**Comment by ishtms** [comment]
@nbrady-techempower [this commit](https://github.com/TechEmpower/FrameworkBenchmarks/pull/8403/commits/e2152c7efac8e7041a8848f5ac5cb9e8417e7e52) adds json.

**Pull request merged**
