### PR TITLE
Create file for verification stage output and get rid of error file

### PR DESCRIPTION
**Pull request by cjnething**
- Addresses tasks 1 and 2 from Issue 1655
- Create file "verification.txt" for all verification stage output to be logged into
- Get rid of "err.txt" file and send all previous information that would have logged to that file to "out.txt" (which already existed)

### CODE REVIEW

**Comment by msmith-techempower** [comment]
This looks good to me; will merge in after round 13.

**Comment by msmith-techempower** [comment]
@cjnething This is a good start! I would like to break out `verification.txt` into several folder and files: `verification/json.txt`, `verification/db.txt`, etc with each only encompassing that particular verification.

Additionally, since we can, let's break out the benchmarking blocks into their own folder and files:
`benchmark/json.txt`, `benchmark/db.txt` etc. The contents of these files should be the data under the `Benchmarking [testname]` block (these look like "BENCHMARKING JSON... Complete").

**Comment by cjnething** [comment]
Updated the PR based on your comments

**Comment by msmith-techempower** [comment]
Just tested this and I love it; LGTM!

**Comment by cjnething** [comment]
Resolves #1655

**Pull request merged**
