### PR TITLE
Add a new framework - Lighty

### PR DESCRIPTION
**Pull request by light0x00**
Hello there!  I want to add a new test for my own network framework. 
I have completed all the steps in the README generated by wizard , and passed the verification.
Could you please check it for me? I will correct it if there is anything missing.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@light0x00 Are you planning on implementing other tests like json and db?

**Comment by light0x00** [comment]
> @light0x00 Are you planning on implementing other tests like json and db?

Thank you for your suggestion. Currently, I don't have plans to implement tests like JSON and DB.

**Comment by nbrady-techempower** [comment]
Thank you for your response @light0x00 

Unfortunately, we have made the decision to no longer accept frameworks that do not plan on implementing more that just plaintext. This takes up a lot of build time during our continuous runs. Ideally, plaintext or json and one db test will be enough, but for now, implementing json would be enough. Thanks.

**Comment by light0x00** [comment]
@nbrady-techempower 

Ok, I'll submit the PR next time. Sorry to bother you.

**Pull request closed without merging**
