### PR TITLE
Add new benchmarks for spring-webflux using rxjava and r2dbc

### PR DESCRIPTION
**Pull request by davidkiss**

### CODE REVIEW

**Comment by davidkiss** [comment]
@michaelhixson the PHP tests are filing in Travis CI, even though I didn't make any PHP related changes. Can you advice how I can resolve this issue?

**Comment by michaelhixson** [comment]
You don't need to change anything.

**Comment by davidkiss** [comment]
@michaelhixson I noticed that some of the webflux tests failed (https://www.techempower.com/benchmarks/#section=test&runid=39223fbd-beef-4543-b51e-ef01c2fba4f1) Is there a way to get more details (logs) on those failures?

**Comment by davidkiss** [comment]
Thanks so much for the detailed information! I'm looking into the issues now

**Pull request merged**
