### PR TITLE
Changes to fix failing nginx builds

### PR DESCRIPTION
**Pull request by sumeetchhetri**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@sumeetchhetri Seemingly unrelated, the apache tests and most of the fortune tests are no longer working. I say that because not only are they failing here but they're failing in master and other runs too. I don't think there were any changes that would have caused this, so maybe just dependencies that are no longer valid?

**Comment by sumeetchhetri** [comment]
The issue was due to rooted installation of unixodbc which was not letting the mysql and postgresql tests to run correctly, also nginx had issues with symlink'd so files which needed to be fixed in the binary of my framework. Hopefully this closes all issues once and for all.

**Comment by sumeetchhetri** [comment]
Also a side note, all these are passing locally, maybe there is something in travis that is messing things up. I infact even tried a new vagrant box and repeated the steps to verify this.

Command used - ./toolset/run-tests.py --mode verify --test  ffead-cpp  ffead-cpp-apache2-mongo  ffead-cpp-apache2-mysql  ffead-cpp-apache2-postgresql  ffead-cpp-mysql
 ffead-cpp-nginx-mongo ffead-cpp-nginx-mysql  ffead-cpp-nginx-postgresql  ffead-cpp-postgresql

================================================================================
  Verification Summary

| Test: ffead-cpp
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-apache2-mongo
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-apache2-mysql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-apache2-postgresql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-mysql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-mongo
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-mysql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-postgresql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-postgresql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
================================================================================

Time to complete: 1290 seconds
Results are saved in results/20170109101014

**Comment by nbrady-techempower** [comment]
@sumeetchhetri unfortunately this does not pass for me on a fresh vagrant install. 😢 It's passing more than what travis is currently showing though, so will have to look in to that.

did a fresh `vagrant up`, pulled in this PR, ran: 
`./toolset/run-tests.py --mode verify --test  ffead-cpp  ffead-cpp-apache2-mongo  ffead-cpp-apache2-mysql  ffead-cpp-apache2-postgresql  ffead-cpp-mysql ffead-cpp-nginx-mongo ffead-cpp-nginx-mysql  ffead-cpp-nginx-postgresql  ffead-cpp-postgresql`

**Result**:

```
================================================================================
  Verification Summary

| Test: ffead-cpp
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-apache2-mongo
|       fortune     : FAIL
|       plaintext   : FAIL
|       db          : FAIL
|       update      : FAIL
|       json        : FAIL
|       query       : FAIL
| Test: ffead-cpp-apache2-mysql
|       fortune     : FAIL
|       plaintext   : PASS
|       db          : WARN
|       update      : WARN
|       json        : PASS
|       query       : WARN
| Test: ffead-cpp-apache2-postgresql
|       fortune     : FAIL
|       plaintext   : PASS
|       db          : WARN
|       update      : WARN
|       json        : PASS
|       query       : WARN
| Test: ffead-cpp-mysql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-mongo
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-mysql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-nginx-postgresql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
| Test: ffead-cpp-postgresql
|       fortune     : PASS
|       plaintext   : PASS
|       db          : PASS
|       update      : PASS
|       json        : PASS
|       query       : PASS
================================================================================

```

**Comment by msmith-techempower** [comment]
It looks like we are getting close on this one, but before we merge it the `sudo`s should be removed as much as possible.

Specifically, anything creating files in `$IROOT` or at any depth uder `$TROOT` **must not** be done with `sudo`.

One should be able to run the following successfully (this means without errors about permissions):
```
./toolset/run-tests.py --mode verify --test ffead-cpp ffead-cpp-apache2-mongo ffead-cpp-apache2-mysql ffead-cpp-apache2-postgresql ffead-cpp-mysql ffead-cpp-nginx-mongo ffead-cpp-nginx-mysql ffead-cpp-nginx-postgresql ffead-cpp-postgresql

rm -rf results installs

git reset --hard
```

**Comment by msmith-techempower** [comment]
Tests are [still failing](https://s3.amazonaws.com/archive.travis-ci.org/jobs/190701330/log.txt) 😢 

```
[36m================================================================================
[36m  Verification Summary
[36m
[36m| Test: ffead-cpp
[36m|       fortune     : [32mPASS
[36m|       plaintext   : [32mPASS
[36m|       db          : [32mPASS
[36m|       update      : [32mPASS
[36m|       json        : [32mPASS
[36m|       query       : [32mPASS
[36m| Test: ffead-cpp-apache2-mongo
[36m|       fortune     : [32mPASS
[36m|       plaintext   : [32mPASS
[36m|       db          : [32mPASS
[36m|       update      : [32mPASS
[36m|       json        : [32mPASS
[36m|       query       : [32mPASS
[36m| Test: ffead-cpp-apache2-mysql
[36m|       fortune     : [32mPASS
[36m|       plaintext   : [32mPASS
[36m|       db          : [32mPASS
[36m|       update      : [32mPASS
[36m|       json        : [32mPASS
[36m|       query       : [32mPASS
[36m| Test: ffead-cpp-apache2-postgresql
[36m|       fortune     : [32mPASS
[36m|       plaintext   : [32mPASS
[36m|       db          : [32mPASS
[36m|       update      : [32mPASS
[36m|       json        : [32mPASS
[36m|       query       : [32mPASS
[36m| Test: ffead-cpp-mysql
[36m|       fortune     : [31mFAIL
[36m|       plaintext   : [31mFAIL
[36m|       db          : [31mFAIL
[36m|       update      : [31mFAIL
[36m|       json        : [31mFAIL
[36m|       query       : [31mFAIL
[36m| Test: ffead-cpp-nginx-mongo
[36m|       fortune     : [31mFAIL
[36m|       plaintext   : [31mFAIL
[36m|       db          : [31mFAIL
[36m|       update      : [31mFAIL
[36m|       json        : [31mFAIL
[36m|       query       : [31mFAIL
[36m| Test: ffead-cpp-nginx-mysql
[36m|       fortune     : [31mFAIL
[36m|       plaintext   : [31mFAIL
[36m|       db          : [31mFAIL
[36m|       update      : [31mFAIL
[36m|       json        : [31mFAIL
[36m|       query       : [31mFAIL
[36m| Test: ffead-cpp-nginx-postgresql
[36m|       fortune     : [31mFAIL
[36m|       plaintext   : [31mFAIL
[36m|       db          : [31mFAIL
[36m|       update      : [31mFAIL
[36m|       json        : [31mFAIL
[36m|       query       : [31mFAIL
[36m| Test: ffead-cpp-postgresql
[36m|       fortune     : [32mPASS
[36m|       plaintext   : [32mPASS
[36m|       db          : [32mPASS
[36m|       update      : [32mPASS
[36m|       json        : [32mPASS
[36m|       query       : [32mPASS
[36m================================================================================
```

**Comment by sumeetchhetri** [comment]
Finally after all those changes all ffead-cpp tests pass successfully,
https://s3.amazonaws.com/archive.travis-ci.org/jobs/190927728/log.txt
I'm a very happy man right now :-)

**Comment by nbrady-techempower** [comment]
@sumeetchhetri And passing locally and on travis! You are my hero! Merging!

**Pull request merged**
