### PR TITLE
Python updates for Round 11

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by GMLudo** [comment]
+10, everything seems to be ok, at least to me.
Failed Travis-CI has failed, but only on others stuffs than Python part.

**Comment by methane** [comment]
@GMLudo FYI, I didn't touch to API-Hour since it may conflict with you.
I used [piprot](https://pypi.python.org/pypi/piprot) to find outdated packages.

**Comment by GMLudo** [comment]
@methane thank you, I recognize I'm in the middle of the river for now to push my modifications, I'll push that as soon as possible, but my day job work has the priority for now.
However, if you see something to improve or to fix, don't hesitate to notify me and/or make a pull request, it's always interesting to have another pair of eyes on the source code.

**Comment by GMLudo** [comment]
Yocto detail: You've forgotten to change Python versions in **frameworks/Python/README.md**.

**Comment by methane** [comment]
> Yocto detail: You've forgotten to change Python versions in frameworks/Python/README.md.

I did it.

**Comment by GMLudo** [comment]
BTW, thank you for piprot tip, I didn't know, I've just used to upgrade requirements of API-Hour, it's an useful tool.
I've added in my Python toolbox.

**Comment by msmith-techempower** [comment]
Travis suggests all the tests passed except for Flask, Falcon, and Bottle. Specifically, `bottle-pypy`, `falcon-pypy`, `flask-pypy`, and `flask-pypy-mysql-raw`.

**Comment by msmith-techempower** [comment]
I pulled your branch onto a clean local vm and tested the erroring pypy tests. They all passed; LGTM!

**Comment by hamiltont** [comment]
amazing work, this is really nice to have

**Pull request merged**
