### PR TITLE
[FASTAPI] Bump dependencies

### PR DESCRIPTION
**Pull request by micaelmalta**
Python 3.11
Fastapi 0.92.0
Nginx-unit 1.29.1
asynpg 0.27.0
ujson 5.7.0
orjson 3.8.7
psycopg2 2.9.5
SQLAlchemy 1.4.45
uvicorn 0.20.0

### CODE REVIEW

**Comment by joanhey** [comment]
Fail Nginx Unit
Check: https://github.com/nginx/unit/issues/794

**Comment by tippexs** [comment]
@joanhey what’s the error message for Unit? Happy to dig into. We are currently having issues with Python > 3.9.7. happy to help to resolve the issue.

**Comment by nbrady-techempower** [comment]
@micaelmalta Is this meant to be in draft still?

**Comment by micaelmalta** [comment]
> @micaelmalta Is this meant to be in draft still?

Waiting for nginx-unit to release an official image

**Comment by micaelmalta** [comment]
Nginx-unit is working now with Python 3.11
We are good to go!

**Pull request merged**
