### PR TITLE
Jawn new version

### PR DESCRIPTION
**Pull request by MTDdk**
New version needs some folder renaming and controller refactoring

### CODE REVIEW

**Comment by blee-techempower** [comment]
Did not pass localtest.
```
Setup jawn: * Where:
Setup jawn: Build file '/home/blee/FrameworkBenchmarks/frameworks/Java/jawn/build.gradle' line: 22
Setup jawn:
Setup jawn: * What went wrong:
Setup jawn: Could not compile build file '/home/blee/FrameworkBenchmarks/frameworks/Java/jawn/build.gradle'.
Setup jawn: > startup failed:
Setup jawn:   build file '/home/blee/FrameworkBenchmarks/frameworks/Java/jawn/build.gradle': 22: unexpected token: << @ line 22, column 1.
Setup jawn:      <<<<<<< HEAD
Setup jawn:      ^
Setup jawn:
Setup jawn:   1 error
Setup jawn:
Setup jawn:
Setup jawn: * Try:
Setup jawn: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Setup jawn:
Setup jawn: BUILD FAILED
```

Please resolve this issue.

**Comment by MTDdk** [comment]
Looks like you have a merge conflict.

I have been looking at every branch for Techempower as well as your own, and I cannot find anywhere, where the build.gradle contains a line: `<<<<<<< HEAD`

Can you verify that this looks like a merge conflict?

**Comment by MTDdk** [comment]
I have made the merge myself, which should fix any errors you have. 
Hopefully

**Comment by blee-techempower** [comment]
Localtest passed.

**Pull request merged**
