### PR TITLE
update to pyramid 2.0

### PR DESCRIPTION
**Pull request by slav0nic**
- pyramid 2.0
- sqlalchemy1.4
- python3.10
- remove python2
- update requirements
- orjson

### CODE REVIEW

**Comment by slav0nic** [comment]
looks live `verify` is not correct, if i run `./tfb --mode verify  --concurrency-level 1 --test pyramid`
in every test i got -1 request:
db -  Executed queries: 1/1, Rows read: **0**/1
updates - Executed queries: 40/40, Rows read: **19**/20, Rows updated: **19**/20

if i run locally with enabled postgresql logging:
**/db**
```
2021-12-14 12:45:57.653 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: BEGIN
2021-12-14 12:45:57.653 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT t.oid, typarray
	FROM pg_type t JOIN pg_namespace ns
	    ON typnamespace = ns.oid
	WHERE typname = 'hstore';
	
2021-12-14 12:45:57.663 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: ROLLBACK
2021-12-14 12:45:57.663 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: BEGIN
2021-12-14 12:45:57.663 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: select pg_catalog.version()
2021-12-14 12:45:57.665 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: select current_schema()
2021-12-14 12:45:57.666 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: show transaction isolation level
2021-12-14 12:45:57.666 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: show standard_conforming_strings
2021-12-14 12:45:57.666 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: ROLLBACK
2021-12-14 12:45:57.668 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: BEGIN
2021-12-14 12:45:57.668 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 1804
2021-12-14 12:45:57.673 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: ROLLBACK
```
**updates/queries=20**
```
2021-12-14 12:46:49.005 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: BEGIN
2021-12-14 12:46:49.005 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 9410
2021-12-14 12:46:49.006 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 8714
2021-12-14 12:46:49.007 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 3848
2021-12-14 12:46:49.008 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 4293
2021-12-14 12:46:49.009 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 2300
2021-12-14 12:46:49.009 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 3441
2021-12-14 12:46:49.010 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 1115
2021-12-14 12:46:49.011 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 7827
2021-12-14 12:46:49.011 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 9513
2021-12-14 12:46:49.012 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 4353
2021-12-14 12:46:49.013 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 5956
2021-12-14 12:46:49.013 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 215
2021-12-14 12:46:49.014 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 5108
2021-12-14 12:46:49.015 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 4908
2021-12-14 12:46:49.016 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 8386
2021-12-14 12:46:49.016 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 149
2021-12-14 12:46:49.017 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 5515
2021-12-14 12:46:49.018 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 5465
2021-12-14 12:46:49.019 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 2186
2021-12-14 12:46:49.021 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: SELECT world.randomnumber AS world_randomnumber, world.id AS world_id 
	FROM world 
	WHERE world.id = 7223
2021-12-14 12:46:49.025 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=1005 WHERE world.id = 149
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=6776 WHERE world.id = 215
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=4418 WHERE world.id = 1115
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=9650 WHERE world.id = 2186
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=806 WHERE world.id = 2300
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=6454 WHERE world.id = 3441
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=7278 WHERE world.id = 3848
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=3045 WHERE world.id = 4293
2021-12-14 12:46:49.026 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=398 WHERE world.id = 4353
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=3553 WHERE world.id = 4908
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=5886 WHERE world.id = 5108
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=8275 WHERE world.id = 5465
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=2979 WHERE world.id = 5515
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=2729 WHERE world.id = 5956
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=4068 WHERE world.id = 7223
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=9541 WHERE world.id = 7827
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=7587 WHERE world.id = 8386
2021-12-14 12:46:49.027 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=8721 WHERE world.id = 8714
2021-12-14 12:46:49.028 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=2089 WHERE world.id = 9410
2021-12-14 12:46:49.028 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: UPDATE world SET randomnumber=5670 WHERE world.id = 9513
2021-12-14 12:46:49.029 EET [2488268] slav0nic@frameworkbenchmarks СООБЩЕНИЕ:  оператор: COMMIT
```
so, it's correct 

cc @nbrady-techempower

**Comment by nbrady-techempower** [comment]
I haven't had a chance to look at this yet @slav0nic -- What does the ORM you're using do if you come across the same `id` twice? Is it doing any caching, etc?

**Comment by slav0nic** [comment]
Yes, sqlalchemy have something like caching in this case, but it not related to verify, i tested it locally with 100% unique values and got same error.
By default  changes like obj.value = obj_same_value not generating update

**Comment by slav0nic** [comment]
okey,  I give up :)
added `flag_modified` call, but i really don't like main idea changing default ORM framework behavior for passing benchmark verification step.

**Pull request merged**
