### PR TITLE
Add async-db test, update deps

### PR DESCRIPTION
**Pull request by ikitommi**
* Add reactive SQL test for Clojure/Reitit.
* Update dependencies
* Fix reflection warning
* Set worker thread pool to 256

### CODE REVIEW

**Comment by ikitommi** [comment]
Hi. Any change of this getting into round18 results? on my tests, ~doubles the db-perf, making Clojure one of the fastest entries there. Would like to see that in the official results.

cheers.

**Comment by nbrady-techempower** [comment]
@ikitommi Unfortunately, probably not. We've captured citrine results for round 18 and we're running Azure (we only have a limited number of credits) off of that same commit.

**Comment by ikitommi** [comment]
Credits? When the citrine results for b8e862a759 (with this in) arrive, if the results are what I expect, is it possible to add more credits to run azure too with it? How much would be needed? If the price is known, could ask our company to sponsor the needed credits, if you take test credit donations. Many ifs :)

**Comment by ikitommi** [comment]
It seems that the changes are actually in ae69f390a8ec33f6159bbfc5c2f7947af06d5626, which only just started. Is it possible to sponsor an extra round for azure? Anyway, thanks for the benchmarks.

**Comment by nbrady-techempower** [comment]
@ikitommi I'll pass this along but I think there's too many moving pieces to get that all approved from our end, too. We've been pretty busy with our paying clients so we can keep the lights on. :wink: We are probably evaluating the two runs we captured for the round this week to make sure there are no glaring issues so we can get the round published. If that changes, I'll let you know. Our "credits" reset every month, sponsored by the MS team. We usually do some basic tests and then one full run on Azure.

**Pull request merged**
