### PR TITLE
Warn for test if value of randomNumber is greater than 10,000, Resolve #1142

### LINKED ISSUE #1142: Add a verify warning if randomNumber is not within range
A few tests are accidentally returning randomNumbers that are to big, e.g. 323234. We only require numbers between 1 and 10000. There's no reason to disqualify tests for this, but it would be nice to automatically point out to them that these few extra bytes per request could harm their performance

PS - this check should go at the bottom of `db_type.py`

### PR DESCRIPTION
**Pull request by LadyMozzarella**
Warn for single database query, multiple database queries, and update when a value of randomNumber from the returned json response is greater than 10,000.

### CODE REVIEW

**Comment by hamiltont** [comment]
LGTM. Are we good to merge into master now?

**Comment by msmith-techempower** [comment]
Please hold off for a bit.

**Comment by msmith-techempower** [comment]
Actually, go ahead - I just confirmed that `round-10` branch is correct hash.

**Comment by hamiltont** [comment]
Looks good on [travis](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/56590553)

**Pull request merged**
