### PR TITLE
ULib: optimization

### PR DESCRIPTION
**Pull request by stefanocasazza**
Hi,
as I wrote in the previous request ULib disappeared from the results of round 10...

Greeting
Stefano

### CODE REVIEW

**Comment by msmith-techempower** [comment]
@stefanocasazza Looks like you need to rebase off our latest master as `frameworks/C++/ULib` was moved to `frameworks/C++/ulib`

**Comment by stefanocasazza** [comment]
Hi,

I suspected that it was necessary, it should now be in place...

Thanks
Stefano


2015-12-10 19:15 GMT+01:00 Mike Smith <notifications@github.com>:

**Comment by msmith-techempower** [comment]
I don't know why Travis-CI hasn't picked up on this...

@ssmith-techempower Please pull and test locally.

**Comment by ssmith-techempower** [comment]
Everything's passing locally, LGTM.

**Pull request merged**
