### PR TITLE
Switch from go1.5 to go1.6

### PR DESCRIPTION
**Pull request by valyala**
Go 1.6 is out a month ago, so it would be great to run Go tests with it.

### CODE REVIEW

**Comment by kostya-sh** [comment]
A while ago I ran go TFB benchmarks using Go 1.5 and 1.6. One thing that I found is that the garbage collector in 1.6 is more accurate at keeping heap size based on `GOGC` value. GC in 1.5 generally tends to overcommit memory. As result the application compiled with 1.6 uses less memory but performs worse in throughput based benchmark like TFB.

I suggest to raise GOGC to 1000 (from 800) to account for more accurate GC algorithm in 1.6:

    echo "export GOGC=1000" >> $IROOT/go.installed

**Comment by methane** [comment]
+1 for @kostya-sh

**Comment by valyala** [comment]
@kostya-sh , done.

**Comment by valyala** [comment]
It looks like Go/revel* [failed to build with go 1.6](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/116053178), since it depends on deprecated code from code.google.com, which has been disabled in go1.6:

> package code.google.com/p/go.net/websocket: unable to detect version control system for code.google.com/ path

@msmith-techempower , let's leave revel tests broken until @robfig removes deprecated code.google.com dependency from [github.com/robfig/revel/](https://github.com/robfig/revel).

**Comment by methane** [comment]
@valyala I've noticed it and fixed in #1964.  Please ignore it.

**Comment by methane** [comment]
Uh...
I haven't noticed about revel-jet and revel-qbs.
I'll fix it.

**Comment by msmith-techempower** [comment]
I am content with this and Travis tests mostly pass; LGTM!

**Pull request merged**
