### PR TITLE
use beef for ntex

### PR DESCRIPTION
**Pull request by pickfire**
@fafhrd91 https://github.com/maciejhirsz/beef is a faster `Cow`, there are two versions `beef::Cow` and `beef::lean::Cow`, I tried `beef::lean::Cow` here which uses 2 bytes.

```
before
{'results': [{'endTime': 1596988310,
              'latencyAvg': '8.79ms',
              'latencyMax': '70.97ms',
              'latencyStdev': '6.62ms',
              'startTime': 1596988295,
              'totalRequests': 4719808},
             {'endTime': 1596988327,
              'latencyAvg': '50.13ms',
              'latencyMax': '274.04ms',
              'latencyStdev': '34.41ms',
              'startTime': 1596988312,
              'totalRequests': 3103856},
             {'endTime': 1596988344,
              'latencyAvg': '112.15ms',
              'latencyMax': '465.45ms',
              'latencyStdev': '66.35ms',
              'startTime': 1596988329,
              'totalRequests': 5002304},
             {'endTime': 1596988363,
              'latencyAvg': '496.59ms',
              'latencyMax': '1.25s',
              'latencyStdev': '243.33ms',
              'startTime': 1596988346,
              'totalRequests': 2337216}]}

after
{'results': [{'endTime': 1596992340,
              'latencyAvg': '8.61ms',
              'latencyMax': '75.25ms',
              'latencyStdev': '6.76ms',
              'startTime': 1596992325,
              'totalRequests': 4976336},
             {'endTime': 1596992358,
              'latencyAvg': '48.19ms',
              'latencyMax': '267.83ms',
              'latencyStdev': '32.04ms',
              'startTime': 1596992342,
              'totalRequests': 3131920},
             {'endTime': 1596992375,
              'latencyAvg': '190.70ms',
              'latencyMax': '796.74ms',
              'latencyStdev': '124.03ms',
              'startTime': 1596992360,
              'totalRequests': 3103472},
             {'endTime': 1596992393,
              'latencyAvg': '350.07ms',
              'latencyMax': '976.95ms',
              'latencyStdev': '178.47ms',
              'startTime': 1596992377,
              'totalRequests': 2688192}]}
```

Benchmarks on my computer may not be accurate, quite a lot of stuff I am running while benchmarking, not sure if it affected the benchmarks.

### CODE REVIEW

**Comment by fafhrd91** [comment]
I am not really sure, but your change should affect only "fortunes" test,
and it is lower after the change, before 5_002_304 vs 3_103_472 after. and other results should not change.

could you re-run bench for "fortunes" test only?

**Comment by pickfire** [comment]
I got
```
--------------------------------------------------------------------------------
Benchmarking ntex
--------------------------------------------------------------------------------
ntex: Traceback (most recent call last):
ntex:   File "/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 167, in __run_test
ntex:     accepting_requests = test.is_accepting_requests()
ntex:   File "/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 77, in is_accepting_requests
ntex:     self.runTests[test_type].get_url())
ntex: KeyError: None
ntex: Error during test: ntex
ntex: Total test time: 1m 2s
tfb: Total time building so far: 1m 2s
tfb: Total time verifying so far: 0s
tfb: Total execution time so far: 1m 11s
```
with `./tfb --test ntex --type fortune`, seemed like there are no results, did I do anything wrong?

**Comment by fafhrd91** [comment]
ok, let's just test it with next tfb run and then will decide.

**Comment by pickfire** [comment]
@fafhrd91 By the way, do you know how drogon getFastDbClient is able to be have database calls so fast? I saw the numbers for database updates was very impressive for the last round.

**Comment by fafhrd91** [comment]
i think it uses batch mode on libpq level. need to investigate and implement the same

**Comment by pickfire** [comment]
How come tfb-status.techempower.com gives `hello, world `? Will the results be out?

**Comment by nbrady-techempower** [comment]
@pickfire tfb-status went down over the weekend due to an outage. we're getting it back up today. thanks.

**Comment by pickfire** [comment]
The results are out. Did it improved?

**Comment by fafhrd91** [comment]
@pickfire performance is worse than before. change should be reverted

**Comment by pickfire** [comment]
@maciejhirsz

**Pull request merged**
