### PR TITLE
Add Dlang Collie 

### PR DESCRIPTION
**Pull request by dushibaiyu**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@dushibaiyu Thanks for the contribution! A few things to start. Please add:
`    - "TESTDIR=D/collie"` 
to the `.travis.yml` file in the project root. Also, please include a `README.md` similar to [this one](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Perl/mojolicious/README.md) so we can get some more information about the framework.

**Comment by dushibaiyu** [comment]
updated

**Comment by nbrady-techempower** [comment]
@dushibaiyu Thank you! We are seeing failures on Travis now. Please take a look when you can. Thanks!

**Comment by dushibaiyu** [comment]
it can not find dub.
maybe I should add dub in step.sh

**Comment by tchaloupka** [comment]
From the travis build log when it fails previously, it was because then the #2648 was not merged yet so there was the older dmd without dub packaged in it.

See:
```
Setup Collie: +++DMDVER=2.071.1

Setup Collie: +++LDCVER=1.0.0

Setup Collie: +++mkdir -p /home/travis/build/TechEmpower/FrameworkBenchmarks/installs/dlang

Setup Collie: +++fw_get -O http://downloads.dlang.org/releases/2.x/2.071.1/dmd_2.071.1-0_amd64.deb

Setup Collie: +++curl -sL -O http://downloads.dlang.org/releases/2.x/2.071.1/dmd_2.071.1-0_amd64.deb
...
```

Now it is merged so there is no need to depend on dub in the setup. See current build log for vibe: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/218750261

**Comment by dushibaiyu** [comment]
update, and wait test

**Comment by tchaloupka** [comment]
@nbrady-techempower this seems ok now, error in travis is unrelated

**Comment by nbrady-techempower** [comment]
@tchaloupka It's possible that if I merge this in now it will get in to Round 14 final without the chance for you to see any preview data. I can wait until after Round 14 is complete or I can get this in now.. Up to you.

**Comment by nbrady-techempower** [comment]
Looks like it may have missed the cutoff for final, but will get this in nonetheless.

**Pull request merged**
