### PR TITLE
Update Zebra and Giraffe to .NET Core 3.1.1

### PR DESCRIPTION
**Pull request by forki**
Just small fixes to update Zebra and Giraffe to .NET Core 3.1.1

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@forki This image doesn't appear to exist?

**Comment by forki** [comment]
Yes trying to figure it out. That's why I marked it wip for now.

**Comment by forki** [comment]
@nbrady-techempower this should now use the correct image. Unfortunately travis seems to take a big nap

**Comment by forki** [comment]
Green! Yay

**Pull request merged**
