### PR TITLE
Actix web 2.0

### PR DESCRIPTION
**Pull request by fafhrd91**
* Upgrade to actix-web 2.0.0

### CODE REVIEW

**Comment by cdbattags** [comment]
would love to get this in asap to see the power of tokio 2.0 and the new futures in Rust

**Comment by cdbattags** [comment]
@nbrady-techempower adding ya on here to potentially expedite

**Comment by cdbattags** [comment]
looks like this is gonna be huge

actix 2.0

```
VERIFYING QUERY COUNT FOR http://tfb-server:8080/db
--------------------------------------------------------------------------------
New configuration template added to /root/.siege
Run siege -C to view the current settings in that file
** SIEGE 4.0.4
** Preparing 512 concurrent users for battle.
The server is now under siege...
Transactions:		         512 hits
Availability:		      100.00 %
Elapsed time:		        0.30 secs
Data transferred:	        0.02 MB
Response time:		        0.18 secs
Transaction rate:	     1706.67 trans/sec
Throughput:		        0.05 MB/sec
Concurrency:		      311.10
Successful transactions:         512
Failed transactions:	           0
Longest transaction:	        0.29
Shortest transaction:	        0.01
```

vs actix-web 1.x

```
VERIFYING QUERY COUNT FOR http://tfb-server:8080/db
--------------------------------------------------------------------------------
New configuration template added to /root/.siege
Run siege -C to view the current settings in that file
** SIEGE 4.0.4
** Preparing 512 concurrent users for battle.
The server is now under siege...
Transactions:		         512 hits
Availability:		      100.00 %
Elapsed time:		        0.43 secs
Data transferred:	        0.02 MB
Response time:		        0.27 secs
Transaction rate:	     1190.70 trans/sec
Throughput:		        0.03 MB/sec
Concurrency:		      322.40
Successful transactions:         512
Failed transactions:	           0
Longest transaction:	        0.41
Shortest transaction:	        0.09
```

**Comment by cdbattags** [comment]
@fafhrd91 Looks like we got a good improvement for actix-core but the other flavors took a hit. Any ideas?

https://www.techempower.com/benchmarks/#section=test&runid=e9d1ff59-7257-48ca-aec5-7166bb546d04&hw=cl&test=fortune

**Comment by fafhrd91** [comment]
I am experimenting with actix-pg

**Pull request merged**
