### PR TITLE
add edap-http framework 

### PR DESCRIPTION
**Pull request by luyongshou**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
You will need to add this framework to the [.travis.yml file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml#L57) so that it can be tested

**Comment by luyongshou** [comment]
> You will need to add this framework to the [.travis.yml file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml#L57) so that it can be tested

i have add to .travis.yml

**Comment by luyongshou** [comment]
> You will need to add this framework to the [.travis.yml file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml#L57) so that it can be tested

Why hasn't my pull request been merged yet?

**Comment by nbrady-techempower** [comment]
@luyongshou Because we were having trouble with other things and I haven't reviewed it yet. I will look at it tomorrow.

**Comment by nbrady-techempower** [comment]
@luyongshou Please rebase and fix this merge conflict and then I will get this in today. Thanks.

**Pull request merged**
