### PR TITLE
[JavaScript] Add uWebSockets.js

### PR DESCRIPTION
**Pull request by xeoneux**

### CODE REVIEW

**Comment by joanhey** [comment]
Fix #6217

**Comment by xeoneux** [comment]
I don't know why that verify JS is failing, any ideas?

**Comment by xeoneux** [comment]
I have checked locally, all the tests are passing
@nbrady-techempower

**Comment by nbrady-techempower** [comment]
Rerunning the job

**Comment by xeoneux** [comment]
I see this issue:
```
TypeError: Cannot read property 'id' of undefined
Error: Unhandled error: TypeError: Cannot read property 'id' of undefined
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5368:56), <anonymous>:12:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/runner/work/_actions/actions/github-script/v3.1.0/dist/index.js:5394:20)
```
in actions/github-script@v3.1.0

**Comment by xeoneux** [comment]
@nbrady-techempower any resolution for this please?

**Comment by nbrady-techempower** [comment]
@xeoneux This doesn't look like a problem with our toolset. Please try updating a file to get the job to rerun, as it's too old now.

Also, any reason you're not using the active lts for node?

**Comment by xeoneux** [comment]
Hi @nbrady-techempower I have updated the Node.js version

**Pull request merged**
