### PR TITLE
Inverno framework test

### PR DESCRIPTION
**Pull request by jkuhn1**

### CODE REVIEW

**Comment by jkuhn1** [comment]
I've been able to verify and run the test, however I haven't been able to find what to update in `.github/workflows/build.yml` following the documentation is this still up to date?

**Comment by nbrady-techempower** [comment]
You don't have to do anything for the github workflows, it just requires approval from first time contribs.

Can you remove some of the files not needed for our tests, like the .sql file.

**Comment by jkuhn1** [comment]
I've just removed the .sql file, there shouldn't be any nonessential file left.

**Comment by jkuhn1** [comment]
Hi, any news on this one? Is there anything else I need to do to merge it?

**Pull request merged**
