### PR TITLE
Update Wicket to 7.5.0

### PR DESCRIPTION
**Pull request by martin-g**
* Use Jackson Afterburner
* Serialize to byte[] instead of String
* Reduce the number of response headers by disabling Wicket handling for caching headers
* Use custom IRequestMapper that directly matches on the request url instead of using Wicket's logic to calculate the best

### CODE REVIEW

**Comment by martin-g** [comment]
The PR template says to use branch `round-14` but there is no such. Please update the PR template.

**Comment by martin-g** [comment]
@dashorst Please review!

**Comment by martin-g** [comment]
Is there a way to see the Resin server logs at Travis ?

**Comment by dashorst** [comment]
Couldn't discover any issue with the code while reviewing it. 

👍

**Comment by martin-g** [comment]
Thanks!
I have to figure out why Resin doesn't like the changes. It is either the new version of MySQL driver or the new RequestMapper.
Another option is to use embedded web server instead.

**Comment by knewmanTE** [comment]
@martin-g Thanks for the PR and for the heads up about the Pull Request Template! I've updated the template now that Round 13 is over.

I don't believe there is any way to check the logs on Travis, as it wipes itself clean after each execution. But I am seeing the wicket test fail when I run it locally. Is the issue something that you might be able to debug on your local instance?

**Comment by martin-g** [comment]
I'll have to read the documentation how to run it in Vagrant.
I have ran it locally in Tomcat and everything is fine.

If you still have the logs could you please paste the exception here ?

**Comment by knewmanTE** [comment]
This is what I'm seeing when I start up the server with `resinctl console`:

```
Starting Resin on Wed, 30 Nov 2016 11:50:11 -0800 (PST)

[11:50:13.071] 
[11:50:13.071] Resin-4.0.41 (built Mon, 22 Sep 2014 09:54:25 PDT)
[11:50:13.071] 
[11:50:13.071] Linux 4.2.0-27-generic amd64
[11:50:13.071] Java(TM) SE Runtime Environment 1.8.0_111-b14, UTF-8, en
[11:50:13.071] Java HotSpot(TM) 64-Bit Server VM 25.111-b14, 64, mixed mode, Oracle Corporation
[11:50:13.071] 
[11:50:13.071] user.name  = testrunner
[11:50:13.202] Table[mnode:2,/home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/resin-data/default/distcache/mnode.db] validating indexes due to unclean shutdown.
[11:50:13.257] Table[data:3,/home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/resin-data/default/distcache/data.db] validating indexes due to unclean shutdown.
[11:50:13.274] 
[11:50:13.274] resin.home = /home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/
[11:50:13.274] resin.root = /home/knewman/FrameworkBenchmarks/installs/resin-4.0.41
[11:50:13.274] resin.conf = /home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/conf/resin.xml
[11:50:13.275] 
[11:50:13.275] server    = 127.0.0.1:-1 (:default)
[11:50:13.275] stage      = production
[11:50:15.229] servlet-mapping *.jsp -> resin-jsp
[11:50:15.230] servlet-mapping *.jspf -> resin-jsp
[11:50:15.230] servlet-mapping *.jspx -> resin-jspx
[11:50:15.268] servlet-mapping *.php -> resin-php
[11:50:15.268] servlet-mapping / -> resin-file
[11:50:15.308] resin:import '/home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/webapps/wicket/WEB-INF/web.xml'
[11:50:15.355] In-place class redefinition (HotSwap) is available.
[11:50:15.432] resin:import '/home/knewman/FrameworkBenchmarks/installs/resin-4.0.41/webapps/wicket/WEB-INF/resin-web.xml'
[11:50:15.532] WEB-INF/resin-web.xml:5: com.caucho.sql.DriverConfig.setType(): com.caucho.config.ConfigRuntimeException: java.lang.ClassNotFoundException: com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource (in EnvironmentClassLoader[web-app:production/webapp/default/wicket,NEW])
               
               3: <database jndi-name='jdbc/hello_world'>
               4:   <driver>
               5:     <type>com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource</type>
               6:    
               7: 		<url>jdbc:mysql://127.0.0.1:3306/hello_world?jdbcCompliantTruncation=false&amp;elideSetAutoCommits=true&amp;useLocalSessionState=true&amp;cachePrepStmts=true&amp;cacheCallableStmts=true&amp;alwaysSendSetIsolation=false&amp;prepStmtCacheSize=4096&amp;cacheServerConfiguration=true&amp;prepStmtCacheSqlLimit=2048&amp;zeroDateTimeBehavior=convertToNull&amp;traceProtocol=false&amp;useUnbufferedInput=false&amp;useReadAheadInput=false&amp;maintainTimeStats=false&amp;useServerPrepStmts&amp;cacheRSMetadata=true</url>
               
[11:50:15.533] Host[production/host/default] active
[11:50:15.536] ServletService[id=default,cluster=] active
[11:50:15.537] 
[11:50:15.546] http listening to *:8080
[11:50:15.571] 
[11:50:15.573] Resin[id=default] started in 4202ms
```

It looks like it's having some issues with the `com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource` class in src/main/webapp/WEB-INF/resin-web.xml

**Comment by martin-g** [comment]
Thank you!
I'll update the PR tomorrow!

**Comment by martin-g** [comment]
Time to run vagrant here!

**Comment by knewmanTE** [comment]
@martin-g make sure to remove [this line](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2374/files#diff-59f36bd10b3bcd63153cc08f407bc369L5) now that you've removed the resin-web.xml file.

**Comment by martin-g** [comment]
Done! Thank you!

**Comment by knewmanTE** [comment]
Thanks! Otherwise this looks good!

**Comment by martin-g** [comment]
@knewmanTE  Did the tests pass for you ?
Last Travis build was saying something like "No tests were ran".

**Comment by knewmanTE** [comment]
@martin-g yes, I tested Wicket locally and it ran fine. The only issue with the last Travis build is that it [it was breaking on the sed line](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/180319078#L2208).

**Comment by martin-g** [comment]
Yey! :fireworks: 
Thanks!

**Pull request merged**
