### PR TITLE
Update Ben connection string

### PR DESCRIPTION
**Pull request by benaadams**
Update max pool size

### CODE REVIEW

**Comment by sebastienros** [comment]
Only if you update the other benchmarks

**Comment by NinoFloris** [comment]
I'll do the others tomorrow ;)

**Comment by benaadams** [comment]
> Only if you update the other benchmarks

Not merged the change in aspnet/benchmarks so seems wrong to propergate it for the others?

**Comment by roji** [comment]
Have no fear - am gonna benchmark the change on the others tomorrow.

**Pull request merged**
