### PR TITLE
OfficeFloor

### PR DESCRIPTION
**Pull request by sagenschneider**
Requires the:
 - java 8 fix
 - PR to use latest maven version

### CODE REVIEW

**Comment by sagenschneider** [comment]
Dependent on PR #1912

**Comment by msmith-techempower** [comment]
`.travis.yml` needs to be updated to include testing of officefloor

**Comment by sagenschneider** [comment]
Ok, will update .travis.yml.   Do you wish for all commits to be squashed?

**Comment by msmith-techempower** [comment]
I don't really have a preference; do whatever you're comfortable with.

**Comment by sagenschneider** [comment]
Ok, .travis.yml updated

**Comment by sagenschneider** [comment]
Please review and merge.

I am aware of the ";charset=UTF-8" not being necessary but this will require a release of OfficeFloor to fix (likely not done in time for March, as in middle of making changes for cloud functionality).  I'll look to have this optimisation available for a later benchmark test.

**Comment by msmith-techempower** [comment]
This actually does not appear to be dependent on #1912 

All tests pass; LGTM!

**Pull request merged**
