### PR TITLE
Go: Updated to 1.5.2 & Added fasthttp benchmark

### PR DESCRIPTION
**Pull request by valyala**
fasthttp is much faster than go's net/http

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@valyala local tests are failing
Logs - http://sprunge.us/OdND

**Comment by valyala** [comment]
Fasthttp requires at least go1.5, while the benchmark uses older Go version (1.4.2) :(

So the following build errors appear:
```
Setup fasthttp: src/github.com/valyala/fasthttp/bytesconv.go:24: date.In(gmtLocation).AppendFormat undefined (type time.Time has no field or method AppendFormat)
Setup fasthttp: src/github.com/valyala/fasthttp/header.go:1171: undefined: bytes.LastIndexByte
Setup fasthttp: src/github.com/valyala/fasthttp/header.go:1496: r.Discard undefined (type *bufio.Reader has no field or method Discard)
Setup fasthttp: src/github.com/valyala/fasthttp/http.go:544: undefined: io.CopyBuffer
Setup fasthttp: src/github.com/valyala/fasthttp/uri.go:257: undefined: bytes.LastIndexByte
Setup fasthttp: src/github.com/valyala/fasthttp/uri.go:269: undefined: bytes.LastIndexByte
```

Is it possible updating go version in the benchmark to [the latest one](https://golang.org/doc/devel/release.html)?

**Comment by msmith-techempower** [comment]
@valyala [This file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/languages/go.sh#L8) should be the one to update to get the latest Go version.

**Comment by valyala** [comment]
@msmith-techempower , done

**Comment by msmith-techempower** [comment]
I see that - this will probably effect all the various Go frameworks - a full Travis run will be required, but because Travis is broken on master, it won't work.

**Comment by valyala** [comment]
Is it possible to manually check all Go frameworks? I did check them few weeks ago on go 1.5.1 - it looks like nothing breaks.

**Comment by valyala** [comment]
BTW, go1.5 has huge latency improvements comparing to go1.4 - see [this article](https://blog.golang.org/go15gc) for details.

**Comment by nbrady-techempower** [comment]
@valyala I am working on testing the Go frameworks now

**Comment by nbrady-techempower** [comment]
@valyala strike that - waiting for #1786 then will complete the tests

**Comment by valyala** [comment]
Go [1.5.2 is out](https://golang.org/doc/devel/release.html#go1.5.minor). It contains [many bugfixes](https://github.com/golang/go/issues?q=milestone%3AGo1.5.2), including the bugfix for [the nasty bug](https://github.com/golang/go/issues/12233). So I updated go version to 1.5.2.

**Comment by msmith-techempower** [comment]
@valyala Can you rebase off of master (or merge master into your branch, if that is easier) just to ensure that you have the latest Travis fixes?

**Comment by valyala** [comment]
@msmith-techempower , done!

**Comment by msmith-techempower** [comment]
Passed all the tests: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/96284048

LGTM!

**Pull request merged**
