### PR TITLE
Grails 2.4.4 upgrade

### PR DESCRIPTION
**Pull request by lhotari**
This pull request upgrades the Grails benchmark to Grails 2.4.4 version.

### CODE REVIEW

**Comment by lhotari** [comment]
@hamiltont Any chance to get this merged before next round of performance tests? What's the current schedule of the next performance test round?

**Comment by hamiltont** [comment]
Doubt it will make it into the preview data, as I think @msmith-techempower has already run that and they are just finalizing the presentation, but if the travis checks pass I'll merge it immediately, and that should get it into the actual R10 run. 

BTW, we're slowly working on removing all the `bash_profile.sh` files, so if you would copy/paste the contents of `bash_profile.sh` into the top of both the `install.sh` and the `setup.sh`, and then delete the `bash_profile.sh` file, that would be helpful :-)

**Comment by lhotari** [comment]
I'm just wondering about the Travis checks that most of them are currently failing. What should I do about that? I'm now re-running only Grails tests in the Travis for my fork: https://travis-ci.org/lhotari/FrameworkBenchmarks/builds/52045999 .

**Comment by lhotari** [comment]
@hamiltont I removed the bash_profile.sh as you instructed. I'm now waiting for the tests for my fork to finish in Travis build https://travis-ci.org/lhotari/FrameworkBenchmarks/builds/52048548 . It's the same as the PR except that has all other tests disabled so that the Travis build executes faster. 

I hope you could merge this PR so that we could see the results in R10 run.

**Comment by hamiltont** [comment]
> I'm just wondering about the Travis checks that most of them are currently failing. What should I do about that? 

it's running all checks because you modified something inside of `toolset/`, and it has to re-check everything when the toolset changes. Many of them are currently failing even in master, so don't worry about the red marks - the only one I'm really caring about is the grails. 

Also, I'm perfectly happy in most PR's accepting a pass result from any travis queue, so if your queue passses happens just link me to the job so I can confirm the result

**Comment by hamiltont** [comment]
Your travis queue passed, and [a quick comparison](https://github.com/lhotari/FrameworkBenchmarks/compare/lhotari:grails-2.4.4-upgrade...grails-changes) shows that the PR branch and the branch you're testing in travis are identical, so we're good! This will definitely be included in R10, it may or may not make it into the R10 preview data - you'll have to check the commit used for the preview data when it's published

**Comment by lhotari** [comment]
@hamiltont Thanks for merging. Ok, that explains the reason why the Travis build started re-running all framework tests. 
The reason I had to modify a file under ```toolset/``` is because ```toolset/setup/linux/frameworks/grails.sh``` has the Grails version number in it.
The changes I made to that file:
https://github.com/TechEmpower/FrameworkBenchmarks/commit/c6073b45#diff-70944edc73963c6776e37be8c73fdbb5L6

I wonder how that could be improved for future updates.

**Comment by hamiltont** [comment]
Yea, I was wondering the same thing. I don't really want to scatter install scripts like grails.sh all over the project and inside frameworks, but at the same time it's annoying to have to re-run all of travis. Once R10 is done I've some plans to (hopefully) make travis substantially faster though, so perhaps this annoyance will be mitigated if travis stops being a 24-hour task ;-)

**Pull request merged**
