### PR TITLE
Improved Flask code

### PR DESCRIPTION
**Pull request by hydratim**
* split app_raw from app
* cleaned app/ORM/SQLAlchemy code
* Rewrote app_raw/raw code from the ground up
* Bumped PyPy from PyPy2 to PyPy3 due to deprecation of Python 2.x
* Migrated from MySQL to PostgreSQL

### CODE REVIEW

**Comment by hydratim** [comment]
Is it possible to re-run the Flask tests on this branch?

**Comment by nbrady-techempower** [comment]
@hydratim started

**Comment by hydratim** [comment]
Awesome, thanks!
It's all passing now as I expected (not just locally).
Is there anything else you need me to do before it can be merged?

**Comment by dbohdan** [comment]
@hydratim Could you review the PonyORM version of the "Fortunes" benchmark for performance bugs? It looks like Flask + ORM "Fortunes" became five times slower between the Round preceding this PR and the one after: https://github.com/TechEmpower/FrameworkBenchmarks/issues/8519#issue-1976322464. This PR is the most significant change during that period. `flask-raw` became faster between the same Rounds.

**Pull request merged**
