### PR TITLE
Improve java setup

### PR DESCRIPTION
**Pull request by hamiltont**
Mostly updates the java setup. The `java7.installed` and `java8.installed` files now contain environment variables, and can be sourced (e.g. `source java7.installed`) to load the proper `JAVA_HOME`, `PATH`, etc. This centralization should help us keep java up to date going forward. 

Also includes a ton of minor fixes that don't belong in other PRs

### CODE REVIEW

**Comment by msmith-techempower** [comment]
I **REALLY** like this notion of sourcing the `.installed` files to set environment variables properly.

Should we consider this the expected way moving forward so that every Python `install.sh` and `setup.sh` don't have the same 3-4 lines at the top and instead only have `source $IROOT/python3.installed`?

**Comment by msmith-techempower** [comment]
OH, OR we add a utility function for that it by name that will print helpful debugging info in error cases and the like:

`fw_source java7` for instance, could do `source $IROOT/java7.installed` in the background, and also print out useful stuff in the case where a user is contributing a new language (or w/e) and their `install.sh` didn't properly call `fw_install java7` at all, so the `$IROOT/java7.installed` doesn't exist.

**Comment by hamiltont** [comment]
We absolutely should. I'm trying to determine if that should just be some new function like `fw_setup`, so that you just run `fw_depends foo` in `install.sh` and then `fw_setup foo` in `bash_profile.sh`, which basically just sources all the *.installed files for you. Thoughts? 

Also, I might have time to get to #1224 today, which should really help your python complaint. I'll just add an install key, so each framework test can manually specify a specific installation file

**Comment by hamiltont** [comment]
Travis LGTM - gained `undertow`, all other Java-based tests stayed the same as on master

**Pull request merged**
