### PR TITLE
Hexagon v0.11

### PR DESCRIPTION
**Pull request by jaguililla**

### CODE REVIEW

**Comment by jaguililla** [comment]
Travis build completed for Hexagon (though other modules failed)

**Comment by nbrady-techempower** [comment]
lgtm @jaguililla thanks! this will be reflected in r14 final

**Comment by jaguililla** [comment]
Thanks! will be R14 anytime soon? like in the next month, or later? Thank you for the great job you are doing!

**Comment by nbrady-techempower** [comment]
@jaguililla R14 previews 1 and 2 have already dropped. R14 final should be any day now. Internally, we have continuous testing up and running like clockwork at the moment so we are hoping for a much faster turn around for the rounds!

**Comment by jaguililla** [comment]
@nbrady-techempower Is there any way to access preview results in order to check possible framework errors?

**Comment by cjnething** [comment]
@jaguililla The results are here: https://www.techempower.com/benchmarks/previews/round14/

**Comment by jaguililla** [comment]
Thanks @cjnething :)

**Pull request merged**
