### PR TITLE
Bump finatra and finagle versions to 20.8.0

### PR DESCRIPTION
**Pull request by bonniee**
Bump finagle to 20.8.0
Bump finatra to 20.8.0

### CODE REVIEW

**Comment by bonniee** [comment]
Re-opening to re-run CI.

**Comment by bonniee** [comment]
The previous builds have failed due to issues finding `util-security_2.12/20.8.0`, however it shows up in Maven Central: https://mvnrepository.com/artifact/com.twitter/util-security_2.12/20.8.0

Let's try again. Apologies for the noise.

**Comment by msmith-techempower** [comment]
I have restarted the jobs, though I don't expect that will resolve anything.

Travis, for reasons, caches stuff even when it claims to have no cached objects.

**Comment by msmith-techempower** [comment]
Okay, nuts to figuring Travis out - it will invalidate that cache *someday*. I pulled your branch locally and am testing; I'll let you know if it passes.

**Comment by msmith-techempower** [comment]
Looks like the download error is real:
image

**Comment by msmith-techempower** [comment]
Hmm, it [does exist on Maven](https://repo1.maven.org/maven2/com/twitter/util-security_2.12/20.8.0/)... looks like they got a bad hash in there somehow.

It's pulling the jar and computing the hash, and it always gets a different one(`c3951e4999498c95e659bdccf1b01ddebd29b251`) from the [published one](https://repo1.maven.org/maven2/com/twitter/util-security_2.12/20.8.0/util-security_2.12-20.8.0.jar.sha1)(`e90666a3e5fd9454606988954d0899ec8d6ae6d6`).

image

**Comment by msmith-techempower** [comment]
Basically, I expect everyone to be running into this problem, not just us. Anyone relying on that jar and a java package manager should be computing the hash and getting a different one than the published one, meaning it cannot be trusted.

I don't think we can do anything until the author is made aware and publishes a fix or a new version.

**Comment by bonniee** [comment]
Thank you for investigating that! I’ll investigate what went wrong with the Maven release.

**Pull request closed without merging**
