### PR TITLE
Clean Fat free code

### PR DESCRIPTION
**Pull request by joanhey**
Use argument unpacking to have less code and be faster.
Format the code.

### CODE REVIEW

**Comment by joanhey** [comment]
@nbrady-techempower  exist a problem creating the mysql docker.

https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/674552551#L772

And the same error when php try to connect:
https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/674552551#L772

**Comment by joanhey** [comment]
I'll try again.

**Comment by joanhey** [comment]
Now passed.
But the error still show creating the mysql docker.
Also in older builds.

**Comment by nbrady-techempower** [comment]
@joanhey 
```
techempower/mysql:latest: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

Comes from the loop before where we test every second whether or not the MySQL server is up and running until we no longer get an error. Shouldn't have any affect on other errors you enouncter.

**Pull request merged**
