### PR TITLE
Vagrant using xenial

### PR DESCRIPTION
**Pull request by nbrady-techempower**
To more accurately reflect the testing environment moving forward, moved vagrant to pull the from ubuntu/xenial instead of trusty. Travis can't run this but I've tested locally:

```
   default: Setting up welcome message
    default: ++ source /etc/profile.d/tfb.sh
    default: + echo 'Setting up welcome message'
    default: + sudo rm -f /etc/update-motd.d/51-cloudguest
    default: + sudo rm -f /etc/update-motd.d/98-cloudguest
    default: + sudo cat
    default: + sudo mv motd /etc/
    default: Setting up client and database machines
    default: + echo 'Setting up client and database machines'
    default: + tfb --init --quiet
    default: + /home/vagrant/FrameworkBenchmarks/toolset/run-tests.py --init --quiet
    default: /usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    default:   """)

C:\Development\fb3\deployment\vagrant>vagrant ssh
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

49 packages can be updated.
15 updates are security updates.
```

```
================================================================================
  Verification Summary

| Test: gemini
|       plaintext     : WARN
|       json          : WARN
================================================================================
```

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
ping @RX14 for libvirt

**Comment by RX14** [comment]
Ideally docker would mean you can just discard vagrant and do everything cleanly as you never touch the host.

I'll do some libvirt testing though.

**Comment by nbrady-techempower** [comment]
I agree @RX14 That will be probably be the case here soon

**Comment by RX14** [comment]
I adjusted the libvirt box, and tested, and it provisioned, but I get this error when trying to run tests:
```
vagrant@TFB-all:~/FrameworkBenchmarks$ tfb --mode verify --test gemini
/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
WARNING:root:results.json for test not found.
fatal: Not a git repository (or any of the parent directories): .git
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
Traceback (most recent call last):
  File "/home/vagrant/FrameworkBenchmarks/toolset/run-tests.py", line 192, in <module>
    sys.exit(main())
  File "/home/vagrant/FrameworkBenchmarks/toolset/run-tests.py", line 189, in main
    return benchmarker.run()
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 133, in run
    self.run_list_test_metadata()
  File "/home/vagrant/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 97, in run_list_test_metadata
    with open(os.path.join(self.full_results_directory(), "test_metadata.json"), "w") as f:
IOError: [Errno 2] No such file or directory: '/home/vagrant/FrameworkBenchmarks/results/20180226153822/test_metadata.json'
```

any idea?

**Comment by nbrady-techempower** [comment]
@RX14 Hmm.. no. Are you on the docker branch when you're doing vagrant up?

**Comment by RX14** [comment]
@nbrady-techempower yes, I checked out this PR.

**Comment by nbrady-techempower** [comment]
Ok thanks, I'll try and reproduce

**Comment by RX14** [comment]
I think it's my fault, there's no write permission to the `results` folder because the permissions are broken. The weird error message is simply because the real error is eaten here: https://github.com/TechEmpower/FrameworkBenchmarks/blob/docker/toolset/benchmark/benchmarker.py?utf8=%E2%9C%93#L249

**Comment by RX14** [comment]
I think I've solved the permissions errors so a PR is incoming.

**Pull request merged**
