### PR TITLE
Update .NET frameworks to .NET 5.0

### PR DESCRIPTION
**Pull request by benaadams**
.NET 5.0 has moved to rc 1 which means it's now officially supported in production

### CODE REVIEW

**Comment by sandeep-eroad** [comment]
> .NET 5.0 has moved to rc 2 which means it's now officially supported in production

should it be rc1?

**Comment by benaadams** [comment]
> should it be rc1?

Yes, clearly I'm living in the future ;)

**Comment by sebastienros** [comment]
We checked this morning to see if you had done it already. Now I understand why it was not here yet 😅

**Comment by benaadams** [comment]
Is now :)

**Comment by nbrady-techempower** [comment]
Woo! Congrats!

**Pull request merged**
