### PR TITLE
use epoll for mojolicious (should other Perl frameworks do so too?)

### PR DESCRIPTION
**Pull request by jberger**
Just a quick config change that should hopefully improve mojolicious performance. If it does so, I feel conscientiously bound to mention that other Perl frameworks might also benefit from the change if done in their `bash_profile.sh` files too.

### CODE REVIEW

**Comment by hamiltont** [comment]
@jberger still working on this one, or can I close it down for now?

**Comment by jberger** [comment]
Travis choked on it last time or I would have encouraged merging it. Give
me a moment to see if the situation is improved or else I will close.

**Comment by hamiltont** [comment]
No worries! BTW, perhaps it would be useful to follow in the footsteps of #1205 and scatter `2>&1 | tee $IROOT/perl-install.log | awk '{ if (NR%100 == 0) printf "."}'` inside of perl.sh, if we can safely assume that the build/install log output of perl is something we're not really interested in seeing fully most of the time

**Comment by jberger** [comment]
OK to merge

**Comment by hamiltont** [comment]
LGTM! Re your comment on IRC:

> because it took 2160 lines just to GET to that point

I know :-( Totally aware that the bash scripts are insanely verbose ATM, see #1124. In my view, fixing this is delayed a bit by #920, which is itself delayed by R10, but it's on my personal wish plate - I don't like linking people to travis and telling them "oh skim until line 5000 something"

**Pull request merged**
