### PR TITLE
update crystal to latest version 0.23.1

### PR DESCRIPTION
**Pull request by drujensen**
This updates crystal to the latest version 0.23.1

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@drujensen there does not seem to be a release at the git location you entered

```
Setup amber: +++fw_get -o crystal-0.23.1-1-linux-x86_64.tar.gz https://github.com/crystal-lang/crystal/releases/download/0.23.1/crystal-0.23.1-1-linux-x86_64.tar.gz
Setup amber: +++curl -sL -o crystal-0.23.1-1-linux-x86_64.tar.gz https://github.com/crystal-lang/crystal/releases/download/0.23.1/crystal-0.23.1-1-linux-x86_64.tar.gz
Setup amber: +++:
Setup amber: +++sleep 30
Setup amber: +++kill 15927
Setup amber: +++trap 'kill $!' SIGTERM
Setup amber: +++fw_untar crystal-0.23.1-1-linux-x86_64.tar.gz
Setup amber: +++echo 'Running '\''tar xf crystal-0.23.1-1-linux-x86_64.tar.gz'\''...please wait'
Setup amber: Running 'tar xf crystal-0.23.1-1-linux-x86_64.tar.gz'...please wait
Setup amber: +++tar xf crystal-0.23.1-1-linux-x86_64.tar.gz
Setup amber: tar: This does not look like a tar archive
```

**Comment by RX14** [comment]
The problem is that the package release number this time is `3` not `1`.

**Comment by drujensen** [comment]
@RX14 @nbrady-techempower @sdogruyol I fixed the package to `3` and ran in the vagrant instance to verify this worked.  Should be fixed now.

@nbrady-techempower is there a way to update to llvm to 3.9?  If not, we will need to add a flag to all the crystal projects so they will compile.  `--no-debug`

**Comment by RX14** [comment]
@drujensen no, you'll need to use the `--no-debug` workaround.

**Comment by drujensen** [comment]
@RX14 ok, thx.  I created https://github.com/TechEmpower/FrameworkBenchmarks/pull/2966 for all 3 projects.

**Comment by drujensen** [comment]
@RX14 moved them over here since they are dependent on this update.

**Comment by faustinoaq** [comment]
@drujensen @sdogruyol I think we should update crystal & crystal-frameworks synchronously

1. Ensure crystal is [latest version](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/languages/crystal.sh#L7)
2. [All crystal test](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/.travis.yml#L40) should be updated both `shard.yml` and `shards.lock` to avoid [shards update error](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2959#issuecomment-328372803). Well, thats reason why `!.shard.lock` is in our `.gitignore`
3. If a framework/library is removed ensure to modify `.travis.yml` too.

So, I think with these steps we can avoid dependent PR like:

- https://github.com/TechEmpower/FrameworkBenchmarks/pull/2959
- https://github.com/TechEmpower/FrameworkBenchmarks/pull/2953

**Comment by drujensen** [comment]
@faustinoaq both will be merged quickly and shards are not dependent on the language upgrade.  No need to hold this up. 

@nbrady-techempower I believe this is ready to go.

**Pull request merged**
