### PR TITLE
make changes for EvHttp-sharp to use bash setup script and updated mono

### PR DESCRIPTION
**Pull request by lgratrix-techempower**
fix EvHttp-sharp

### CODE REVIEW

**Comment by hamiltont** [comment]
This fixed evhttp, but I think your commit includes some of the work from #1287 without providing credit to @pdonald - perhaps you could redo this and ensure that his commits are present in the pull request? that will also make it possible to merge both PRs into master without git thinking that they conflict

**Comment by msmith-techempower** [comment]
I can handle the merge conflicts manually, and there's a problem with `xsp` from @pdonald 's commit that I want fixed up before merging it in.

**Comment by hamiltont** [comment]
Coolio, we should be sure to merge from pdonald first to give him credit for the mono fixes, or build the final fix for that URL problem as a commit on top of his commits

**Comment by msmith-techempower** [comment]
Agreed - I want pdonald to get the credit, but I'm not yet comfortable merging his PR and I wanted other mono frameworks to be able to move forward.

**Comment by LadyMozzarella** [comment]
Commits from #1287 have been merged, ready for an update.

**Pull request closed without merging**
