### PR TITLE
aah framework updated to latest release v0.8

### PR DESCRIPTION
**Pull request by jeevatkm**
- app updated to use latest aah release v0.8
- fixed TFB Host header issue

### CODE REVIEW

**Comment by jeevatkm** [comment]
Is there an issue with travis build setup/config?
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/262574353

I have verified the changes in `Vagrant VM` before creating this PR, was all green. Please let me know, what I have to do.

**Comment by jeevatkm** [comment]
@nbrady-techempower can you please have a look and shed some light on travis error?

**Comment by jeevatkm** [comment]
`setup.sh` has issues, I have updated it. This PR required to be merged before benchmark test run.

Please let me know, if anything needed from my end.

**Comment by jeevatkm** [comment]
Any updates?

**Comment by nbrady-techempower** [comment]
@jeevatkm Thanks for the PR. Unfortunately resources are tight at the moment. We have to address the MySQL travis issue before we can start merging. We should be able to review this shortly.

**Comment by jeevatkm** [comment]
@nbrady-techempower Okay understood, thank you.

**Comment by jeevatkm** [comment]
Vagrant VM verify results:
```
Server aah: Framework processes have terminated
verify: 100% |####################################################################################################################################################################| Rough Time: 00:02:34
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
WARNING:root:Framework http4k does not define a default test in benchmark_config.json
================================================================================
  Verification Summary

| Test: aah
|       fortune       : PASS
|       plaintext     : PASS
|       db            : PASS
|       update        : PASS
|       json          : PASS
|       query         : PASS
================================================================================

Time to complete: 156 seconds
Results are saved in /home/vagrant/FrameworkBenchmarks/results/20170903002853
vagrant@TFB-all:~/FrameworkBenchmarks$
```

**Comment by jeevatkm** [comment]
Thank you @nbrady-techempower

**Pull request merged**
