### PR TITLE
Benchmarking http://micronaut.io/ framework

### PR DESCRIPTION
**Pull request by jringuette**
Hi, here is a submission for the micronaut java framework.

### CODE REVIEW

**Comment by graemerocher** [comment]
Please do not merge, we will be providing an official pull request for this in the future. See https://github.com/micronaut-projects/micronaut-core/issues/215#issuecomment-400764982

@jringuette thanks for going through the effort, but I think the framework authors are probably best placed to provide this. We can maybe use some of your pull request as a base, as we had not yet implemented the SQL db based tests.

**Comment by nbrady-techempower** [comment]
Thanks for the work and communication here. Closing due to @graemerocher's request

**Comment by acmeguy** [comment]
@graemerocher  when do you think that will be? (I'm evaluating Micronaut for a project)

**Comment by graemerocher** [comment]
@acmeguy A PR was merged on the 20th of July https://github.com/TechEmpower/FrameworkBenchmarks/pull/3941

Now it is matter of waiting for the next round of results I guess.

**Comment by jringuette** [comment]
You can already see the results in the daily/weekly runs that are done on the master branch here https://tfb-status.techempower.com/

Look for the latest [Citrine](https://www.techempower.com/benchmarks/#section=test&runid=a0d6e357-e8e3-4a5b-9ef0-6175ed824b20) run, you will see micronaut's results.

**Pull request closed without merging**
