### PR TITLE
Add easyjson marshallers

### PR DESCRIPTION
**Pull request by dcu**
It should improve performance when working with JSON.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @dcu - Since all the test implementations are now converted to docker, we're not going to be merging anything else into master. Could you target the `docker` branch with this change? Let me know if you don't follow how it works, and I'll try and incorporate the change there for you.

**Comment by dcu** [comment]
@nbrady-techempower I cherry picked my change but it seems the tests aren't running, can you check?

**Comment by dcu** [comment]
@nbrady-techempower thanks, looks like it worked

**Comment by nbrady-techempower** [comment]
@dcu looks good! merging

**Comment by dcu** [comment]
@nbrady-techempower is there a way to run the benchmark to see the results?

**Comment by nbrady-techempower** [comment]
@dcu keep an eye on https://tfb-status.techempower.com/ it should be included in the next full run

**Pull request merged**
