### PR TITLE
Vapor 2

### PR DESCRIPTION
**Pull request by kimdv**
Made new pull request because of some major changes.

### CODE REVIEW

**Comment by kimdv** [comment]
@nbrady-techempower it seems like more frameworks fails here. Should this be ignored?

But there is still some problems with vapor.

**Comment by nbrady-techempower** [comment]
Those other frameworks can be ignored.

it looks like it's complaining about `cmysql` and `ctls` dependencies? do these need to be added in the setup.sh file? `fw_depends cmysql ctls` ?

**Comment by kimdv** [comment]
I think it depends on it, if I remember correct, I installed it via home-brew when I started on Vapor developing. 

Should I just add them in them like this

```
#!/bin/bash

fw_depends swift3 mongodb mysql postgresql cmysql  ctls

swift build -Xswiftc -DNOJSON -c release

.build/release/vapor-tfb-mysql --env=production &
```

**Comment by nbrady-techempower** [comment]
Yeah right there is where you want to do it

**Comment by kimdv** [comment]
Currently waiting for the Vapor team to implement this: [#267](https://github.com/vapor/fluent/issues/267)

**Comment by nbrady-techempower** [comment]
@kimdv How's this looking? Gonna throw the WIP flag on it for now. Let us know if there's anything we can do if you're having toolset trouble.

**Comment by kimdv** [comment]
@nbrady-techempower I'm still waiting on some feedback from from the Vapor team. 

Current the preparation methods creates a db called "fluent". I have filled an issue on GitHub that will prevent that, but I think they are busy at WWDC :)

**Comment by nbrady-techempower** [comment]
Ah, yes, makes sense!

**Comment by kimdv** [comment]
@nbrady-techempower The vapour team have made the fixes, and everything passes on my local machine using Vagrant. But the tests fails on Travis. Can you see what's wrong ? :)

**Comment by nbrady-techempower** [comment]
Thanks @kimdv 

It's not immediately clear to me what's wrong in travis. So I will pull and test locally this afternoon and see what I can find.

**Pull request merged**
