### PR TITLE
ASP.Net Core add platform dataupdates

### PR DESCRIPTION
**Pull request by benaadams**
Bringing aspnetcore platform in line with Mono improvements

/cc @sebastienros

### CODE REVIEW

**Comment by sebastienros** [comment]
Should be top 10 in updates after this PR.

**Comment by sebastienros** [comment]
This is failing because of Nancy

**Comment by benaadams** [comment]
`The specified framework 'Microsoft.AspNetCore.App', version '2.1.0-rc1-final' was not found.`

Is what you get for specifying a version and then you making a release :)

**Comment by benaadams** [comment]
@nbrady-techempower is it possible to get this merged before next run? 

It also fixes the `nancy-netcore` framework which will be otherwise be broken due to a docker image update

**Pull request merged**
