### PR TITLE
Implemented vibed for a master release

### PR DESCRIPTION
**Pull request by msmith-techempower**
This should get it working on master while I work on #1605

### CODE REVIEW

**Comment by mcocciaTE** [comment]
I get a lot of merge conflicts when I try and pull when on the vibed branch. It looks like on github it can auto merge into master though so I'm not sure why it is failing to locally.

**Comment by msmith-techempower** [comment]
Have you pulled your master branch lately? I have merged in like like 10 PRs today

**Comment by mcocciaTE** [comment]
I did a git reset --hard to pull from master when it didn't work and it did not fix it :/ It still says "Your branch and 'origin/vibed' have diverged, and have 58 and 176 different commits each, respectively"

**Comment by msmith-techempower** [comment]
AHHHH, there was a `vibed` branch which I merged in to a different branch before.

Delete your `vibed` branch, then `git remote update --prune origin` on latest master, then you should be able to pull the new `vibed`.

**Comment by mcocciaTE** [comment]
Ahhh there we go. Working for me locally. Probably worth of a LGTM label now.

**Comment by mcocciaTE** [comment]
Oh I didn't see there was one already

**Comment by msmith-techempower** [comment]
Well, travis said `vibed` passed: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/66235814

LGTM!

**Pull request merged**
