### PR TITLE
feat: Upgrade ASP.NET Core benchmarks to .NET 8

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Upgrades to .NET 8.

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
cc @sebastienros

**Comment by ShreyasJejurkar** [comment]
Surprisingly, the mono pipeline is failing with a compilation error. 
https://github.com/TechEmpower/FrameworkBenchmarks/actions/runs/6922176168/job/18828604783#step:9:144

cc @vargaz @MichalStrehovsky

image

**Comment by NinoFloris** [comment]
Please upgrade Npgsql to 8.0 as well!

**Comment by ShreyasJejurkar** [comment]
> Please upgrade Npgsql to 8.0 in minimal as well!

ohh I missed that. Thanks, upgraded.

**Comment by ShreyasJejurkar** [comment]
Pinging @sebastienros again for the review. :)

**Review by sebastienros — APPROVED** [review]

**Comment by ShreyasJejurkar** [comment]
@nbrady-techempower Pinging again, in case you missed it.

**Comment by NinoFloris** [comment]
We've just released Npgsql 8.0.1 which contains some important fixes https://www.nuget.org/packages/Npgsql/8.0.1 

Nothing directly applicable to the TE scenarios as far as I can tell. However as the PR is still open I'd recommend bumping the version just in case.

**Comment by ShreyasJejurkar** [comment]
> We've just released Npgsql 8.0.1 which contains some important fixes https://www.nuget.org/packages/Npgsql/8.0.1
> 
> Nothing directly applicable to the TE scenarios as far as I can tell. However as the PR is still open I'd recommend bumping the version just in case.

Done. Thanks. :)

**Comment by sebastienros** [comment]
cc'ing [NateBrady23](https://github.com/NateBrady23)

**Comment by ShreyasJejurkar** [comment]
cc @NateBrady23

**Pull request merged**
