### PR TITLE
update s-server to version 2.2

### PR DESCRIPTION
**Pull request by woshilaiceshide**
update the s-server jar to version 2.2, which is optmized based on the previous version.

### CODE REVIEW

**Comment by ashawnbandy-te-tfb** [comment]
@woshilaiceshide Does this differ from PR #2305 other than the target branch?

**Comment by woshilaiceshide** [comment]
@ashawnbandy-te-tfb , yes, this pr is the same as #2305 other than the target branch.

**Comment by ashawnbandy-te-tfb** [comment]
@woshilaiceshide Could we close this PR then?  We're wrapping up round 13 and will begin reviewing round 14 shortly.

**Comment by woshilaiceshide** [comment]
@ashawnbandy-te-tfb just closed

**Pull request closed without merging**
