### PR TITLE
[JavaScript] Add uWebSockets.js

### PR DESCRIPTION
**Pull request by UnlimitedBytes**

### CODE REVIEW

**Comment by UnlimitedBytes** [comment]
@msmith-techempower @hamiltont @nbrady-techempower @pfalls-techempower @joanhey @methane

**Comment by xeoneux** [comment]
Would love to see this benchmark!

**Comment by xeoneux** [comment]
When will this merge?

**Comment by cirospaciari** [comment]
uWebSockets author don't posts benchmarks here (and is highly oppose to posting here), the only really valid benchmark at some degree is plaintext, other benchmarks will only be benchmaking json and db libs. That's why i only posted under the name of socketify.py and only plain and json (to highlight PyPy3 over Python3 lib) benchmarks.

**Comment by cirospaciari** [comment]
@UnlimitedBytes in version v20.14.0 [Latest](https://github.com/uNetworking/uWebSockets.js/releases/latest) You don't need to write manually the Date header anymore

**Comment by nbrady-techempower** [comment]
@xeoneux please remove the .editorconfig and .prettierrc files from this PR and I'll merge

**Comment by nbrady-techempower** [comment]
@UnlimitedBytes please remove the .editorconfig and .prettierrc files from this PR and then it looks good

**Comment by nbrady-techempower** [comment]
Looks like this still needs some work. Please re-open when you have a chance to update.

**Comment by ReneWerner87** [comment]
@UnlimitedBytes can you reopen the pr and adjust the mention files

**Pull request closed without merging**
