### PR TITLE
make deno runnable

### PR DESCRIPTION
**Pull request by qballer**
The Deno example wasn't runnable I've made it so. I've also run `deno fmt` to keep it with the community standard

### CODE REVIEW

**Comment by qballer** [comment]
@nbrady-techempower @msmith-techempower is it possible to run CI on this?

**Comment by nbrady-techempower** [comment]
@qballer Most certainly!

**Comment by qballer** [comment]
thanks, I really want to see the benchmark results on this. :)

**Comment by qballer** [comment]
didn't run `/tfb --mode verify --test deno-mongodb-raw`, fixing..

**Comment by nbrady-techempower** [comment]
@qballer Just ping me when you need this run again. I don't get notifications for that.

**Comment by qballer** [comment]
thanks, I will do that. It could be the case that I found a bug in Deno. Trying to find out with the Deno folks

**Comment by nbrady-techempower** [comment]
Feel free to reopen this if you have a chance to work on it. There's another attempt at fixing the deno tests too, but going to close both for now.

**Pull request closed without merging**
