### PR TITLE
use snake_case for function names in iron

### PR DESCRIPTION
**Pull request by steveklabnik**
This is more idiomatic Rust.

### CODE REVIEW

**Comment by steveklabnik** [comment]
This failure seems unrelated.

**Comment by msmith-techempower** [comment]
@steveklabnik Looks like you need to rebase from our latest master for Travis to test this properly.

**Comment by steveklabnik** [comment]
Will do.

**Comment by msmith-techempower** [comment]
@steveklabnik Looks like there was an error: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/96127834

**Comment by steveklabnik** [comment]
Ah, this change is unrelated to my fix, actually. It's due to the dependencies resolving in an incompatible way.

I don't have time to fix this right now, so I'll just give it a close. In the future, others will end up with this error and need to fix it though.

**Pull request closed without merging**
