### PR TITLE
Mitol server tests for NodeJS framework

### PR DESCRIPTION
**Pull request by Helidium**
Hi,

I have prepared additional tests for the NodeJS framework, using a Mitol server.

Thank you,

### CODE REVIEW

**Comment by Helidium** [comment]
Hi @nbrady-techempower, I have prepared the tests as discussed.
I have changed the helper.js, to add headers without writing head, you can see the diff.

Please let me know if there is anything else that needs to be done.

Thank you,

**Comment by nbrady-techempower** [comment]
@Helidium wow you're fast! Looks good! Would you mind adding some information about Mitol to the `README.md`?

**Comment by Helidium** [comment]
@nbrady-techempower I have updated the readme.md file. Can you check it out, if it's ok?

Thank you

**Comment by nbrady-techempower** [comment]
@Helidium Looks good, thanks!

**Comment by Helidium** [comment]
@nbrady-techempower Is it possible to merge in this round window?

Thank you,

**Comment by nbrady-techempower** [comment]
@Helidium If I do that, and it makes it in, you won't have a chance to make any modifications. The data will be posted. If that's ok with you, I can merge it in. I'd prefer that new implementations get a chance to see preview data.

**Comment by Helidium** [comment]
@nbrady-techempower Yes, please do merge the PR. Thank you

**Pull request merged**
