### PR TITLE
Do not apt-get upgrade

### LINKED ISSUE #1139: Remove apt-get upgrade from setup scripts
Presumably someone can install a fresh 14.04 image, run `toolset/run-tests.py --install server`, and be sitting on a machine that is configured to run a round. Running apt-get upgrade makes this a lot harder to achieve, and I'm not convinced it offers any tangible benefit. While not running upgrade doesn't offer any guarantees, it reduces the range of differences between two machines from "all possible packages" to "packages that TFB explicitly installs".

Thoughts?

### LINKED ISSUE #1369: Installation's apt-upgrade causes postgres errors
When running the prerequisite installation, the command `sudo apt-get -yq upgrade -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold` tries to update all the postgres versions, which causes lots of error output because once the first postgres version is started none of the others can start. 

This appears to also cause errors to be returned from subsequent apt commands as dpkg attempts to recover from it's prior issue. 

```
Setting up postgresql-client-common (166.pgdg12.4+1) ...
Setting up postgresql-client-9.2 (9.2.10-1.pgdg12.4+1) ...
Setting up postgresql-common (166.pgdg12.4+1) ...
 * Starting PostgreSQL 9.3 database server
   ...done.
Setting up postgresql-9.2 (9.2.10-1.pgdg12.4+1) ...
Refused to start PostgreSQL 9.2, because PostgreSQL 9.3 is currently running! You should first stop 9.3 instance...
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing postgresql-9.2 (--configure):
 subprocess installed post-installation script returned error exit status 13
dpkg: dependency problems prevent configuration of postgresql-contrib-9.2:
 postgresql-contrib-9.2 depends on postgresql-9.2 (= 9.2.10-1.pgdg12.4+1); however:
  Package postgresql-9.2 is not configured yet.
dpkg: error processing postgresql-contrib-9.2 (--configure):
 dependency problems - leaving unconfigured
Setting up postgresql-client-9.4 (9.4.1-1.pgdg12.4+1) ...
No apport report written because the error message indicates its a followup error from a previous failure.
Setting up postgresql-9.4 (9.4.1-1.pgdg12.4+1) ...
Refused to start PostgreSQL 9.4, because PostgreSQL 9.3 is currently running! You should first stop 9.3 instance...
invoke-rc.d: initscript postgresql, action "start" failed.
dpkg: error processing postgresql-9.4 (--configure):
 subprocess installed post-installation script returned error exit status 13
dpkg: dependency problems prevent configuration of postgresql-contrib-9.4:
 postgresql-contrib-9.4 depends on postgresql-9.4 (= 9.4.1-1.pgdg12.4+1); however:
  Package postgresql-9.4 is not configured yet.
dpkg: error processing postgresql-contrib-9.4 (--configure):
 dependency problems - leaving unconfigured
Setting up postgresql-client (9.4+166.pgdg12.4+1) ...
No apport report written because MaxReports is reached already
<snip>
Errors were encountered while processing:
 postgresql-9.2
 postgresql-contrib-9.2
 postgresql-9.4
 postgresql-contrib-9.4
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### PR DESCRIPTION
**Pull request by hamiltont**
Increases stability of our scripts by avoiding unexpected upgrades

Fixes #1369 
Fixes #1139

### CODE REVIEW

**Comment by msmith-techempower** [comment]
Will this leave us in the 'never ran upgrade' position?

**Comment by hamiltont** [comment]
More like a "Only run upgrade manually" situation - the problem is that automatic upgrade of all software on the machine has big implications, and often creates complex problems. This upgrade has causes issues in Travis with mongodb, rsyslog, and postgres, and they are annoyingly complex issues (like upgrade seems to re-install the postgres version that we expressly uninstalled, then try and start it, which fails because an older version is running or something crazy like that)

**Comment by hamiltont** [comment]
Basically, if a human is there to understand what to do when apt-get upgrade fails and dpkg starts refusing to do anything more, then sure you can upgrade. Otherwise....it's a PITA

**Comment by LadyMozzarella** [comment]
[Travis build](https://travis-ci.org/LadyMozzarella/FrameworkBenchmarks/builds/56947388) - not yet started as of this commit.

**Comment by hamiltont** [comment]
This one was actually [scheduled correctly](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/56821392) on the main queue. I think a lot of them were (see [here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/pull_requests)) they just were not hyperlinked from the pull requests because travis didn't have write permission on the organization

**Comment by LadyMozzarella** [comment]
whoops- thanks @hamiltont

**Comment by hamiltont** [comment]
So travis finished, and the only two differences from the latest full build on master are `Haskell/yesod` and `JavaScript/nodejs`. NodeJS started passing (yay!), and yesod started failing with this: 

```
attoparsec-0.12.1.5 failed during the building phase. The exception was:
ExitFailure 9
This may be due to an out-of-memory condition.
bench-0.0.0 depends on attoparsec-0.12.1.5 which failed to install.
```

`Scala/scruffy` started failing, but that turns out to actually be true (master just hadn't caught up to the failure yet - see #1481). 

I'm hoping to merge this, thoughts?

**Comment by hamiltont** [comment]
As an added bonus, this drops about 2 hours off the total travis build time :-P

**Comment by msmith-techempower** [comment]
`cabal` (the package manager for `haskell`) often runs out of memory in the Travis environment. I would suggest pulling and testing on a VM with a bit more RAM and proving it is a false-positive.

**Comment by methane** [comment]
@msmith-techempower See #1117

**Comment by hamiltont** [comment]
Sadly, I have confirmed that `yesod` is indeed broken in master, and that is not just an effect of removing `apt-get upgrade`. Confirmed via travis and virtualbox. 

So the only test affected by this PR appears to be nodejs, which now passes.

**Pull request merged**
