### PR TITLE
http4k v5 upgrade and new servers

### PR DESCRIPTION
**Pull request by daviddenton**

### CODE REVIEW

**Comment by daviddenton** [comment]
@nbrady-techempower this has passed the checks but it doesn't look like they were run properly?

**Comment by nbrady-techempower** [comment]
@daviddenton Yeah, the diff checker isn't working quite right yet. Still working on some fixes today.

**Comment by nbrady-techempower** [comment]
@daviddenton Can you bump this to trigger a run

**Comment by daviddenton** [comment]
This is now green and ready to merge! Thanks for the work on the Python stuff @nbrady-techempower 😄

**Pull request merged**
