### PR TITLE
Fixes a conflict with the Windows file system.

### PR DESCRIPTION
**Pull request by KevinBrogan**
Fixing a bug that makes it impossible to checkout source code on a windows file system.

aux is a reserved keyword

### CODE REVIEW

**Comment by knewmanTE** [comment]
Were you able to test this locally with the changes and get it to run successfully? When running locally on a fork of your branch, I am getting the following error:
```
Setup fasthttp: can't load package: package templates: no buildable Go source files in 
/home/techempower/FrameworkBenchmarks/frameworks/Go/fasthttp/src/templates
```

Is it possible that the aux file is a requirement for fasthttp to run properly?

**Comment by KevinBrogan** [comment]
damn it, I typoed the renamed file location. missed the templates directory.

**Comment by KevinBrogan** [comment]
I don't have a working copy on my machine yet. Had to get the source on it first, which is impossible until this rename is completed.

**Comment by knewmanTE** [comment]
@KevinBrogan no worries! It looks like it's doing okay on Travis, so as long as it passes on Travis we should be okay to merge this in.

**Comment by knewmanTE** [comment]
Looks like that fix did the trick. Merging in!

**Comment by KevinBrogan** [comment]
Thanks!

**Pull request merged**
