### PR TITLE
add framework akka-http 1.0-RC2

### PR DESCRIPTION
**Pull request by sxend**
add akka-http framework with MySQL http://doc.akka.io/docs/akka-stream-and-http-experimental/1.0-RC2/
  
### build
```
cd frameworks/Scala/akka-http
sbt assembly
```
### run
```
java -server -jar target/scala-2.11/akka-http-benchmark.jar
```
### endpoint
- http://127.0.0.1:9000/plaintext
- http://127.0.0.1:9000/json
- http://127.0.0.1:9000/db
- http://127.0.0.1:9000/fortunes
- http://127.0.0.1:9000/queries?queries=
- http://127.0.0.1:9000/updates?queries=100

### CODE REVIEW

**Comment by msmith-techempower** [comment]
Can you add `aka-http` to the `.travis.yml` file in the root of the project so Travis-CI will automatically test this?

**Comment by sxend** [comment]
@msmith-techempower rebasing on master and, added .travis.yml configuration. PTAL :)

**Comment by sxend** [comment]
@msmith-techempower rebase, and registered .travis.yml. PTAL

**Comment by msmith-techempower** [comment]
Looks good! LGTM!

**Pull request merged**
