### PR TITLE
update Tornado from 5.1.1 to 6.0

### PR DESCRIPTION
**Pull request by MioYvo**
New big version of Tornado has been released. Some changes may improve performance.

https://www.tornadoweb.org/en/stable/releases/v6.0.0.html

### CODE REVIEW

**Comment by MioYvo** [comment]
error details from travis-ci :
```
  File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 14, in <module>
    from psutil import virtual_memory
ImportError: No module named psutil
```
Seems tools of tfb is broken.

**Comment by MioYvo** [comment]
Maybe we need to rebuild and upload a new image [techempower/tfb:latest](https://hub.docker.com/r/techempower/tfb) to dockerhub to make #4494 effective.

**Comment by nbrady-techempower** [comment]
Yeah this is our mistake. We're actually not using dockerhub for the image anymore. Fix incoming; thanks.

**Comment by nbrady-techempower** [comment]
@MioYvo You can merge in the current master branch to fix the travis issues

**Comment by MioYvo** [comment]
I did a wrong git merge and push.Close this PR. Sorry.

**Pull request closed without merging**
