### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by nbrady-techempower**
Updated readme to include `tfb` command and removed `Issues Stats` badges, which are either really slow to load and old, or broken.

### CODE REVIEW

**Comment by cjnething** [comment]
I just went to the Issue Stats page and it seems to be loading fine. Perhaps it was just down when you went to check it?

**Comment by nbrady-techempower** [comment]
@cjnething You can see the image loading in our README on the front page?

**Comment by cjnething** [comment]
Yes, I can

**Comment by nbrady-techempower** [comment]
Hmm, weird. I always get this:

**Pull request merged**
