### PR TITLE
Java Servlet + DSL model

### PR DESCRIPTION
**Pull request by zapov**
DSL client java for JSON serialization
PostgreSQL

### CODE REVIEW

**Comment by zapov** [comment]
I've removed the database part.
That should resolve all the issues!?

When TE decides on the rules we can look into adding those parts back.

**Comment by msmith-techempower** [comment]
It seems that this was not tested by Travis. Please add `    - "TESTDIR=Java/servlet-dsl" (alphabetical ordering please) to `.travis.yml` and push that change to your branch.

**Comment by zapov** [comment]
Ouch. Sorry about that. Added.

**Comment by msmith-techempower** [comment]
No problem - we'll wait and see what Travis says.

**Comment by msmith-techempower** [comment]
Travis agrees - LGTM!

**Pull request merged**
