### PR TITLE
Issue #1947: postgresql: set synchronous_commit to off

### PR DESCRIPTION
**Pull request by valyala**
Disable synchronous commits in postgresql as discussed at #1947 .

### CODE REVIEW

**Comment by valyala** [comment]
FYI, this PR already [passed travis tests](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/116054555). After that I updated comments in the postgresql.conf, so new test has been queued.

**Comment by valyala** [comment]
@msmith-techempower , could you cancel [this](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/116054856) and [this](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/116054856) test, since they are useless now and only occupies travis resources?

**Comment by valyala** [comment]
Ping. The PR passes tests - see https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/116054555 .

**Comment by msmith-techempower** [comment]
We have an agreement; LGTM!

**Pull request merged**
