### PR TITLE
[ci fw-only Java/act] Docker act 1.8.1

### PR DESCRIPTION
**Pull request by greenlaw110**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@greenlaw110 If you pull in the most recent `docker` branch changes, you should get the updated travis stuff for faster runs. That might also take care of the Rust stuff that's showing up here, but if not, would you mind removing it.

**Comment by greenlaw110** [comment]
@nbrady-techempower how can I get the upstead travis? I just fetched upstream/docker and there is no .travis.yml file change:

```
Merge made by the 'recursive' strategy.
 benchmark.cfg.example               |  1 -
 toolset/benchmark/benchmarker.py    | 28 ++++++++++++++++++++--------
 toolset/benchmark/framework_test.py | 43 +++++++++++++++++++++++++++++++++++++------
 toolset/utils/database_helper.py    | 40 ++++++++++++++++++++++++++++++++++++++++
 toolset/utils/docker_helper.py      | 30 ++++++++++++++++++++++++------
```

**Comment by nbrady-techempower** [comment]
Ah, you do have the changes. The problem is the travis differ sees all the merge commits in the log and thinks there has been a core toolset change. `[ci fw-only Java/act]` should work fine now but it has to be in the most recent commit message

**Comment by greenlaw110** [comment]
@nbrady-techempower thanks for the `[ci fw-only Java/act]` tip. I found the CI failed with the following error log:

```
--------------------------------------------------------------------------------
  Running Test: act-hibernate-pgsql
--------------------------------------------------------------------------------

Process Test Runner (act-hibernate-pgsql):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/benchmarker.py", line 387, in __run_test
    result = test.start(out, database_container_id)
  File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 62, in start
    result = docker_helper.build(self.benchmarker_config, [self.name], out)
  File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 60, in build
    os.path.join(test.directory, test_docker_file)))))
  File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 325, in __gather_dependencies
    deps.extend(__gather_dependencies(dep_docker_file))
  File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 305, in __gather_dependencies
    if os.path.exists(docker_file):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
Do you see what's the problem?

**Comment by nbrady-techempower** [comment]
@greenlaw110 The problem is here https://github.com/actframework/FrameworkBenchmarks/blob/f15bcaa216bf2072040c537e1bed634a0bc96fb5/frameworks/Java/act/act-hibernate-pgsql.dockerfile#L1

it should be `tfb/act-base:latest` now

@msmith-techempower see stack trace above. I thought you captured this in a PR.

**Comment by greenlaw110** [comment]
@nbrady-techempower thanks. My mistake again

**Comment by greenlaw110** [comment]
@nbrady-techempower can this PR be merged?

**Comment by nbrady-techempower** [comment]
@greenlaw110 just remove that rust file and ill merge this in

**Comment by greenlaw110** [comment]
@nbrady-techempower sorry what rust file do you mean?

**Comment by nbrady-techempower** [comment]
If you look at the files changed tab here, you're reintroducing `frameworks/Rust/may-minihttp/setup.sh`

**Comment by greenlaw110** [comment]
@nbrady-techempower the file `frameworks/Rust/may-minihttp/setup.sh` has been removed.

**Comment by greenlaw110** [comment]
thanks @nbrady-techempower

**Pull request merged**
