### PR TITLE
Using latest maven version

### PR DESCRIPTION
**Pull request by sagenschneider**

### CODE REVIEW

**Comment by sagenschneider** [comment]
Note the $IROOT/maven.installed file will need to be deleted for the later maven version to be installed.

**Comment by msmith-techempower** [comment]
I am not sure why this is necessary; #1911 passed all tests without this being merged in.

**Comment by sagenschneider** [comment]
Yes, I realised I had put in a fix within the OfficeFloor plug-ins to avoid this issue (flag that turns of the functionality, as was not necessary for this test).  Hence now working.

I will leave it to you, as to whether a later version of Maven is worth the risk of introducing.

**Comment by msmith-techempower** [comment]
Thanks for the explanation - I am in favor of leaving this until it is necessary.

**Pull request closed without merging**
