### PR TITLE
Modernize haskell benchmarks

### PR DESCRIPTION
**Pull request by saturday06**
- Use stack on snap, wai
- Update LTS Haskell to 6.2
- Adapt content-type to benchmarker's requirement

### CODE REVIEW

**Comment by saturday06** [comment]
`toolset/setup/linux/languages/haskell.sh` is no longer needed but it doesn't be removed to make travis happy.

**Comment by saturday06** [comment]
I'll create separated PR to remove that haskell.sh.

**Comment by nbrady-techempower** [comment]
Hi @saturday06 we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by saturday06** [comment]
🆗

**Comment by nbrady-techempower** [comment]
Thanks!

**Pull request closed without merging**
