### PR TITLE
Use Wildfly 9.0.0.Beta2

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by LadyMozzarella** [comment]
Wildfly is failing for me with this PR. Looks like the [version directory in the setup.sh script](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/wildfly-ee7/setup.sh#L6) needs to be updated to 9.0.0.Beta2 as well.

**Comment by stuartwdouglas** [comment]
Should be fixed now

**Comment by LadyMozzarella** [comment]
Travis-CI says Wildfly looks good, but the changes are causing Undertow to fail. Did you intentionally add those changes on your last commit?

**Comment by stuartwdouglas** [comment]
Sorry, that was unintentional.

**Pull request merged**
