### PR TITLE
[ci fw-only Java/act] Act: use act release version

### PR DESCRIPTION
**Pull request by greenlaw110**

### CODE REVIEW

**Comment by zloster** [comment]
I have **NO** idea why commit in my cloned repository will show up here.

**Comment by nbrady-techempower** [comment]
@zloster I'm a bit confused as I've only seen the proper behavior. The commit that references this PR has the PR # in the commit message doesn't it?

**Comment by zloster** [comment]
@nbrady-techempower Yes, it does.

I've just noticed that the commit in my master has different hash and parent: https://github.com/zloster/FrameworkBenchmarks/commit/9a7c9d3cafa5466b929c9868afbeac26c1706e97
than the merged one in TechEmpower's master: https://github.com/TechEmpower/FrameworkBenchmarks/commit/5a3fae7c7b33bd39050147aacf88182e1da49557

Yet these two are exactly the same commit. And my master synced today is EVEN with TechEmpower's one: https://github.com/TechEmpower/FrameworkBenchmarks/compare/master...zloster:master

**Comment by zloster** [comment]
@nbrady-techempower One possible explanation is that somehow I've rewritten the history in the branch about the Servlets: https://github.com/TechEmpower/FrameworkBenchmarks/commit/547ab2dae1b2c0280ac1091b2d9a396502dd4bf3 The affected pull requests are just before my commit.
Then this PR gets merged, I'm syncing my master and everything seems fine?

**Comment by greenlaw110** [comment]
no idea what's happening to your branch. Here is what I've done to submit the PR:

1. create the feature (in this case: `act-use-act-release-version`) in my fork
2. implement my changes
3. test locally and commit my changes and push to my fork and get it passed the travis-ci tests
4. `git co master && git fetch upstream && git merge upstream/master`
5. `git co <feature-branch> && git merge master`
6. submit the PR from the <feature-branch>

**Comment by zloster** [comment]
@greenlaw110 Thank you for the information. The problem was something that I've done.

**Pull request merged**
