### PR TITLE
Upgraded Go/Echo to v2.

### PR DESCRIPTION
**Pull request by nbrady-techempower**
Reference #2002

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@vishr Pinging you here as these tests are failing local and travis.

**Comment by vishr** [comment]
I will have a look at them soon.

**Comment by vishr** [comment]
@nbrady-techempower The build passed at my end.
When is the next benchmark round?

**Comment by nbrady-techempower** [comment]
@vishr we're looking to get round-13 official preview run and official results up really soon, i'd round-14 is at least a month  or two down the road; though now that we have a better cycle of branches for rounds, we're hoping to get them moving even faster.

**Comment by vishr** [comment]
Got it.

**Comment by nbrady-techempower** [comment]
Everything good now after rebase and re-test. Thanks @vishr! merging for round-14

**Pull request merged**
