### PR TITLE
Improve the Elixir Phoenix benchmark

### PR DESCRIPTION
**Pull request by ckampfe**
Hi there!

This PR does a few things to update the Elixir Phoenix framework benchmark:

- ~~Bumps the Erlang runtime from `18.2` to `19.0`~~, and changes random number generation to use the newer Erlang `:rand` library over `:random`, which was emitting deprecation warnings.
- Bumps the Elixir language from `1.1` to `1.3`
- Bumps the Phoenix framework from `1.0` to `1.2`, along with related dependencies, and fixes application code that broke as a result of these dependency upgrades
- Modifies the build process to:
  1. Enable kernel polling (more info here: https://stackoverflow.com/questions/1182025/what-do-the-erlang-emulator-info-statements-mean)
  2. Explicitly use consolidated protocols when starting the application (more info here: http://learningelixir.joekain.com/optmizing-elixir/)

This is all enumerated in the commit log as well :)

I have run the framework benchmark locally with these changes using the described vagrant setup and seen both faster numbers and lower error counts.

Thanks for your consideration!

PS: Please let me know if this should be reopened against another branch, happy to do so.

### CODE REVIEW

**Comment by stevedomin** [comment]
Awesome work @ckampfe!!

**Comment by ckampfe** [comment]
Thanks @stevedomin! I'm new to this Techempower stuff, do you know anywhere I could read more to figure out what we (elixir people) should be doing to fix the benchmark here? am I even picking the right branch (master)?

**Comment by stevedomin** [comment]
No idea, I'm an elixir dev myself so hopefully someone from @TechEmpower can respond to your questions

**Comment by knewmanTE** [comment]
@ckampfe thanks for your contributions! A couple things:

1) master is fine. We're going to be merging round-13 branch into master shortly, so that master can represent the current testing branch.
2) On Travis, I'm now seeing that the Erlang frameworks chicagoboss, mochiweb, and misultin are breaking. Would you mind taking a look at these and see if it's related to updating the Erlang version?

**Comment by ckampfe** [comment]
@stevedomin thanks!

@knewmanTE great, I'll keep it on master. I'll play a bit on the Erlang frameworks and see if going from `18.2 -> 19.0` had anything to do with the breakage. If so, we should be able to do the rest of this PR without any changes other than rolling back the `18.2 -> 19.0` bit.

**Comment by ckampfe** [comment]
Looking like misultin, chicagoboss, and mochiweb all require versions of dependencies that have a regexed match version string topping out at Erlang 18. To get this PR in I'm going to do like mentioned above and pull out the bit that upgrades to Erlang 19. `18.3` appears to be the latest on that major, so I'll give that a shot and repush.

`misultin`:

```
Setup misultin: ERROR: OTP release 19 does not match required regex R15B0[^1]|R16B$|R16B[^0]|R16B0[^3]|R16B03-1|17|18
Setup misultin: ERROR: compile failed while processing /home/travis/build/TechEmpower/FrameworkBenchmarks/frameworks/Erlang/misultin/deps/erlydtl: rebar_abort
```

`chicagoboss`:

```
Setup chicagoboss: ERROR: OTP release 19 does not match required regex R16|17|18
Setup chicagoboss: ERROR: compile failed while processing /home/travis/build/TechEmpower/FrameworkBenchmarks/frameworks/Erlang/chicagoboss/deps/jsx: rebar_abort
```

`mochiweb`:

```
Setup mochiweb: ERROR: OTP release 19 does not match required regex R15B0[^1]|R16B$|R16B[^0]|R16B0[^3]|R16B03-1|17|18
Setup mochiweb: ERROR: compile failed while processing /home/travis/build/TechEmpower/FrameworkBenchmarks/frameworks/Erlang/mochiweb/deps/erlydtl: rebar_abort
```

**Comment by ckampfe** [comment]
@knewmanTE @stevedomin removed the Erlang 19 version upgrade and was able to run the chicagoboss, misultin, and mochiweb, and phoenix verifications locally. Accordingly I've stripped the commit that did that.

**Comment by knewmanTE** [comment]
@ckampfe thanks! Do you know if the breaking frameworks are still being updated and maintained? If so, then this might just be a matter of waiting on them to catch up to the latest version of Erlang and then making a pull request once they're up-to-date.

Alternatively, if it seems like there is no intention for some frameworks to ever become compatible with Erlang 19 (or if development on them has ceased entirely), then it may be worth having a discussion about whether we either <b>(a)</b> remove them from the test suite or <b>(b)</b> add 2 erlang install files, one for v18.2, and one for the most up-to-date version. 

We try to avoid things like <b>(b)</b> when possible so we can reduce clutter within the repo, but we also shouldn't be limiting the performance of newer frameworks because of deprecated frameworks we still have in the suite. At the very least, it never hurts to start a discussion!

**Comment by ckampfe** [comment]
@knewmanTE:

- chicagoboss appears to actively maintained, TE might be on an old version of the framework: https://github.com/ChicagoBoss/ChicagoBoss/commit/69796d5109945fc8d012571cf8247a6a749aa623
- misultin appears to be no longer maintained as of ~2012: ["Misultin development has been discontinued."](https://github.com/ostinelli/misultin)
- mochiweb appears to be actively maintained, TE might be on an old version of the framework: https://github.com/mochi/mochiweb/commit/c583c5fc5f9784f6fb0d0f430209f46a10a825f2

I'm not sure what would be involved with getting these up to date, but I can give it a look.

**Comment by thousandsofthem** [comment]
IMO updating erlang still the good idea - at least to latest 18.x - mainly because of bugfixes in there

**Comment by ckampfe** [comment]
@thousandsofthem good point, I agree. I'll give that a try

**Comment by ckampfe** [comment]
Phoenix runs fine on 18.3, getting dependency compile errors on mochiweb and chicagoboss for `erlydtl`.

**Comment by thousandsofthem** [comment]
So sad, even 18.3 is too new 😞

**Comment by ckampfe** [comment]
@thousandsofthem yeah....

mochi in particular uses a tag that is from June 2014: https://github.com/TechEmpower/FrameworkBenchmarks/commit/6f707c9e18c987ff35176347184a6365aa106dc7#diff-3f4771e738f5e2ca9e56daed016e678fR4 and https://github.com/mochi/mochiweb/releases/tag/v2.9.0

**Comment by knewmanTE** [comment]
@ckampfe awesome work! Today we made a fix on master that solves a lot of the failing tests we were seeing on Travis (~20 of them were breaking because MongoDB wasn't starting properly). Could you try merging the latest from master into your branch and pushing to this pull request one more time? We just want to do a last sanity check on Travis to make sure there aren't any weird residual effects in your changes that might be affecting other frameworks.

**Comment by ckampfe** [comment]
@knewmanTE yep! I will get it taken care of

**Comment by ckampfe** [comment]
@knewmanTE just pulled master, rebased this branch against it, and pushed, should be as you requested

**Comment by msmith-techempower** [comment]
@knewmanTE I think we should merge this in for round-13 since it fixes a lot of Erlang/Elixir stuff which has been broken (even though it's technically a version upgrade and we frown upon that getting merged in during preview locks).

**Comment by knewmanTE** [comment]
Thanks for all of your help and cooperation @ckampfe! Merging this in now.

**Pull request merged**
