### PR TITLE
Dart tweaks

### PR DESCRIPTION
**Pull request by kevmoo**
Use best-practice JSON encoding model

some formatting tweaks

### CODE REVIEW

**Comment by hamiltont** [comment]
Any idea why this would cause the update test to start failing? See [here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/54906142#L4355). Especially odd is that the other database tests still work ok

**Comment by kevmoo** [comment]
@hamiltont Could it be a fluke? Should I rebase and try again?

**Comment by hamiltont** [comment]
It definitely could just an "oops", although normally when that happens all the tests fail. Rebasing can't hurt - why don't you do that and if it fails again we can take a most serious look

**Comment by kevmoo** [comment]
@hamiltont I installed vagrant locally. Turns out I break the DB serialization by making things final. I think this fixes things.

**Comment by hamiltont** [comment]
wow, how unexpected! Cool that travis caught this, let's see if it passes now

**Comment by LadyMozzarella** [comment]
[Travis build](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/56827422) for reference (Not started yet as of this comment)

**Comment by LadyMozzarella** [comment]
Travis-CI looks happy to me, merging. Tests are 'warn' because the check we're doing for headers is case sensitive, but fixed in a merge after these commits were made. Looks like all of the responses for update actually came back fine.

**Pull request merged**
