### PR TITLE
Hexagon version upgrade to 0.16

### PR DESCRIPTION
**Pull request by jaguililla**

### CODE REVIEW

**Comment by jaguililla** [comment]
Problems with new version deployment in JCenter. I'll rerun the tests once it is fixed.

**Comment by jaguililla** [comment]
Though Travis job is failing, Hexagon's tests are passing.

**Comment by nbrady-techempower** [comment]
@jaguililla Could you fix your `.travis.yml` to match what's currently in master?

**Comment by jaguililla** [comment]
Done

**Pull request merged**
