### PR TITLE
Swift 5.7 and Hummingbird v1.0

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Comment by adam-fowler** [comment]
@0xTim

**Comment by adam-fowler** [comment]
@0xTim the vapor mongo targets aren't compiling can you have a look

**Comment by 0xTim** [comment]
@nbrady-techempower it looks like new releases of Vapor aren't getting picked up like they used to - do we need to change anything?

**Comment by adam-fowler** [comment]
@0xTim could this be because the package has `// swift-tools-version:5.5`

**Comment by 0xTim** [comment]
@adam-fowler it's because the Vapor projects have a resolved file caching old versions of the framework. I can either remove them and do a separate PR (don't have access to your fork) or if you could remove them that would be great!

**Comment by adam-fowler** [comment]
By the way the `vapor-mongo-fluent` was dependent on both the OpenKitten and Joannis' own version of MongoKitten. I have fixed this as well

**Review by 0xTim — APPROVED** [review]

**Comment by 0xTim** [comment]
Yep fine by me - @joannis want to take a look?

**Comment by Joannis** [comment]
Taking a look tomorrow

**Pull request merged**
