### PR TITLE
Update Kemal to 0.21.0

### PR DESCRIPTION
**Pull request by sdogruyol**
This PR updates Kemal to 0.21.0 and changes the repo to new organization

### CODE REVIEW

**Comment by faustinoaq** [comment]
I think we need to update crystal too. Currently TFB is using crystal 0.22.0

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/languages/crystal.sh#L7

Also, if we update crystal to 0.23.1 then we need to add `--no-debug` flag to avoid https://github.com/crystal-lang/crystal/issues/4719

**Comment by nbrady-techempower** [comment]
@sdogruyol looks like this change needs to be made to the committed `shard.lock` as well right?

`Setup kemal: Outdated shard.lock (kemal requirements changed). Please run shards update instead.`

**Comment by faustinoaq** [comment]
@nbrady-techempower yeah, you are right, thanks your comment!

**Comment by faustinoaq** [comment]
@sdogruyol you need to update `shard.lock` too, just delete the current `shard lock` and generate a new one. Also @drujensen made a PR to update crystal, so, all should work fine.

**Comment by faustinoaq** [comment]
All crystal test are passing now, Why do Go/aah failed? Is it related to Crystal ?

**Comment by nbrady-techempower** [comment]
@faustinoaq No, just a bug with the dynamic matrix that decides what tests need to be run based on the edits provided. I'll get this in for you guys.

**Pull request merged**
