### PR TITLE
[Ruby] Update to Roda 2.23 and Sequel 4.43

### PR DESCRIPTION
**Pull request by mwpastore**
[ci fw-only Ruby/rack-sequel Ruby/roda-sequel Ruby/sinatra-sequel]

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
hi @mwpastore ! Looks like the jruby portions of the roda-sequel test failed

**Comment by mwpastore** [comment]
@nbrady-techempower Hrrm, could you rerun https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/205153728?

**Comment by msmith-techempower** [comment]
Restarted [travis](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/205153728) for you.

**Comment by nbrady-techempower** [comment]
@mwpastore Awesome, passing now! Thanks as always!

**Pull request merged**
