### PR TITLE
Axum improvements

### PR DESCRIPTION
**Pull request by vorot93**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@vorot93 There are still errors here. Trying to run locally I get:

```
axum: error: failed to parse manifest at `/axum/Cargo.toml`
axum: Caused by:
axum:   feature `edition2021` is required
axum:   The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0 (32da73ab1 2021-08-23)).
axum:   Consider trying a newer version of Cargo (this may require the nightly release).
axum:   See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.
```

Going to close for now, but feel free to re-open if you have a chance to work on it

**Comment by vorot93** [comment]
@nbrady-techempower edition 2021 requires newer rustc.

**Comment by Elabajaba** [comment]
You need to update the dockerfiles in the axum folder to a newer version of rust. It's probably also worth updating it from Debian 10 to Debian 11.

eg. 
Replace `FROM rust:1.55-slim-buster` with `FROM rust:1.59-slim-bullseye`

**Comment by nbrady-techempower** [comment]
Sure. Feel free to make the necessary changes and reopen to pass verification.

**Comment by vorot93** [comment]
@nbrady-techempower updated, please reopen

**Pull request closed without merging**
