### PR TITLE
Several Toolset Verification Updates

### LINKED ISSUE #2634: "run-tests.py --mode verify" should confirm the client machine can reach the server
Over the past two days, I've noticed three frameworks that passed the verification step but got zero RPS in actual test runs.  It turns out they all were accepting connections from localhost but not from the client machine that runs wrk.

The verification step should include a test for connectivity from the client machine.  A single successful request to any one of the server's endpoints should be sufficient for passing.

Other notes:
* Accepting connections from localhost only is the default setting for many frameworks / HTTP servers, so it's easy to run into this issue by accident.
* When this issue occurs, there usually aren't any useful clues in the server logs.  The most useful clue appears in the raw wrk output, where there should be some "connection refused" messages.

### PR DESCRIPTION
**Pull request by nbrady-techempower**
resolves #2634 

Now, during the verification step, there will be a check to see if the server is reachable from the client machine. The first step remains, which does header verification using python from the app server, and will throw errors as normal with useful information. If this step doesn't fail, then the client check will be made. Seeing that check fail will usually mean the server was set up correctly but only accepting connections from localhost.

### Queries

This PR revealed that only some frameworks are not sanitizing the query param in the queries and updates test. Since the [Test Requirements](http://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#multiple-database-queries) make it clear that missing or non-integer parameters should be interpreted as `1`, no response in these cases will now be marked as failing.

_Those are now fixed_

### JSON

JSON now warns if response bytes are greater than 27 -> {"message":"hello, world!"}

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@daviddenton If you have a chance, would you mind updating fintrospect  to account for missing queries paramater? (Fine to do in a separate PR if you have time.)

**Comment by daviddenton** [comment]
Sure I'll take a look :)

**Comment by nbrady-techempower** [comment]
@daviddenton You rock! thanks!

**Comment by daviddenton** [comment]
@nbrady-techempower that's strange. From the code it looks like this case should be handled in fintrospect.
Can you please just confirm the request URL that the framework isn't responding correctly to and I'll take a closer look.

Thanks :)

**Comment by nbrady-techempower** [comment]
@daviddenton I tried for a while to get that test working. It appears that when there is no parameter given, the `numberOfQueries` and `multipleRoute` vars are never evaluated. I assumed it had to do with `Query.optional` and tried `Query.required` but couldn't quite figure out the api for it.

**Comment by daviddenton** [comment]
@nbrady-techempower I've worked out that it's the empty query that is causing the problem - it behaves ok when there is an invalid or missing query - which confused me for a while!

I'm not at a machine at the moment, but if you change line 40 of DatabaseRoutes to:

```    
val numberOfQueries = Query.optional(ParameterSpec.string(StringValidations.EmptyIsValid).map {
```

... it should start to work ok. If it can wait then I'll PR tomorrow.

Thanks!

**Comment by nbrady-techempower** [comment]
@daviddenton that did it! thanks! :)

**Pull request merged**
