### PR TITLE
Integration of Curacao 4.0.0

### PR DESCRIPTION
**Pull request by markkolich**
* Upgrading Curacao benchmark to version `4.0.0`
* Cleanup and performance changes from Round 10 runs
* Moving Curacao build to Java 8
* Ripping out SBT, replacing with Maven
* Updating benchmark test config to test with `war` backed by Resin

### CODE REVIEW

**Comment by markkolich** [comment]
Looks like some tests failed but these failures have nothing to do with my changes for Curacao:
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/69753930

**Comment by markkolich** [comment]
Continuously bitten by Travis CI failures that are unrelated to the updates/diff in this PR.

**Comment by markkolich** [comment]
@msmith-techempower @zane-techempower @bhauer hi, are you still processing/accepting PRs? Myself and several others have noticed weird build failures with Travis that seem unrelated to the code or changes in our PRs &mdash; known issue?

**Comment by msmith-techempower** [comment]
Yes, Travis sometimes fails for reasons we cannot explain.

**Comment by markkolich** [comment]
@blee-techempower @msmith-techempower Hi folks, I have no idea why Travis continually fails my PR.  I've rebased with the latest `master`, confirmed things compile cleanly, and verified my framework tests run locally.  I'm struggling to make sense of https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/93690135 .....

```
travis_time:end:2eb46c56:start=1448740870313788365,finish=1448740899937639303,duration=29623850938
[0Ktravis_fold:end:install
[0Ktravis_time:start:083ca76e
[0K$ time ./toolset/run-ci.py verify "$TESTDIR"
Creating Benchmarker from benchmark.cfg.example
WARNING:root:results.json for test ec2 not found.
INFO:run-ci:Found 1 usable tests (1 valid for linux, 1 valid for linux and {mysql,postgres,mongodb,cassandra,elasticsearch,sqlite,redis,none}) in directory '$FWROOT/frameworks/Java/curacao'
INFO:run-ci:Using tests [u'curacao'] to verify directory $FWROOT/frameworks/Java/curacao
INFO:run-ci:Running mode verify with commmand toolset/run-tests.py --mode verify --test curacao
FWROOT is /home/travis/build/TechEmpower/FrameworkBenchmarks
Usernames (e.g. --client-user, --runner-user, and --database-user) are required!
The system will run each test as the runner-user
Aborting
[0m
real	0m0.586s
user	0m0.456s
sys	0m0.072s
travis_time:end:083ca76e:start=1448740899943576255,finish=1448740900539183065,duration=595606810
[0K
[31;1mThe command "time ./toolset/run-ci.py verify "$TESTDIR"" exited with 1.[0m

Done. Your build exited with 1.
```

What should I be looking for here to address this?  Appreciate any insight.

**Comment by bhauer** [comment]
@markkolich We'll take a look at this when time permits.  It's probably something we need to fix on our side.

**Comment by markkolich** [comment]
@bhauer ok, thanks!

**Comment by msmith-techempower** [comment]
Looks like it failed to build/run: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/96059655

**Comment by msmith-techempower** [comment]
Ah, this seems related to the issue from #1684 wherein `resin` was built with java7 and therefore does not understand what Java8 is... we may have to resolve that first.

**Comment by markkolich** [comment]
@msmith-techempower Hey Mike, thanks for looking into this.  Looks like we're getting a little bit farther.

The latest error is this:

```
Setup curacao: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile
(default-compile) on project techempower-benchmark:
Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```

My guess is Maven is running with Java 7, but I'm requiring Java 8 according to my `pom.xml`.

I have specified `fw_depends java8 resin maven` in my `setup.sh`:
https://github.com/TechEmpower/FrameworkBenchmarks/pull/1706/files#diff-a3e3c857a83eb9e20e25b7a0010a33d3R3

Am I missing another setting to enable Java 8 compilation?

**Comment by msmith-techempower** [comment]
The problem is that `fw_depends resin maven` both chain up and have `fw_depends java7`.

At some point we need to either add a `resin_java8` (undesirable) or move everything to using `java8` (still not entirely desirable, but probably the best solution).

**Comment by msmith-techempower** [comment]
We have entirely updated to Java8; please rebase off master for a retest.

Related, I just merged in #1892 without thinking to look back to this one; is this work still relevant?

**Comment by markkolich** [comment]
@msmith-techempower yes, the work here is still relevant.  I've rebased with the top of `master` and am currently waiting on Travis results.  Can you take another look and merge this in when Travis finishes?

**Comment by msmith-techempower** [comment]
Looking much better, now! All tests pass; LGTM!

**Comment by markkolich** [comment]
@msmith-techempower Awesome! Thanks for pushing this through, and for all of the hard work upgrading your stack to Java 8!

**Pull request merged**
