### PR TITLE
[ci skip] Easier debug

### PR DESCRIPTION
**Pull request by joanhey**
Added to `--mode debug`  http://localhost:28080 to open with Ctrl+click.
It will not be necessary to look at the documentation.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@joanhey This only works for people that use port 8080 and then are using vagrant which is mapping 28080 to 8080. If you're testing through some other means, or using curl on another screen in vagrant, it will be the actual test port.

**Comment by joanhey** [comment]
From vagrant is more than 90% of cases.
Perhaps we can add to the test: from vagrant  http://localhost:28080

**Comment by nbrady-techempower** [comment]
It's not just that it's vagrant, it's also that the test has to be using port 8080 which we don't enforce. I use vagrant too, but I never hit the debug endpoint from outside of vagrant; I'm usually using screen or tmux. Let me think on this a moment. We can probably test that the user is using vagrant and then add a message like:
```
http://localhost:8080 or http://localhost:28080 outside vagrant
```

or if they're not using vagrant and the port isn't 8080 just
```
http://localhost:<test.port>
```

**Comment by nbrady-techempower** [comment]
Addressed this in #5135

**Pull request closed without merging**
