### PR TITLE
Php/CodeIgniter upgrade

### PR DESCRIPTION
**Pull request by arysom**
Version bump and change of www link.

### CODE REVIEW

**Comment by arysom** [comment]
Can someone tell me, why it has failed?

**Comment by cjnething** [comment]
Hi @arysom did you check [the logs](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/283339002)? (I looked and I don't really understand what went wrong either)

**Comment by arysom** [comment]
@cjnething  - me too. I have no idea. Some bench.json fails for the first time and then the rest probably fails because of that. Maybe it some test settings. Many PRs here fail. You can close pr, or I can make it once again. No problem. Cheers.

**Comment by cjnething** [comment]
@arysom Thanks for your contribution! Closing for now, but please feel free to reopen/make a new one.

**Pull request closed without merging**
