### PR TITLE
Various Swift framework optimizations

### PR DESCRIPTION
**Pull request by adam-fowler**
@0xTim

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
LGTM

**Comment by nbrady-techempower** [comment]
Can you remove the `.gitignore` in the language root directory. Other than that, this looks good.

**Comment by adam-fowler** [comment]
I put the .gitignore in the root of the swift folder as it was a standard set of files to ignore in swift projects and I had noticed other languages had a global .gitignore. 

I'm happy to remove it if so desired. Is it ok to move into the hummingbird folders?

**Comment by adam-fowler** [comment]
@nbrady-techempower I have moved .gitignore to the hummingbird folder are we good with that?

**Pull request merged**
