### PR TITLE
Update Php Laravel from 3.2.14 to 4.2

### PR DESCRIPTION
**Pull request by LadyMozzarella**
Tests all warn/pass with update.
- laravel: fortune pass, query & db warn  
- laravel-raw: plaintext & json pass

### CODE REVIEW

**Comment by hamiltont** [comment]
You replaced the source code with a composer download, if I'm reading this right. If so, great!!! Don't forget to also commit the `composer.lock` file to the repo - it's the fully-qualified version of the `composer.json`

**Comment by LadyMozzarella** [comment]
Thanks @hamiltont! I had placed the composer.lock in the .gitignore. Added now.

**Comment by msmith-techempower** [comment]
@LadyMozzarella This is failing on a clean (brand new) VM and travis - is there something missing?

**Comment by LadyMozzarella** [comment]
I have a sed that isn't the correct path for the nginx config. So it was working on my machine, but failing on Travis. - I'm fixing it now.

**Comment by msmith-techempower** [comment]
Why was this closed?

**Comment by LadyMozzarella** [comment]
@msmith-techempower I accidentally reverted back too far and the association between the branch and this pull request was lost. So, github automatically closed it. I submitted a new pull request for this at [#1323](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1323).

**Pull request closed without merging**
