### PR TITLE
Implements disabled log destination

### PR DESCRIPTION
**Pull request by NinoFloris**
See #6627

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
I think we can give this a shot. A new run will be starting shortly with this change and can be compared to https://tfb-status.techempower.com/results/67c8e670-dab3-44f9-94c3-21a80074afc9

**Comment by sebastienros** [comment]
This is breaking the ASP.NET perf lab. Not saying it's wrong but didn't expect that. What's happening is that now the postgresql log is only comprised of these lines

```
[STDERR] 2021-06-16 19:00:15 GMT LOG:  ending log output to stderr
[STDERR] 2021-06-16 19:00:15 GMT HINT:  Future log output will go to log destination "".
```

And we are not detecting that the server is ready to accept connections.

I might still be able to change the setting on my side, or check for this message instead.

**Comment by nbrady-techempower** [comment]
@sebastienros Happy to revert after the next run finishes if you need more time to figure it out. Let me know. Still have to confirm that this is a net positive change.

**Comment by sebastienros** [comment]
I am not blocked, had to change what message we look for to detect if postgres is ready.

**Comment by NinoFloris** [comment]
@sebastienros I've asked to get a run to see what the effects are, I think given the amount of failing tests I noticed there are many frameworks that don't really support running their benchmarks with this disabled (yet). Really just curious what the outcome is. Like I said locally I saw *a lot* of effect, if that replicates I might start writing postgres patches to reduce the general cost of having any log destinations.

**Comment by NinoFloris** [comment]
That being said, I don't see a lot of difference in the running results yet https://www.techempower.com/benchmarks/#section=test&runid=5409dd1a-7afa-4be6-a81e-8160b38cfce2 specifically actix would have absolutely shown better numbers if this had any effect so if you want @nbrady-techempower you could revert already.

**Comment by nbrady-techempower** [comment]
@NinoFloris @sebastienros ok let's revert. I appreciate the effort here!

**Pull request merged**
