### PR TITLE
[ci fw-only Java/act] Docker act 1.8.0

### PR DESCRIPTION
**Pull request by greenlaw110**
[ci fw-only Java/act] update to act-1.8.0; tune for act-hibernate updates test

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hey @greenlaw110 Sorry I missed your google groups post. I'm much more active here so if you have any further questions feel free to ping any of us here. Part of this transition will include better error reporting, and I'll make sure to capture what you just saw. I just ran into the same issue this morning because of a typo in a dependency.

**Comment by greenlaw110** [comment]
@nbrady-techempower The CI failure is not caused by Java/act, can you please merge this PR?

**Comment by nbrady-techempower** [comment]
Just going to ping @michaelhixson on this since he has taken care of all the Java -> docker stuff and make sure this doesn't conflict for him

**Comment by michaelhixson** [comment]
@nbrady-techempower The only Java framework left to dockerize is Servlet.  This PR looks fine to me, though I'm guessing the addition of `may-minihttp/setup.sh` is unintentional - a merge gone wrong.

**Pull request closed without merging**
