### PR TITLE
Add Crystal

### PR DESCRIPTION
**Pull request by will**
Only the JSON and Plain Text tests, but it's a start.

### CODE REVIEW

**Comment by msmith-techempower** [comment]
Is there no framework being exercised? What is the reason for the directory being called "stdlib" instead of "crystal-raw" or similar?

**Comment by will** [comment]
> Is there no framework being exercised?

Correct

> What is the reason for the directory being called "stdlib" instead of "crystal-raw" or similar?

I wasn't aware of the naming conventions. I can change it to crystal-raw :)

**Comment by msmith-techempower** [comment]
Great, `crystal-raw` sounds good. Also, after you do that, I think we can safely merge it in since [Travis-CI](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/64016022) has checked it.

**Comment by will** [comment]
Updated, thanks!

Question for future tests: Were I to include a [postgres driver](github.com/will/crystal-pg) for the database tests, would that still fit under -raw?

**Comment by msmith-techempower** [comment]
Yeah, if you plan on including the database tests, I would suggest adding them to the `raw` one you have here.

LGTM!

**Comment by Vikaton** [comment]
Someone is working on a framework on Crystal called Moonshine

**Pull request merged**
