### PR TITLE
Add benchmark for Finatra framework (Scala)

### PR DESCRIPTION
**Pull request by cacoco**
Pull request to add the [Finatra](https://github.com/twitter/finatra) framework and benchmark tests to the TechEmpower/FrameworkBenchmarks.

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @cacoco we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by cacoco** [comment]
@nbrady-techempower sure thing. Thanks!

**Comment by nbrady-techempower** [comment]
Awesome thank you! We'll just run it through travis again, test it on our local branch and then get it merged in to Round-14! We'll be able to more easily control the process this way and allow contributors to make new contributions much faster without having to worry about open PRs :smile_cat:

**Comment by cacoco** [comment]
Created https://github.com/TechEmpower/FrameworkBenchmarks/pull/2063

**Pull request closed without merging**
