### PR TITLE
Enable LTO for warp-rust

### PR DESCRIPTION
**Pull request by xfix**
This makes compilation slower, but this isn't a compilation time benchmark, so that's fine.

### CODE REVIEW

**Comment by xfix** [comment]
Seems like warp-rust currently doesn't build, so this will update yarte as well.

**Comment by joanhey** [comment]
Aside:
The github-actions need to delete the label `PR: Please Update` when another commit pass the tests.
@ajohnstonTE

**Comment by ajohnstonTE** [comment]
@joanhey This was actually discussed on our end at the time, and we decided to have it require manual review to remove the label. @nbrady-techempower Anything to add to that?

**Comment by nbrady-techempower** [comment]
Yeah, I prefer to leave the label. We could do a separate label, but if I add the label manually for a different reason, I wouldn't want the action to delete it on the next passing test. The label at least gives me, the person who is normally doing all the review, the callout to take a closer look.

**Pull request merged**
