### PR TITLE
H2O: Optimize the multiple queries and database updates tests

### PR DESCRIPTION
**Pull request by volyrique**
These changes are mostly about query parallelization. There are more details in the commit descriptions.

### CODE REVIEW

**Comment by knewmanTE** [comment]
This LGTM. Are you ready to merge it in?

**Comment by volyrique** [comment]
Yes, I am.

**Comment by knewmanTE** [comment]
Excellent! Merging it in then!

**Comment by volyrique** [comment]
Thanks! Are there any plans to do a preview round soon?

**Comment by methane** [comment]
Is parallel query execution allowed?
ref https://github.com/TechEmpower/FrameworkBenchmarks/issues/2204

**Comment by knewmanTE** [comment]
Hmm, that's actually a good question. I may have misinterpreted what exactly h2o was doing in this change. I know that we don't allow batch requests (i.e. each DB request is expected to make a full round-trip to the database server). I'm not sure how that applies to parallel execution. I apologize if I merged this prematurely. 

ping @msmith-techempower @bhauer

**Comment by volyrique** [comment]
I don't see how #2204 applies to this case: The implementation is not making bulk requests of any kind - every row is selected by exactly one query, and there are exactly N roundtrips to the database.

**Comment by methane** [comment]
https://groups.google.com/forum/#!msg/framework-benchmarks/nePDNY9jp-4/EtG6SswmFQAJ

> The use-case this is approximating is an application behavior where you need to read item A and then based on A's value and other logic, you need to read item B and then based on B's value and other logic, you now need to read item C, and so on.  Imagine branching code.

**Comment by volyrique** [comment]
The same message says as well:
> The N iterations are intended to be the equivalent of doing the database work of the Single-query test in its entirety N times, but without the overhead of an additional the HTTP request. [...] The intent has always been to do N round-trips to the database server to fully exercise the connection pool, database driver, ORM (where applicable), and other elements of database connectivity.

This is exactly what the implementation does; in fact, what prompted the change was the fact that the database connection pool was not exercised properly.

**Comment by methane** [comment]
I don't understand full chnage of this pull request.
Couldn't you exercise connection pool properly without parallel query execution?

**Comment by volyrique** [comment]
No, as explained in the first commit description (the current physical hardware environment has 40 cores).

**Comment by methane** [comment]
Uh, I though "exercise" means "simulate real usage", not "saturate the pool".

As I mentioned above, this test simulates sequential N query roundtrip
(one query is depends on result of previous query).

No problem about can't saturate all connections in pool.
If you don't like free conns in pool, you can reduce conns/thread.
All frameworks must follows same rule.

**Comment by bhauer** [comment]
For the multiple-query test, I feel it is acceptable to run the N queries in parallel *as long as* each query is executed with a complete round-trip communication with the database server.  What we want to avoid is tactical optimization for this benchmark that uses either a batch or a single statement to run all N queries, and in so doing, avoids the overhead of N round-trips to the database server.

The test is using a very simple query as a least-complex proxy for more complex queries that have nothing to do with one another and would be run separately in a real-world application—that is, not batched.  So I feel it is acceptable to run them in parallel as long as they are not sharing statements and avoiding the round-trip communication costs.  (Executing them in parallel would, in most cases, actually ensure that they were running on separate connections, so I think it would be exceptional for any sharing to be happening in a parallel implementation approach.)

As for the Updates test type, I would say parallelism is okay here as well, except that each parallel task should run a read then a write.  In other words, the read-then-write work load should be considered an atomic sequence.  It is not acceptable to parallelize N reads and N writes as a unified set of tasks numbering 2*N.

Also, the intent of this test is still to exercise separate statements for each read and write.  In other words, we want 2*N round-trips to the database server in total: N reads and N writes.

I hope that helps clarify, but please let me know if anything is unclear or inconsistent.  Thanks!

**Comment by volyrique** [comment]
Thanks for the explanation! I just have one comment for the updates test:
> In other words, we want 2*N round-trips to the database server in total: N reads and N writes.

Doesn't that contradict the current requirements page, and in particular the statement that batch updates are acceptable? Such approach would imply less than 2*N round-trips.

**Comment by bhauer** [comment]
Ah yes.  Sorry, that was a recent change that I made to the requirements after a conversation with someone else about the same matter.  The *original* intent was 2*N round-trips, but you are correct, the requirements as they are set now allow for batches on the updates (writes) side of the Updates test.

The [requirements](https://www.techempower.com/benchmarks/#section=code) should always trump anything that I say here or on the mailing list.

**Pull request merged**
