### PR TITLE
Rust framework Anansi (not accepting requests from client machine)

### PR DESCRIPTION
**Pull request by saru-tora**
This framework does not seem to accept requests during tests for some reason.

### CODE REVIEW

**Comment by joanhey** [comment]
Failed compiling:
https://github.com/TechEmpower/FrameworkBenchmarks/actions/runs/3832471255/jobs/6763475162#step:9:982

**Comment by saru-tora** [comment]
Changing it to `0.0.0.0` made it pass the JSON and plaintext test @nbrady-techempower. However, for the db test, now it says it can't find the randomNumber column.

**Comment by nbrady-techempower** [comment]
@saru-tora Great! Glad that worked. Is this ready to be moved out of draft?

**Comment by nbrady-techempower** [comment]
@saru-tora Thanks, that's no longer relevant

**Pull request merged**
