### PR TITLE
Run optimize for laravel

### PR DESCRIPTION
**Pull request by bratao**

### CODE REVIEW

**Comment by hamiltont** [comment]
For the uninitiate, what's the difference between composer's `--optimize-autoloader` and `php artisan optimize --force`?

**Comment by bratao** [comment]
Internally it will call Composer with the optimize flag, but in addition it will create bootstrap/compiled.php , that is a 'pre-compiled' file with common classes.

**Comment by hamiltont** [comment]
good to know

**Comment by hamiltont** [comment]
@bratao Would this be useful for the other PHP-based tests too? If yes, how do you feel about sending me a PR for that? :-)

**Pull request merged**
