### PR TITLE
php/peachpie benchmarks fixes

### PR DESCRIPTION
**Pull request by jakubmisek**
- fixes broken tests
- removes broken tag
- selects id from database properly
- updated runtime

### CODE REVIEW

**Comment by jakubmisek** [comment]
I see the tests cause an exception: HTTPConnectionPool(host='tfb-server', port=8080): Read timed out. (read timeout=15)

Currently not sure why, so we'll try to fix it and update the PR asap

**Comment by jakubmisek** [comment]
seems the build and CI passed, ready to merge :)

**Comment by nbrady-techempower** [comment]
@jakubmisek Can you rebase this, please? You have some file changes that don't belong.

**Comment by jakubmisek** [comment]
@nbrady-techempower thank you for the checks, I've created a clean PR at https://github.com/TechEmpower/FrameworkBenchmarks/pull/5746

**Pull request closed without merging**
