### PR TITLE
Updated to Play 2.4.2

### PR DESCRIPTION
**Pull request by donovanmuller**
Removed deprecated BoneCP tests.

### CODE REVIEW

**Comment by hamiltont** [comment]
Code looks good to me. 

[bonecp](https://github.com/wwadge/bonecp) appears to have been updated as recently as ~20 days ago - can I get a second "yes, it's deprecated" voice from someone?

**Comment by donovanmuller** [comment]
@hamiltont It's not so much the status of the bonecp project itself that led to the tests being removed (even though the github README advises using Hikari and that bonecp should be considered deprecated), but rather that Hikari has superseded bonecp as the default connection pool for Play 2.4. @richdougherty happy?

**Comment by hamiltont** [comment]
Oh my bad - totally missed the big bold part of the readme that said bonecp shoudl not be used. This LGTM then!

**Comment by richdougherty** [comment]
Looks good, @donovanmuller!

**Pull request merged**
