### PR TITLE
Update installer.ps1~

### PR DESCRIPTION
**Pull request by NuttasitBoonwat**
edit http to https

### CODE REVIEW

**Comment by cjnething** [comment]
Hi @NuttasitBoonwat thanks for your recent contributions! For future merge requests, please put all of your similar changes in the same merge request. So for example, if you see other changes from "http" to "https" that you would like to change, please put them all in one merge request. Feel free to ask if you have any questions. Thanks!

**Comment by NuttasitBoonwat** [comment]
Thanks! @cjnething i’m a beginner

**Comment by cjnething** [comment]
@NuttasitBoonwat Great! This was my first open-source project too. I'm a bit biased but I think it's a good one for beginners.

**Comment by NuttasitBoonwat** [comment]
@cjnething okays i’ll do my best 😁

**Pull request merged**
