### PR TITLE
Add .json Extension to benchmark_config Files, Resolve #1095

### LINKED ISSUE #1095: Rename benchmark_config as benchmark_config.json
Or any other name that includes a `*.json` extension, so that it opens up in everyone's editors with the proper settings.

### PR DESCRIPTION
**Pull request by LadyMozzarella**
Rename benchmark_config files to benchmark_config.json to resolve #1095. 

Everything appears to be running fine in my separate Travis, except for Perl (see issue #1366).

### CODE REVIEW

**Comment by hamiltont** [comment]
LGTM, great work

**Comment by hamiltont** [comment]
If this is fixed up, feel free to cancel the build for #1446 and close the PR :-)

**Comment by LadyMozzarella** [comment]
ah ok - sure @hamiltont

**Comment by LadyMozzarella** [comment]
@hamiltont Are we ready to merge this one in, or should we hold off for a bit?

**Comment by hamiltont** [comment]
Merged - took another look @ the code and the Travis results, it LGTM

**Pull request merged**
