### PR TITLE
Bump to Ninja 4.0.5.

### PR DESCRIPTION
**Pull request by raphaelbauer**
Painless and simple to merge. Thanks!

### CODE REVIEW

**Comment by msmith-techempower** [comment]
There appears to be an error with Maven's dependency stuff:
```
INFO:run-ci:[ERROR] Failed to execute goal on project ninja-standalone: Could not resolve dependencies for project org.ninjaframework.techempower:ninja-standalone:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.ninjaframework:ninja-servlet:jar:4.0.5, org.ninjaframework:ninja-standalone:jar:4.0.5, org.ninjaframework:ninja-test-utilities:jar:4.0.5: Could not find artifact org.ninjaframework:ninja-servlet:jar:4.0.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
INFO:run-ci:[ERROR] 
INFO:run-ci:[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
INFO:run-ci:[ERROR] Re-run Maven using the -X switch to enable full debug logging.
INFO:run-ci:[ERROR] 
INFO:run-ci:[ERROR] For more information about the errors and possible solutions, please read the following articles:
INFO:run-ci:[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by raphaelbauer** [comment]
Hey @msmith-techempower , I just tried it and it works without any problems. Maybe the connection was gone, or maven was down when Travis tried to build?

Would you mind starting the build again? Should work just fine...

Thanks! Raphael

**Comment by hamiltont** [comment]
I got it - restarted the java ninja test

**Comment by raphaelbauer** [comment]
@hamiltont thanks - does that mean it works?

**Comment by hamiltont** [comment]
Yea, this LGTM. I've re-run it twice now, it succeeded both times. Travis must have hiccupped the first time around

**Pull request merged**
