### PR TITLE
Add Cutelyst framework tests

### PR DESCRIPTION
**Pull request by dantti**
This includes all 6 test as
well as json configuration for
running them. Since Cutelyst has
a pluggable Engine which the best one is
uwsgi, the test use it to process the
HTTP requests directly, an initial work
to use nginx as a front-end giving it
keep-alive support is also available.

The Qt 5.6 PPA used for these test did
not provide a postgres driver so that's
disabled at the moment.

### CODE REVIEW

**Comment by msmith-techempower** [comment]
You need to add your test to `.travis.yml` in order for Travis-CI to test it properly.

**Comment by cjnething** [comment]
This failed on Travis

**Comment by dantti** [comment]
yes, odd as it works locally, I'll try to fix this next week :)

**Comment by dantti** [comment]
The new commit should fix this now

**Comment by dantti** [comment]
ok, now with postgres drivers on the Qt 5.6 ppa all tests pass, please review

**Comment by msmith-techempower** [comment]
Tests passed in Travis.

**Comment by nbrady-techempower** [comment]
Hi @dantti we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by dantti** [comment]
Sure will rebase for round-14, is there some end date? I'm about to do a new release but I'm trying to have more unit tests and ATM fix a MSVC build

**Comment by nbrady-techempower** [comment]
@dantti No projected time for freezing round-14 just yet so you probably have some time. If it's an ongoing thing that you don't think will be ready for a while you can pull it against round-15 and mark it as a work in progress.

**Comment by dantti** [comment]
Ok, current tests in this PR are fine, so it could be testable at any moment, it would be just switch the underground Core lib. I asked to see if I should hurry and make a new release in some short time. Especially since this 13 round PR was ready a couple of weeks after freeze :)

**Comment by nbrady-techempower** [comment]
hi @dantti Did you want to reopen this against round-14? Is there anything we can help you with?

**Comment by dantti** [comment]
I have just released [Cutelyst 0.12.0](https://dantti.wordpress.com/2016/06/21/cutelyst-0-12-0-is-out/) so, now I'll work on this :)

**Comment by nbrady-techempower** [comment]
@dantii great news! excited to see some results! :)

**Pull request closed without merging**
