### PR TITLE
jooby: get back netty

### PR DESCRIPTION
**Pull request by jknack**

### CODE REVIEW

**Comment by maxdemarzi** [comment]
Why pick, why not have both?

**Comment by jknack** [comment]
Too late for adding both, will be a great addition for R15

**Comment by nbrady-techempower** [comment]
Yeah, seems like we're going back and forth with this. You could duplicate the tests for undertow as well. No problem there.

**Comment by jknack** [comment]
Will do in R15

**Comment by zloster** [comment]
@jknack @maxdemarzi It is quite easy to support both especially when your code doesn't require changes in it. Make additional `setup-undertow.sh`. Add two maven profiles in the `pom.xml` (or default with `netty` as dependency and another with `undertow` as dependency). In the first script you call maven with the profile that is packaging `netty`, the other script will call maven with the profile which is packaging `undertow`. Add the new setup script as configuration in `benchmark_config.json`. Update the metadata. All done. Take a look in the [Dropwizard test](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/dropwizard) for details.

**Comment by jknack** [comment]
@zloster Thank you. I didn't know this was possible.

**Comment by nbrady-techempower** [comment]
@jknack Do you want this in for Round 14 and then work on putting multiple implementations together or leave as is until that's complete?

**Comment by jknack** [comment]
@nbrady-techempower In for R14 (if possible).

**Pull request merged**
