### PR TITLE
Upgrade to .NET 8

### PR DESCRIPTION
**Pull request by LLT21**
The project is upgraded to .NET 8. The MySQL test has been commented out as it generates a problem with .NET 8 ODBC. The Npgsql is natively compiled without reflection.

### CODE REVIEW

**Comment by pebezo** [comment]
Since this PR was sent the final .NET8 came out, so may as well use that?

**Comment by LLT21** [comment]
@pebezo : upgraded to the official .NET 8 release

**Comment by LLT21** [comment]
@pebezo : can you merge this pull request or is it still @nbrady-techempower who merges the .NET pull requests ?

**Comment by pebezo** [comment]
Sorry, I don't have merge permissions in this repo...

**Pull request merged**
