### PR TITLE
Added Cygnite PHP Framework for Benchmarking

### PR DESCRIPTION
**Pull request by sanjoydesk**
Added Cygnite PHP Framework for Benchmarking

### CODE REVIEW

**Comment by knewmanTE** [comment]
Thanks for adding your framework! Always great to see people developing frameworks and adding them to the benchmark tests!

It looks like you might still have some of the boilerplate files in your merge request. Could you try to isolate the files that are part of the benchmark test and then use `wget` or `git clone` to download the framework itself? You can check out a few examples of this being done here:

- [ClanCats (PHP, still a pending merge request)] (https://github.com/TechEmpower/FrameworkBenchmarks/blob/php-ccf2/frameworks/PHP/clancats/install.sh)
- [Silicon (C++)](https://github.com/TechEmpower/FrameworkBenchmarks/blob/619e5d2fec8b0f0d8f034fe1a6353b93c89493ed/frameworks/C%2B%2B/silicon/install.sh) 
- [web2py (Python)](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/web2py/install.sh).

**Comment by sanjoydesk** [comment]
Hi,

Thanks for the reference. I will make changes and send back. Please let me know if I miss anything so that I can do necessary changes. @knewmanTE 

Thank you!

**Comment by sanjoydesk** [comment]
Hi @knewmanTE 

I have updated code as per the reference into my branch. Can you please let me know if everything is fine and good to  go ahead?

Thanks!

Warm Regards,
Sanjoy

**Comment by knewmanTE** [comment]
Cool! Looks like you've pretty much got the structure setup. A couple quick tweaks:

1) in the root of the FrameworkBenchmarks (the directory with config/, deployment/, frameworks/, toolset/) there's a file `.travis.yml`. In order for travis to run its test suite on your framework, you have to add a line for your framework (i.e. `- "TESTDIR=PHP/php-cygnite"`)

2) It looks like all of the TFB-specific code is located in these files (unless I missed one):
- `apps/configs/database.php`
- `apps/controllers/BenchController.php`
- `apps/models/Fortune.php`
- `apps/models/World.php`
- `apps/routes.php`
- `apps/views/bench/fortunes.view.php`

There are still a lot of Cygnite boilerplate files that don't necessarily need to live in the FrameworkBenchmarks Github repo (including a large number of cached files and a number of Twitter Bootstrap CSS/JS files).

I'm not familiar with the cygnite framework, but based on its Github repo, it looks like cloning the repo will provide you with all of the default controllers, assets, and other such files.

What I'd recommend is creating a folder in `frameworks/PHP/php-cygnite` called `apps` and including only the FrameworkBenchmark-related files. For example:

apps/
--- configs/database.php
--- controllers/BenchController.php
--- models/
------ Fortune.php
------ World.php
--- views/bench/fortunes.view.php
--- routes.php

And then adding a few lines to your `install.sh` script to clone the git repo and copy in your FrameworkBenchmark files. something like:

```
# changes directory to /frameworks/PHP/php-cygnite
cd $TROOT
# removes the previous clone of cygnite framework
rm -fr cygniteframework
# clones a fresh version of the framework
git clone --branch v1.5-alpha https://github.com/sanjoydesk/cygniteframework.git
# adds your benchmark files to the cygnite framework
cp -r apps/ cygniteframework/
```

If you check my first comment, I linked to a few other frameworks that do similar things. For example, [web2py](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Python/web2py) contains a simple `app/` folder, but if you check it's [install.sh file](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/web2py/install.sh), you can see that it clones in the rest of the boilerplate web2py code from Github. This will also require you to adjust your `setup.sh` and `nginx.conf` files to match the new root location of the framework.

I hope that was helpful! I know that the benchmark tools have kind of a confusing setup, so feel free to ask if anything I just wrote doesn't make sense.

**Comment by sanjoydesk** [comment]
Hi @knewmanTE 

Thanks! for for the explaining. I have removed all files which is not necessary for the test. But I am little confused about your example to clone source code from GITHUB repo.

The first thing is Cygnite official core repository is located as below.

https://github.com/cygnite/cygnite-application - Skeleton App
https://github.com/cygnite/framework - Core Framework

There is a composer.json located in the root directory of php-cygnite which will install core dependencies. We install cygnite as [here!](http://goo.gl/3HGLlI). So please let me whether any other tweaks required for the test.

Thank You!

Regards,
Sanjoy Dey

**Comment by knewmanTE** [comment]
@sanjoydesk yes, if you can get the framework with composer, that's totally fine! Definitely the cleaner solution.

It looks like the Travis test is still failing. It gave the error:
`The command "./toolset/run-ci.py cisetup "$TESTDIR"" failed and exited with 1 during .`

I'm not entirely sure at the moment what the cause of the issue is. I'm pretty busy at the moment, but might be able to take a look later.

**Comment by sanjoydesk** [comment]
Hello @knewmanTE yes sure. I am trying different way to resolve, if not please help me whenever you get some time.

Thank you!

**Comment by hamiltont** [comment]
Nice pr! 

 - Travis is failing because there is no [benchmark_config.json](https://frameworkbenchmarks.readthedocs.org/en/latest/Codebase/Framework-Files/#benchmark-config-file). 
 - Please rename `php-cygnite` to `cygnite`  (the php prefix is a holdover from history that we're trying to remove)
 - composer is definitely preferred for the php-based tests, let's us upgrade much more quickly/sanly

**Comment by sanjoydesk** [comment]
Thanks @hamiltont Quite confusing things as need to do lot configuration for anyone new. 

I have added benchmark_config.json into the root and also removed unnecessary files from the source code. 

Thanks!

**Comment by sanjoydesk** [comment]
Good to see travis pass the build. Hope now Cygnite is ready to merge. @knewmanTE @hamiltont 

Thanks!

**Comment by hamiltont** [comment]
The last commit caused two minor issues - basically, all the queries urls e.g. `http://127.0.0.1:8080/index.php/bench/db/0` and `http://127.0.0.1:8080/index.php/bench/db/foo` should be returning an array of json objects, even if it's an array of length one.

**Comment by hamiltont** [comment]
You can look at the bottom of your travis run for full details if that didn't make sense ;-)

**Comment by hamiltont** [comment]
LGTM. THanks for the hard work on this!

**Comment by sanjoydesk** [comment]
Please check. Good to go ? :+1: @hamiltont 
```
===============================================================================
  Verification Summary
| Test: cygnite-php-framework
|       plaintext   : PASS
|       json        : PASS
| Test: cygnite-php-framework-raw
|       query       : PASS
|       db          : PASS
|       fortune     : PASS
==============================================================================
```

**Pull request merged**
