### PR TITLE
Update nodejs to v0.10.38 and fix warnings

### LINKED ISSUE #1520: node.js & MySQL: response is formed too early
Code for node.js seems to not be handling errors correctly, where a 200 response code is written to output before an operation succeeds (in fact, before it starts).

### PR DESCRIPTION
**Pull request by mhart**
Fixes #1520 and all other warnings regarding things like the `Server` header.

Also updates all module dependencies to their latest versions and removes some duplicate code.

### CODE REVIEW

**Comment by ebramanti-techempower** [comment]
Definitely want to wait on this PR. I've been working to update everything to latest version of node (0.12.2) and I'll also be switching the SQL driver as well. io.js support will be worked on after this is done.

**Comment by mhart** [comment]
Oh ok – I thought this would be a quick fix to get in before working on 0.12 or io.js which I imagine are bigger targets.

I'm a bit confused by the build failure – it works fine for me – maybe it's transient, because the other tests passed fine?

**Comment by hamiltont** [comment]
> it's transient, because the other tests passed fine?

Quite possible, travis-ci occasionally has unexpected network failures, which appears to be what happened to nodejs based on the output I've copied below. I'll restart the build to see if it greenlights 

```
Setup nodejs: > (node-gyp rebuild 2> builderror.log) || (exit 0)
Setup nodejs: 
Setup nodejs: npm ERR! Linux 2.6.32-042stab090.5
Setup nodejs: npm ERR! argv "node" "/home/travis/build/TechEmpower/FrameworkBenchmarks/installs/nvm/v0.10.38/bin/npm" "install"
Setup nodejs: npm ERR! node v0.10.38
Setup nodejs: npm ERR! npm  v2.8.3
Setup nodejs: npm ERR! code ECONNREFUSED
Setup nodejs: npm ERR! errno ECONNREFUSED
Setup nodejs: npm ERR! syscall connect
Setup nodejs: 
Setup nodejs: npm ERR! Error: connect ECONNREFUSED
Setup nodejs: npm ERR!     at errnoException (net.js:905:11)
Setup nodejs: npm ERR!     at Object.afterConnect [as oncomplete] (net.js:896:19)
Setup nodejs: npm ERR!  { [Error: connect ECONNREFUSED]
Setup nodejs: npm ERR!   code: 'ECONNREFUSED',
Setup nodejs: npm ERR!   errno: 'ECONNREFUSED',
Setup nodejs: npm ERR!   syscall: 'connect',
Setup nodejs: npm ERR!   parent: 'mongoose' }
Setup nodejs: npm ERR! 
Setup nodejs: npm ERR! If you are behind a proxy, please make sure that the
Setup nodejs: npm ERR! 'proxy' config is set properly.  See: 'npm help config'
Setup nodejs: 
Setup nodejs: npm ERR! Please include the following file with any support request:
Setup nodejs: npm ERR!     /home/travis/build/TechEmpower/FrameworkBenchmarks/frameworks/JavaScript/nodejs/npm-debug.log
nodejs: setup.sh and framework processes have terminated
Setup nodejs: Setup has terminated
Setup nodejs: setup.sh process exited naturally with 1
INFO:root:Executed setup.sh, returning 1
```

**Comment by hamiltont** [comment]
ping @knewmanTE - is this PR compatible with your ongoing work with nodejs? E.g. can we merge this immediately if travis agrees, or do you want to do something first

**Comment by ebramanti-techempower** [comment]
Do not merge! I'm doing a ton of work on all the Node frameworks right now @hamiltont

**Comment by hamiltont** [comment]
Ok, thanks for the heads up. You can merge PRs, right? It not, just ping me here when you want this merged

**Comment by ebramanti-techempower** [comment]
@hamiltont Yes, but with @mhart's permission I would like to close this PR and merge his changes into my big upgrade PR coming later today.

**Comment by mhart** [comment]
Sure – I mean, I think it's a better basis to start from than the existing code. But if you're nearly done with your changes, then may as well.

**Comment by ebramanti-techempower** [comment]
@mhart I should be making a PR later today, you can follow my continued work [here](https://github.com/ebramanti-techempower/FrameworkBenchmarks/tree/update-node-frameworks).

**Comment by knewmanTE** [comment]
@hamiltont , just to confirm, you were referring to @ebramanti-techempower 's nodejs work, right?

**Comment by ebramanti-techempower** [comment]
@knewmanTE I think so, I thought you were working on Lumen.

**Comment by knewmanTE** [comment]
Yeah, Lumen is PHP. Thus far I think I've only done work on PHP and Python frameworks.

**Comment by hamiltont** [comment]
> referring to @ebramanti-techempower 's nodejs

Correct, my bad. It's a bit tough to keep track of what everyone's doing with the influx of new comments/PRs/etc ;-)

**Comment by hamiltont** [comment]
ps - are either of you present in the IRC channel? I find it faster for resolving small confusions like this, so  ping me if you're there so I can know your usernames

**Comment by ebramanti-techempower** [comment]
Don't believe I'm in IRC, I'll get myself set up

**Pull request closed without merging**
