### PR TITLE
Fix compilation of Scala unfiltered

### PR DESCRIPTION
**Pull request by ashawley**
```
  * frameworks/Scala/unfiltered/setup_unfiltered.sh:
  Build is Scala 2.11, not 2.10

  * frameworks/Scala/unfiltered/src/main/scala/DatabaseAccess.scala:
  Use MySQL driver, not SQL Server

  * frameworks/Scala/unfiltered/src/main/scala/Plans.scala (Plans):
  Convert netty.cycle.Plan to netty.future.Plan
  (intent): Use new DBIO async facility of Slick 3
```

### CODE REVIEW

**Comment by ashawley** [comment]
Happy to rebase after 2389 is merged, or re-push if Travis resolves its MySQL issue on its own.

**Comment by mfirry** [comment]
@ashawley you might take this chance and add the `/plaintext` route test.

**Comment by knewmanTE** [comment]
@ashawley could you rebase this now that #2402 is merged in?

**Comment by knewmanTE** [comment]
@ashawley thanks! On the [Travis build](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/182175707), it looks like the `db` test is passing, but `json` and `query` are still failing. Any idea what could be causing that?

**Comment by nbrady-techempower** [comment]
Hi @ashawley ! Just wanted to ping you to let you know that we've made some setup changes. The databases now need to be included in your setup files with `fw_depends`. I'm going to close this. If you'd like to get this in to the next round, which we should be starting preview runs for right after the new year, could you make the necessary changes and reopen targeting master? Thanks for your contributions! :)

**Comment by mfirry** [comment]
Will adding just `fw_depends mysql` make it work?

**Comment by nbrady-techempower** [comment]
@mfirry yes, for mysql that will work. Looks like you may have had other issues? If your dev environment is vagrant, pull from master and do a fresh `vagrant up` in the vargrant-development directory to test.

**Comment by ashawley** [comment]
No worries.  For some reason the unfiltered.async was deadlocking after the first request. I never got around to resolving it.  I'll try to revisit it at some point.

**Comment by ashawley** [comment]
Feel free to merge though.  This PR does fix compilation.  Perhaps, someone else will come along and take it to the next level.

**Comment by nbrady-techempower** [comment]
@ashawley Ok, I will take a look at that if I have some time today and comment out the tests that are not working. I would like to be at a state where there are no failing tests in master.

**Pull request closed without merging**
