### PR TITLE
add support for Test type 6: Plaintext

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@jochenberger Would you mind checking out the conflicts? Also, a note that we are moving to warnings for text/plain responses that don't carry the charset="utf-8" parameter, and removing the warning for JSON responses that do not.

**Comment by jochenberger** [comment]
I updated the PR.
> and removing the warning for JSON responses that do not.

That's supposed to be "that do", right?

**Comment by nbrady-techempower** [comment]
@jochenberger Sorry if that was unclear. As it stands, we are warning if your JSON response is missing the charset=utf-8 parameter. This should not be the case, as there are no parameters for JSON application types. We're removing the warnings for JSON responses that do not have charset=utf-8.

**Comment by nbrady-techempower** [comment]
Pulled and tested locally as well as passing travis. Looks good! Thanks for your contributions @jochenberger

**Pull request merged**
