### PR TITLE
Added `oldaniel/zap`

### PR DESCRIPTION
**Pull request by oldaniel**
I did a local benchmark and realized `zap` is faster than `tokio-minihttp`, so I thought adding it would be nice, just to proof Rust's performance.

### CODE REVIEW

**Comment by oldaniel** [comment]
Any idea why [travis](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/303618716#L763) failed?

**Comment by nbrady-techempower** [comment]
> https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/databases/postgresql/create-postgres.sql#L11

classification can only be Fullstack, Micro, or Platform

**Comment by oldaniel** [comment]
@nbrady-techempower Uups, sorry for the problem. Thank you for the quick response.

**Comment by oldaniel** [comment]
@nbrady-techempower Still the same error. I think they're not recognizing the Test Dir path.

**Comment by nbrady-techempower** [comment]
@oldaniel I think you're looking at the wrong logs:
https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/303656275
```
Accessing URL http://TFB-server:8080/json:
  Response (trimmed to 40 bytes): "{"content":"Hello World"}"
   FAIL for http://TFB-server:8080/json
     Missing required key 'message'
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
```

**Comment by oldaniel** [comment]
Oh snap. I really should have took a bigger look at the requirements. I am really sorry for causing so many problems. Will fix that now.

**Comment by nbrady-techempower** [comment]
@oldaniel No worries at all! Let us know if you need any help

**Pull request closed without merging**
