### PR TITLE
Bump akka http

### PR DESCRIPTION
**Pull request by ckampfe**
@knewmanTE reopened against master as requested

### CODE REVIEW

**Comment by ckampfe** [comment]
@knewmanTE was this slated to make it into 13?

Round 12 akka-http was removed at the maintainer's request for being outdated. I'd hate to have the same thing happen to akka-http again given that the akka team has benched (internally) 2.4.9 as delivering marked improvements in throughput vs. older versions and the Spray framework. Round 11 is the last that I am seeing akka-http.

Thanks!

**Comment by knewmanTE** [comment]
@ckampfe do you have a link to where the maintainer requested removing it in round 12?

**Comment by ckampfe** [comment]
@knewmanTE https://twitter.com/rolandkuhn/status/704620217104736256, which was linked on the Round 12 page

**Comment by knewmanTE** [comment]
@ckampfe  thanks! We're taking a look now.

**Comment by nbrady-techempower** [comment]
@ckampfe Let's ping @rkuhn and see if he's ok with this.

**Comment by rkuhn** [comment]
Please coordinate with @ktoso, he's heading the Akka HTTP work.

**Comment by ktoso** [comment]
Hi there, yes, ok to include in the benchmarks again.

We're did most of the optimisation work (still ongoing but 2.4.9 marked the most changes we wanted to make).

I'll have a look at the code soon to see if it follows the best practices etc, thanks!

**Comment by nbrady-techempower** [comment]
@ktoso Great! We'll merge this in for round 13 for now :) Getting things set up for our new environments has taken much longer than we wanted it to, and once we kick that test off we our hopeful for a much quicker round turnaround. And thanks @ckampfe for your contributions!

**Comment by martin-g** [comment]
> I'll have a look at the code soon to see if it follows the best practices etc, thanks!

@ktoso Ping!

**Pull request merged**
