### PR TITLE
Update Tapestry to the latest version

### PR DESCRIPTION
**Pull request by jochenberger**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@jochenberger I pulled and tested this locally and it fails all tests. Switching back to the previous version works fine. It seems there are some breaking changes and isn't as simple as just updating the version number.

**Comment by jochenberger** [comment]
Yes, I'm monitoring the Travis build and noticed that too. I updated the PR and I'm waiting for the new build to finish.

**Comment by jochenberger** [comment]
Right, that wasn't as easy as I assumed it would be. Unfortunately the build logs don't contain much information that could help to debug the problem. Firing up the Vagrant VM...

**Comment by jochenberger** [comment]
That didn't help much either. The only information I could gather is from the log output:
```
Accessing URL http://127.0.0.1:8080/tapestry/hellodbs?queries=2 
CaseInsensitiveDict({'date': 'Wed, 23 Dec 2015 17:14:59 GMT', 'content-length': '329', 'content-type': 'text/html; charset=utf-8', 'connection': 'clos
e', 'server': 'Resin/4.0.41'})<html>
<title>Server Error</title>
<body>
<h1>Server Error</h1>
<p>The server is temporarily unavailable due to an
internal error.  Please notify the system administrator
of this problem.</p>
<pre><code>
Date: 2015-12-23T17:14:59.239+00:00
</code></pre>
<p /><hr />
<small>
Resin/4.0.41
Server: 'default'
</small>
</body></html>
```
Now I need to run, so I can't debug this any further right now.

**Comment by nbrady-techempower** [comment]
Ok, when you can http://tapestry.apache.org/release-notes-54.html
My guess is the problem stems from the removal of Javassist.

**Comment by jochenberger** [comment]
I'll have another look but I really don't know where to start. The webapp itself is fine AFAICT, so it's probably a problem with resin.

**Comment by jochenberger** [comment]
it seems to be a resin bug, in `~/FrameworkBenchmarks/installs/resin-4.0.41/log/jvm-default.log`, there's an entry
```
[08:25:13.769] jar:file:/home/vagrant/FrameworkBenchmarks/installs/resin-4.0.41/webapps/tapestry/WEB-INF/lib/guava-15.0.jar!/META-INF/beans.xml:5: <beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"> is an unexpected top-level tag.
               
               3:     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               4:     xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
               5:     bean-discovery-mode="none">
               6:   <!--
               7:   This file is here for bean-discovery-mode="none", which turns off CDI's behavior of assuming
               
               
               <beans xmlns="http://caucho.com/ns/resin">,
               <beans xmlns="http://java.sun.com/xml/ns/javaee"> or
               <beans xmlns=""> are expected.
               
               Syntax: (<beans> | <beans> | <beans>)
```
It looks as if it's trying to parse an XML comment.

**Comment by jochenberger** [comment]
No, the comment is not a problem, sorry, it doesn't like the `xmlns`.

**Comment by jochenberger** [comment]
https://github.com/google/guava/issues/1527#issuecomment-61353121 looks interesting.

**Comment by nbrady-techempower** [comment]
@jochenberger while this was going on we fixed a lot of the issues separately with #1836 #1837 and a Tapestry update was being worked on here #1684 
I'm inclined to close this and either continue the discussion in an issue or fix #1684

**Comment by jochenberger** [comment]
Well, #1684 is about Tapestry 5.3.8 while this one's about 5.4.0.

**Comment by msmith-techempower** [comment]
I think that this should supersede #1684, so I am reopening.

**Comment by nbrady-techempower** [comment]
@msmith-techempower FYI, seemed there were a lot of unrelated changes here, with only the pom file relating to Tapestry, and causing breaking changes. While the moonshine updates @blee-techempower committed here were separated out.

**Comment by jochenberger** [comment]
I rebased the branch onto current master.

**Comment by msmith-techempower** [comment]
Looks good; LGTM!

**Pull request merged**
