### PR TITLE
Use Revenj routes instead of .NET ones

### PR DESCRIPTION
**Pull request by zapov**
Revenj route can specify synchronous response.

### CODE REVIEW

**Comment by knewmanTE** [comment]
@zapov could you update your repo with the latest from master? We recently merged in a fix that should get Travis working again so we can verify your test.

**Comment by zapov** [comment]
I did.
btw. you've changed metadata so revenj.net is now called revenj, while revenj.jvm is still called revenj.jvm
Also, I think Mono missing from Platform is confusing people thinking that it's probably running on .NET core

**Comment by knewmanTE** [comment]
@zapov thanks! I'm not too familiar with the Platform/Flavor distinction, but perhaps @msmith-techempower can shed some light on it.

Sorry about the test names. Would you mind opening a PR to change it back? Also, could you update both of the test names in that PR to be lowercase so they better match the style of the other tests?

**Comment by zapov** [comment]
Well, I'm reluctant to change names at this point since this would mean results would drop from previous round.

**Comment by knewmanTE** [comment]
Hmm... @msmith-techempower @bhauer thoughts?

**Pull request merged**
