### PR TITLE
Micronaut 4

### PR DESCRIPTION
**Pull request by dstepanov**
FYI @graemerocher @sdelamo

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
Could we use properties, the default in Micronaut Framework 4,  instead of yml?

**Comment by dstepanov** [comment]
> Could we use properties, the default in Micronaut Framework 4, instead of yml?

That would improve the startup which is not benchmarked by the framework.

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]

**Comment by yawkat** [comment]
we need feedback from the vertx team before merging this

@franz1981

**Comment by franz1981** [comment]
@dstepanov Hi Denis, just curious, which bug was? is something related Vertx we have any responsability (and can fix)?

**Comment by franz1981** [comment]
@dstepanov thanks for sharing, hope will be fixed soon!!!

**Comment by dstepanov** [comment]
@nbrady-techempower Can you merge, please?

**Pull request merged**
