### PR TITLE
Initial php frameworks config

### PR DESCRIPTION
**Pull request by joanhey**
This configuration should be OK for all frameworks

### CODE REVIEW

**Comment by msmith-techempower** [comment]
Any reason for leaving out: `hhvm`, `php`, `peachpie`, and `workerman`?

**Comment by joanhey** [comment]
peachpie(.net) is not php.
hhvm I know less about it, and leave for later.
Workerman , :confused:  now I send it

**Comment by msmith-techempower** [comment]
[PeachPie](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/367601383) claims to be PHP.

**Comment by joanhey** [comment]
Peachie is a copy of php in .net

**Comment by msmith-techempower** [comment]
> Peachie is a copy of php in .net https://www.peachpie.io/

Wow, cool. Thanks!

**Comment by joanhey** [comment]
Travis-ci seems that it is blocked for this PR.
But this PR passed in my fork https://travis-ci.org/joanhey/FrameworkBenchmarks/builds/367705857?utm_source=github_status&utm_medium=notification

**Comment by nbrady-techempower** [comment]
Looks good, ill cancel the run here

**Pull request merged**
