### PR TITLE
Go/echo framework removal

### PR DESCRIPTION
**Pull request by nbrady-techempower**
Go/echo is pulling in go packages from a number of different repos without being tied down to any specific versions. I've tried a couple of combinations of versions without any luck.

@methane Just going to ping you here in case you wanted to take a look at bringing this back in, since I believe you were the one that updated it to v2.

### CODE REVIEW

**Comment by methane** [comment]
Please wait.  I'm checking what happens in echo.
At least, it drops fasthttp support and APIs for selecting http server are removed.
That's why build fails.

**Comment by nbrady-techempower** [comment]
I can hold off on this but the fix would have to include specific versions of the packages being used. Pulling packages direct from github repos at master causes occasional failures and doesn't keep a clean history of performance improvements.

**Comment by methane** [comment]
> Pulling packages direct from github repos at master causes occasional failures and doesn't keep a clean history of performance improvements.

Sadly speaking, all Go frameworks doesn't pin the version.
There are no defacto standard tool for pinning yet.

**Comment by methane** [comment]
https://github.com/methane/FrameworkBenchmarks/pull/8

**Comment by nbrady-techempower** [comment]
Can you 'go get' from local git repos? In that case we could pull in the source from a specific commit at runtime.

**Comment by methane** [comment]
I'm trying glide to lock dependency versions.

**Comment by nbrady-techempower** [comment]
Excellent! Hopefully that works out. If not I can explore more tomorrow. Thanks for all your work @methane!

**Comment by nbrady-techempower** [comment]
Closing in favor of #2450

**Pull request closed without merging**
