### PR TITLE
updating for a newer version of the framework

### PR DESCRIPTION
**Pull request by MTDdk**

### CODE REVIEW

**Comment by ssmith-techempower** [comment]
I'm not sure why this didn't trigger a Travis run. When I ran it locally the connection timed out when hitting the fortunes endpoint, but worked on all the other tests.

**Comment by MTDdk** [comment]
I experienced the same problem.

I will just try to pull the latest changes and test it again

**Comment by MTDdk** [comment]
Could you please test it again, now that I got Travis to build it?

**Comment by ssmith-techempower** [comment]
Looks good to me, merging in.

**Pull request merged**
