### PR TITLE
[C#][aspnetcore] feat - Upgrade to .NET 6 LTS

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
- [x] .NET 6 upgrade.
- [x] Implicite Usings.
- [x] Update Packages.
- [x] File-Scoped namespaces.
- [x] Ran `dotnet-format`
- [x] Target type initialization.  

Opening early for review...

cc @sebastienros @roji

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
for `aspnetcore-mono` getting below error. Seems like it cannot find files for 6.0.

image

**Comment by ShreyasJejurkar** [comment]
ICYMI @sebastienros

**Comment by sebastienros** [comment]
/cc @MichalStrehovsky for core-rt changes

LGTM

**Comment by ShreyasJejurkar** [comment]
Thanks for the input @sebastienros. 🙌

**Comment by MichalStrehovsky** [comment]
> /cc @MichalStrehovsky for core-rt changes

This is too big to review - the files under aspnetcore-corert should be bit-for-bit identical with aspnetcore except for the NuGet.config and .csproj.

@ShreyasJejurkar could you also fold #6888 into this? Then I can close that one. Otherwise we're just going to conflict. I don't understand the ordering by which pull requests get merged in this repo; the pull request has been open for a while. #6888 just brings RawDbMySqlConnector.cs and RawDbNpgsql.cs in sync, adds a `<IlcArg Include="--instructionset:sse4.2" />` line to the csproj and deletes `<RdXmlFile Condition=" '$(DatabaseProvider)' == 'Npgsql' " Include="npgsql.rd.xml" />` from the csproj (and deletes the file).

**Comment by ShreyasJejurkar** [comment]
Hi @MichalStrehovsky, I have merged your branch into mine. And also upgraded package versions, please have a look. 
Thanks.

**Comment by ShreyasJejurkar** [comment]
`aspnetcore-mono` still having issues.
image

**Comment by sebastienros** [comment]
My advice is to split this pr into separate ones per folder. This way one won't block the others, and it will be easier for each owner to review it. It should not be much more work to do that depending on your for experience.

**Comment by ShreyasJejurkar** [comment]
it's ok @sebastienros. I will just keep `aspnetcore` and `aspnetcore-corert` changes in their PR. Will revert `aspnetcore-mono` changes.

**Comment by ShreyasJejurkar** [comment]
Reverted `aspnetcore-mono`. This PR contains `aspnetcore` and `aspnetcore-corert` changes only and those are building successfully. 

@sebastienros can you please enable CI, so that at least we could see the build result?

**Review by MichalStrehovsky — APPROVED** [review]
Thank you! Assuming the *.cs files are now identical between aspnetcore and aspnetcore-corert.

**Review by sebastienros — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
@nbrady-techempower Could you please have a look? It looks good to merge if the CI passes but it needs someone's approval for the CI to run.

**Comment by MichalStrehovsky** [comment]
@ShreyasJejurkar looks like the CI triggered.

```
aspcore-corert-ado-pg-up: /app/BenchmarkApplication.cs(160,37): error CS0246: The type or namespace name 'PipeWriter' could not be found (are you missing a using directive or an assembly reference?) 
```

Could you please make sure the C# files are identical between aspnetcore and aspnetcore-corert? My signoff is conditioned on that. I just checked manually and 12 *.cs files are different.

**Comment by ShreyasJejurkar** [comment]
@MichalStrehovsky Ok let me check.

**Comment by ShreyasJejurkar** [comment]
I just ran `dotnet build` with .NET 6 in codespaces for the core-rt project, it build successfully there! 

image

**Comment by ShreyasJejurkar** [comment]
I compare the files between `aspnetcore` and `aspnetcore-corert` with file compare, found only some styled changes and nothing substantial. Fixed those changes with the latest commit as well!  https://github.com/TechEmpower/FrameworkBenchmarks/pull/6914/commits/8f6a0a3245ad7f20f6d9f8d2704a466b9d2dd5de

**Comment by MichalStrehovsky** [comment]
> I just ran dotnet build with .NET 6 in codespaces for the core-rt project, it build successfully there!

The build failure was specific to when you specify the Database property. Vanilla `dotnet build` worked in the CI as well (the plaintext and json benchmarks compiled successfully).

There are still differences in 3 C# files.

Could you please just copy over all the *.cs files from aspnetcore\PlatformBenchmarks to aspnetcore-corert\PlatformBenchmarks and commit that?

**Comment by ShreyasJejurkar** [comment]
@MichalStrehovsky Latest commit (https://github.com/TechEmpower/FrameworkBenchmarks/pull/6914/commits/7c02c52e80d420d3c9f19059f6d83faf4f09f520) is a result of the following command. 
```bash
@ShreyasJejurkar ➜ .../frameworks/CSharp/aspnetcore/PlatformBenchmarks (net-6 ✗) $ cp --parents `find -name \*.cs` ../../aspnetcore-corert/PlatformBenchmarks
```
Command copies all the *.cs files from `aspnetcore` to `aspnetcore-corert` keeping directory structure! 
There were 3 files modified, but with just a whitespace difference!

**Comment by sebastienros** [comment]
@ShreyasJejurkar @MichalStrehovsky Is there still something to do on this PR?

**Comment by ShreyasJejurkar** [comment]
CI has failed somehow, it's not C# code related! We can merge once CI gets green!

Please re-trigger it!

**Comment by nbrady-techempower** [comment]
@ShreyasJejurkar Would you mind pulling in the latest master here to get this to rerun. The mysql image was busted.

**Comment by ShreyasJejurkar** [comment]
on it

**Comment by ShreyasJejurkar** [comment]
@nbrady-techempower Done merging main! 

Thanks,

**Pull request merged**
