### PR TITLE
Update php5 to v5.6.30

### PR DESCRIPTION
**Pull request by joanhey**
v5.5.x has reached the end of life 9 months ago
Work in progress

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@joanhey Mind if I steal you if you have a moment? You're currently doing the most work in PHP. Do you happen to know how to disable gzip encoding for the php frameworks listed in #2646? It doesn't look like it's being done at the nginx level

**Comment by joanhey** [comment]
I will check it @nbrady-techempower

**Comment by joanhey** [comment]
Sorry for the merge

**Comment by joanhey** [comment]
mmm, closed the pull request to reomove work to travis, but it's the same

**Pull request closed without merging**
