### PR TITLE
sinatra-sequel updates

### PR DESCRIPTION
**Pull request by mwpastore**

### CODE REVIEW

**Comment by msmith-techempower** [comment]
This is the PR that would greatly benefit from #2495

**Comment by nbrady-techempower** [comment]
@mwpastore Thanks for the updates! Since you're in the area and if you have any time, would you mind taking a look at rails? Tests just recently started failing.

**Comment by mwpastore** [comment]
Successful build of sinatra-sequel is here: https://travis-ci.org/mwpastore/FrameworkBenchmarks/builds/191549113

I tweaked the commit messages so the shas may not match but otherwise the code is the same.

**Comment by nbrady-techempower** [comment]
@mwpastore Looks good, I'm just going to restart the ruby builds here. Github going down interrupted the travis run. Then we'll get this merged

**Comment by mwpastore** [comment]
@nbrady-techempower Not sure where you are with this but just got a bug resolved on another gem and updated this commit/PR to reflect. Sorry if that creates additional hassle for you.

**Comment by nbrady-techempower** [comment]
@mwpastore no worries. If you rebase with our current master you'll get our new travis changes, which will get you faster travis results

**Comment by mwpastore** [comment]
@nbrady-techempower Done!

**Pull request merged**
