### PR TITLE
Try to use FIFO scheduling policy (second attempt)

### PR DESCRIPTION
**Pull request by stefanocasazza**

### CODE REVIEW

**Comment by hamiltont** [comment]
Remember that very soon your `install.sh` file will not be able to use `sudo`. Are you sure this PR is needed?

**Comment by stefanocasazza** [comment]
Hi,

I'm not sure that sudo is strictly necessary.
I'm trying to use FIFO scheduling policy and for this I need 2 things:
1) the execution context of ULib server must have a limit for real-time
priority >0 (99): ulimit -r.
This should be satisfied by this 2 entry into /etc/security/limits.conf:
* hard rtprio 99
* soft  rtprio 99
2) the executable file program ULib server must have set the file
capabilities to be able to set real-time priority.
This should be satisfied by the setcap program in libcap2-bin package.

It is this PR needed?
I'm not sure I understand what you mean. ULib server work also without the
possibility to use real-time priority,
but I'm very curious to see how this feature would improve performance in
the TechEmpower peak environment...

Greetings

2015-07-18 17:07 GMT+02:00 Hamilton Turner <notifications@github.com>:

**Comment by stefanocasazza** [comment]
I am not able to rebase this request..
I am forced to refork...

Greetings
Stefano

**Comment by stefanocasazza** [comment]
I am not able to rebase this request.
I am forced to refork...

Greetings
Stefano

**Pull request closed without merging**
