### PR TITLE
Update phoenix to v0.17.0 (latest), fix config, make tests pass

### PR DESCRIPTION
**Pull request by thousandsofthem**
* phoenix version `0.17.0` now (latest ). was `0.13.0`
* Regenerated the phoenix app from scratch using all-default built-in generator (`mix phoenix.new`)
* Tuned config to match other apps (pool size i.e.)
* Now all tests passing without warnings
* Updated elixir `1.0.4` -> `1.0.5`
* Includes https://github.com/TechEmpower/FrameworkBenchmarks/pull/1729

### CODE REVIEW

**Comment by thousandsofthem** [comment]
"Round 11 Preview" numbers are off by factor of ~ten. Primary reason: Wrong pool size (way too low)

**Comment by thousandsofthem** [comment]
ugh ugh.
There are more recent update present (recently opened and already merged), phoenix 1.0.3 - https://github.com/TechEmpower/FrameworkBenchmarks/pull/1751
This one is outdated - phoenix v0.17.0

@blee-techempower could you please revert merge?

**Comment by msmith-techempower** [comment]
@thousandsofthem I'm not sure why GH thinks that this is merged; I just checked master and it is not. You should double-check to make sure, but I think that we are okay on this and GitHub is just being a little weird.

**Comment by thousandsofthem** [comment]
¯\\_(ツ)_/¯

okay, looks like files are untouched so all good here. thanks!

**Pull request merged**
