### PR TITLE
update to tapestry 5.3.8 and java8 (5.4-beta-31 exists)

### PR DESCRIPTION
**Pull request by based2**

### CODE REVIEW

**Comment by hamiltont** [comment]
blocking on changes requested in #1547

**Comment by zane-techempower** [comment]
Looks like this is close, but not quite there. Seems like there is a disagreement between jdk version and target release, in this case it seems like the target is 1.8 i.e. Java8. However the process is using Java7 to try to compile the code.

See: http://stackoverflow.com/questions/28291691/fatal-error-compiling-invalid-target-release-1-8-help-1

**Comment by msmith-techempower** [comment]
Will require `install.sh` to be updated to `fw_depends java8` from java7.

**Comment by mcocciaTE** [comment]
I can get everything to compile when I change source $IROOT/java7.installed it java8 in the setup.sh but it causes all of the tests to give a generic server error back. I'm looking more into why.

**Comment by mcocciaTE** [comment]
I believe the version of maven we use has an issue with java8. If we updated maven to 3.1.1+ it should work.

**Comment by mcocciaTE** [comment]
Updating maven did not seem to work. Poking around more.

**Comment by based2** [comment]
https://maven.apache.org/docs/3.3.3/release-notes.html
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12332054

**Comment by mcocciaTE** [comment]
So maven ended up working but redis was not. #1684 is my fixes which get everything happy.

**Pull request closed without merging**
