### PR TITLE
Add Roda+Sequel benchmarks

### PR DESCRIPTION
**Pull request by mwpastore**
This "hard fork" of sinatra-sequel swaps out Sinatra and Slim for Roda and Erubi. Otherwise it is almost exactly the same!

[ci fw-only Ruby/roda-sequel]

### CODE REVIEW

**Comment by knewmanTE** [comment]
This looks good to me! 

@mwpastore, out of curiosity, do the different platforms and servers make a noticeable difference in benchmark results? I ask just because Ruby tests have historically had a large number of tests per framework and given that each additional test implementation adds to the total time it takes to run the suite, it would be great if we could find a way to trim down on the total number of Ruby tests. From a quick look at our Round 13 results, it looks like Thin consistently performs the worst across all Ruby tests, Unicorn performs the best, and Puma is a little lower than Unicorn.

**Comment by mwpastore** [comment]
That's fair, and the number of Ruby frameworks is ever-increasing (sorry), so we have some quadratic growth here. Puma, Unicorn, and Passenger are the three most popular Ruby app servers, so I would definitely like to keep those, and JRuby+TorqueBox seems to be the best massively-multithreaded option today (given the somewhat sorry states of Rubinius and JRuby web servers such as Trinidad, Jubilee, Fishwife). I would be comfortable removing JRuby+Puma, would that be helpful?

**Comment by knewmanTE** [comment]
Yeah, that would probably be helpful! I'll make an Issue where maybe we can solicit some feedback from any other Ruby developers who might have strong opinions one way or another.

**Comment by knewmanTE** [comment]
@mwpastore actually, looking at some of our other Ruby tests, it looks like we no longer have any JRuby or Puma tests anyway, so maybe just open up a new PR that removes those tests from your two recent framework additions?

**Comment by mwpastore** [comment]
@knewmanTE @nbrady-techempower removed JRuby in #2277 with the intention of adding it back in for Round 14. I [offered](https://github.com/TechEmpower/FrameworkBenchmarks/issues/2074#issuecomment-263682641) to add it back in for sinatra-sequel and carried the change through to rack-sequel and roda-sequel.

**Comment by knewmanTE** [comment]
Ahh, right you are! I'm fine keeping it as-is for now then. (sorry for the confusion, I'm still catching myself up on all of the setup and Travis changes that were implemented over the past couple months).

**Comment by mwpastore** [comment]
No worries! It's been quite a whirlwind of activity. The new setup and Travis configuration is pretty fantastic.

**Comment by knewmanTE** [comment]
Yeah, we're pretty stoked about it! Having an all-green Travis is a dream come true!

**Pull request merged**
