### PR TITLE
Update SNUnit benchmark and dependencies

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by volyrique** [comment]
Note that PR #7928 marks SNUnit as a broken implementation, so you could use this opportunity to fix it.

**Comment by joanhey** [comment]
SUnit is using Nginx Unit, and all the frameworks using it pass the Github Actions.
Nginx Unit fail only in Citrine, not when testing in local or Github actions.

**Comment by lolgab** [comment]
> Note that PR #7928 marks SNUnit as a broken implementation, so you could use this opportunity to fix it.

The problem is in NGINX Unit, not specific to the Scala framework. I'm updating to the latest `1.29.1` that got released some days ago.

**Comment by volyrique** [comment]
You need to remove the broken tag.

**Comment by lolgab** [comment]
> You need to remove the broken tag.

Done ✅

**Pull request merged**
