### PR TITLE
update

### PR DESCRIPTION
**Pull request by luyikk**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
hey @luyikk ! Would you mind removing the binary files. Those shouldn't be stored here. If they're required for the tests to run they should be imported via packages.

**Comment by nbrady-techempower** [comment]
Please remove:

```
BIN +14.5 KB .vs/FrameworkBenchmarks/v16/.suo 
BIN +908 KB .vs/FrameworkBenchmarks/v16/Browse.VC.db
```

**Comment by luyikk** [comment]
Okay thanks

**Comment by luyikk** [comment]
@nbrady-techempower  hey please check

**Comment by nbrady-techempower** [comment]
Hey @luyikk Can you merge in the current master. I'd like this to run again with some new verifications we've put in.

**Pull request merged**
