### PR TITLE
Hapi fix

### PR DESCRIPTION
**Pull request by nbrady-techempower**
The default test for hapi was also trying to spin up redis. We currently do not have a working redis setup.

### CODE REVIEW

**Comment by LadyMozzarella** [comment]
Could we just delete the implementation instead of commenting it out?

**Comment by nbrady-techempower** [comment]
@LadyMozzarella We may be adding redis back in, so for tests that are failing because redis was removed I was just planning on keeping the author's original implementation in code. It may be helpful for people who are looking at the current implementation, wondering what the intent was. Since I don't know if they would have done things differently had they known they couldn't use redis, this might be the best way for now.

**Comment by nbrady-techempower** [comment]
Nonetheless, this one passed locally but isn't passing travis so I will have to revisit in a moment.

**Comment by LadyMozzarella** [comment]
In that case, can you add a comment with that information while you're in there?

**Comment by nbrady-techempower** [comment]
Will do.

**Comment by nbrady-techempower** [comment]
All green! merging

**Pull request merged**
