### PR TITLE
Python webware

### PR DESCRIPTION
**Pull request by knewmanTE**
Adds [Webware](http://www.webwareforpython.org/), the first of the historical Python frameworks mentioned in #1540

### CODE REVIEW

**Comment by hamiltont** [comment]
rebase and/or merge please

**Comment by knewmanTE** [comment]
@hamiltont merged the latest changes from master into this branch.

**Comment by knewmanTE** [comment]
Webware is passing fine. Random other tests are causing travis to return a fail.

**Comment by hamiltont** [comment]
LGTM!

**Comment by msmith-techempower** [comment]
@hamiltont @knewmanTE Why did we allow this insane sub-subfolder hierarchy?

**Comment by knewmanTE** [comment]
@msmith-techempower I think it came up in #1540, specifically [here](https://github.com/TechEmpower/FrameworkBenchmarks/issues/1540#issuecomment-95282340).

**Pull request merged**
