### PR TITLE
Simplify Revenj setup.

### PR DESCRIPTION
**Pull request by zapov**
Add DSL Platform as language dependency.
Move Java compilation to Maven plugin.
Add missing Fortunes implementation.

### CODE REVIEW

**Comment by msmith-techempower** [comment]
All tests pass in Travis-CI.

**Comment by zapov** [comment]
Updated due to poor Git conflict handling ;(

**Comment by nbrady-techempower** [comment]
Hi @zapov we are getting ready to start our preview runs for round-13. In the meantime we are preparing to start work on verifying pull requests for round-14. Because of this, we are slightly restructuring our branches. Would you mind closing this and making a pull request that targets the new round-14 branch? Thanks!

Here's more information: http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Contributing-Guide/#github-pull-request-procedure

**Comment by zapov** [comment]
Sure

**Pull request closed without merging**
