### PR TITLE
Update actix-* yarte fortunes 

### PR DESCRIPTION
**Pull request by botika**
Update yarte implementation in `actix-*` fortunes, less `actix-diesel` (here yarte has no effect), for compare different actix implementations with the same behavior.

### CODE REVIEW

**Comment by botika** [comment]
It seems to me that @robjtede is in charge of this? 

You can confirm this that I want to see the difference between the implementation in an actor and the direct implementation.

**Review by robjtede — COMMENTED** [review]
not 100% familiar with yarte or what the implications of this change is but *looks* sensible

**Review by robjtede — APPROVED** [review]

**Comment by botika** [comment]
Yarte now is using direct `tokio-bytes` implementation through the `buf-min` trait giving it a higher performance by implementing all the runtime at a low level with the use of raw pointers and simd instructions .

**Comment by sebastienros** [comment]
+10% RPS, -10% mean latency on my tests, good job!

**Comment by sebastienros** [comment]
image

**Pull request merged**
