### PR TITLE
Update actframework project to act-1.5.1

### PR DESCRIPTION
**Pull request by greenlaw110**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@greenlaw110 this just needs `useSSL=false` to solve the ebean-mysql failures

**Comment by greenlaw110** [comment]
@nbrady-techempower how can I specify `useSSL=false`?

**Comment by greenlaw110** [comment]
@nbrady-techempower Looks like this time act tests all passed! However there are other framework tests failures

**Comment by nbrady-techempower** [comment]
@greenlaw110 Perfect! Thanks for adding that!

**Comment by greenlaw110** [comment]
@nbrady-techempower brilliant! Thank you!. 

BTW will this PR enter the next preview round? and do you have lead time for the preview round3 result available?

**Comment by nbrady-techempower** [comment]
@greenlaw110 This will probably miss the next preview. I think we're wrapping it up. Getting the logs together and should be up any day now. But we'll probably be doing one or two more before we post final.

**Comment by greenlaw110** [comment]
@nbrady-techempower cool! thanks to all you guys setting up this platform!

**Pull request merged**
