### PR TITLE
Haskell/Yesod tests: Code reorg

### PR DESCRIPTION
**Pull request by saurabhnanda**
Code reorganisation according to the following comments:

* https://github.com/TechEmpower/FrameworkBenchmarks/pull/2247#issuecomment-243642866
* https://github.com/TechEmpower/FrameworkBenchmarks/pull/2247#issuecomment-243787321

### CODE REVIEW

**Comment by saurabhnanda** [comment]
@msmith-techempower @nbrady-techempower please review this PR. The Yesod tests are passing Travis CI. Don't know why the other stuff is failing -- I didn't touch anything else in my branch. 

In Travis CI, will Yesod show up as one entry or two entries - yesod-mysql and yesod-postgres?

**Comment by msmith-techempower** [comment]
@saurabhnanda Agreed, Travis-CI passes. Let's get this merged into round-14 since it just code reorganization.

**Comment by saurabhnanda** [comment]
Okay. When is the next round of preliminary (or final) results out?

On 6 Sep 2016 11:00 pm, "Mike Smith" <notifications@github.com> wrote:

@saurabhnanda <https://github.com/saurabhnanda> Agreed, Travis-CI passes.
Let's get this merged into round-14 since it just code reorganization.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TechEmpower/FrameworkBenchmarks/pull/2258#issuecomment-245015713>,
or mute the thread

**Comment by knewmanTE** [comment]
@saurabhnanda would you mind closing this PR and re-opening it against the round-14 branch?

re: the next results, we're going to run a second preview round this weekend on our high-performance hardware setup with the plan of publishing the results next week. The Round 13 Final run should follow shortly after across both of our test environments.

**Pull request merged**
