### PR TITLE
Fix mongo login and bump vert.x core version to latest stable 3.3.2

### PR DESCRIPTION
**Pull request by pmlopes**

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Oops, sorry @pmlopes I didn't realize this was target to the master branch. Would you mind targeting the round-14 branch with this? Master has been frozen and is currently pulled into our test environments for preview. All framework enhancements will now go toward a `round-##` branch.

**Comment by pmlopes** [comment]
Sure. I'll take care of it tomorrow if that is not a problem.

**Comment by nbrady-techempower** [comment]
@pmlopes of course! thanks!

**Comment by pmlopes** [comment]
new PR targeted the correct branch is created.

**Pull request closed without merging**
