### PR TITLE
reimplemented Gemini-Postgres due to Travis error

### PR DESCRIPTION
**Pull request by knewmanTE**
See the original [merge request](https://github.com/TechEmpower/FrameworkBenchmarks/pull/1336)

Broke off a clean branch from master and reimplemented the changes for the Gemini Postgres test after tests passed locally but failed on Travis.

### CODE REVIEW

**Comment by hamiltont** [comment]
@knewmanTE @msmith-techempower Is there any way to download the contents of the WEB-INF/lib directory instead of storing them into this repository? One of the things we found over in #1050 was that these 0-4MB binary files are the majority of the repository's 120MB `.git` folder, so I'd advocate for always requiring PRs to download such dependencies

**Comment by msmith-techempower** [comment]
@hamiltont The answer is "yes" for everything except the gemini jar-file, since it is not open source. I could spend some time and convert everything to maven and only include a `POM.xml` and 1 ~4mb jar file.

**Comment by msmith-techempower** [comment]
This still seems to be failing. I'll check it out and take a look.

**Comment by msmith-techempower** [comment]
I have no idea why Travis is failing on this - I created a new VM image and tested `gemini-postgres` and it worked fine. LGTM!

**Comment by hamiltont** [comment]
Linking to #1119 - perhaps related?

**Comment by msmith-techempower** [comment]
OH, that's a good point. Almost certainly related to #1119

**Pull request merged**
