### PR TITLE
[vapor-postgres] Add database updates test

### PR DESCRIPTION
**Pull request by vojtarylko**

### CODE REVIEW

**Comment by vojtarylko** [comment]
@nbrady-techempower Can you approve running workflows?

**Comment by nbrady-techempower** [comment]
@vojtarylko done

**Comment by vojtarylko** [comment]
@nbrady-techempower Thanks. Should I do something to get this merged?

**Comment by nbrady-techempower** [comment]
@vojtarylko No, it just needed to pass CI. All set.

**Pull request merged**
