### PR TITLE
Add digitalocean to vagrant setup

### PR DESCRIPTION
**Pull request by hamiltont**
If someone could test this before we merge that would be appreciated. I'd like to ensure it's working outside of my personal environment

### CODE REVIEW

**Comment by hamiltont** [comment]
BTW, if you use [this referral link of mine](https://www.digitalocean.com/?refcode=9296d86938f2) you get $10 free on Digital Ocean. I've been using it for a week straight and racked up a whopping $0.16 bill, so...$10 is a good deal :-P

**Comment by victorbriz** [comment]
Here are the issues I faced during digital_ocean TFB testing:
1a. ssh keys cannot be non-standard, provision fails (ssh-agent not used similar to  help.github.com/articles/generating-ssh-keys/)
1b. setup fails if ssh public key was manually added to digital ocean
https://gist.github.com/victorbriz/dd8c4a4a10419c4610b2

2. benchmark test fails, possible permission issues (couldn't open temporary file ./sedwKhiN6: Permission denied)
https://gist.github.com/victorbriz/dd8c4a4a10419c4610b2

**Comment by hamiltont** [comment]
> probably 512MB is too low for TFB on DO.

Definitely. I'll have to add that to the readme, I'm hesitant to set the default higher than this minimum value

> Setup vertx: sed: couldn't open temporary file ./sedhRLbjM: Permission denied

Huh, wonder if my provisioning script is not properly setting folder permissions

**Comment by victorbriz** [comment]
Yep, deploying on local virtualbox permissions on ~/FrameworkBenchmarks are set 777, so:
sudo -u testrunner touch ~/FrameworkBenchmarks/frameworks/Java/vertx/setup.sh
succeeds, while on DO permissions are 664/665:
sudo -u testrunner touch /home/ubuntu/FrameworkBenchmarks/frameworks/Java/vertx
touch: setting times of ‘/home/ubuntu/FrameworkBenchmarks/frameworks/Java/vertx’: Permission denied
So you just need "sudo chmod -R 777 /home/ubuntu/FrameworkBenchmarks" in provisioning script for TFB-DO (I just did that manually and vertx test run successfully)

**Comment by msmith-techempower** [comment]
Considering this pull request dead; will reopen if interest in digitalocean comes up down the line.

**Pull request closed without merging**
