### PR TITLE
Fix the validation issue when initialization happens in less than 1000ms

### PR DESCRIPTION
**Pull request by pmlopes**
Citrine is a fast environment and the startup of the application happens in less than 1 second. For this reason the validation of the test some times fails as the date header is not properly initialized.

### CODE REVIEW

**Comment by bhauer** [comment]
Ha!  Super-fast start-up problems, huh?  ;)  What a fun problem to have.

**Comment by pmlopes** [comment]
@bhauer  🤷 woops!

BTW the CI test failed not because it was fast but due to some package fetch fail on docker, how can we request a new run?

**Comment by zloster** [comment]
@pmlopes The most recent PRs all failed with this error. See for example https://github.com/TechEmpower/FrameworkBenchmarks/pull/4729#issuecomment-489390148
Probably some change in the toolset is required.

**Comment by nbrady-techempower** [comment]
@pmlopes I'm trying to test this locally because of travis failures and getting this:

```
--------------------------------------------------------------------------------
Running Test: vertx-web
--------------------------------------------------------------------------------
vertx-web: Step 1/7 : FROM maven:3.5.3-jdk-10-slim as maven
vertx-web:  ---> 276091e24d4f
vertx-web: Step 2/7 : WORKDIR /vertx-web
vertx-web:  ---> Using cache
vertx-web:  ---> f707c2c7dbad
vertx-web: Step 3/7 : COPY scripts scripts
vertx-web:  ---> Using cache
vertx-web:  ---> 262502ffbd7e
vertx-web: Step 4/7 : COPY src src
vertx-web:  ---> Using cache
vertx-web:  ---> b4a08ecb4c0d
vertx-web: Step 5/7 : COPY pom.xml pom.xml
vertx-web:  ---> Using cache
vertx-web:  ---> abdff7d222d2
vertx-web: Step 6/7 : RUN mvn package -q
vertx-web:  ---> Running in b567888fe38a
vertx-web: [ERROR] COMPILATION ERROR :
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[504,5] illegal start of expression
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[506,22] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[506,23] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[516,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[516,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[522,6] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[528,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[528,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[529,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[529,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[530,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[530,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[537,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[537,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[538,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[538,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[539,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[539,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[545,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[545,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[546,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[546,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[547,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[547,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[554,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[554,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[555,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[555,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[556,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[556,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[564,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[564,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[570,6] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[572,27] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[572,29] ';' expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[574,1] class, interface, or enum expected
vertx-web: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project vertx-web-benchmark: Compilation failure: Compilation failure:
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[504,5] illegal start of expression
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[506,22] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[506,23] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[516,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[516,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[522,6] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[528,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[528,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[529,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[529,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[530,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[530,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[537,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[537,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[538,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[538,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[539,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[539,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[545,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[545,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[546,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[546,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[547,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[547,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[554,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[554,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[555,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[555,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[556,14] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[556,15] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[564,12] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[564,13] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[570,6] illegal start of type
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[572,27] <identifier> expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[572,29] ';' expected
vertx-web: [ERROR] /vertx-web/src/main/java/io/vertx/benchmark/App.java:[574,1] class, interface, or enum expected
vertx-web: [ERROR] -> [Help 1]
vertx-web: [ERROR]
vertx-web: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
vertx-web: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
vertx-web: [ERROR]
vertx-web: [ERROR] For more information about the errors and possible solutions, please read the following articles:
vertx-web: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
vertx-web: Removing intermediate container b567888fe38a
vertx-web: Docker build failed; terminating
vertx-web: Traceback (most recent call last):
vertx-web:   File "/FrameworkBenchmarks/toolset/utils/docker_helper.py", line 57, in __build
vertx-web:     raise Exception(token['errorDetail']['message'])
vertx-web: Exception: The command '/bin/sh -c mvn package -q' returned a non-zero code: 1
vertx-web: Build time: 31s
vertx-web: ERROR: Problem starting vertx-web
```

**Comment by pmlopes** [comment]
@nbrady-techempower I've verified all issues on all tests:

* vertx-web
* vertx-web-postgres
* vertx-web-susom-postgres
* vertx-web-mongodb

And fixed the issue of the unset date header, plus the minor warning about not having a `README.md` (renamed the old `Readme.md`).

I also took the freedom to bump the dependencies to the latest stable release versions. It all passes on my local environment, so I expect it to be green on CI too.

**Comment by nbrady-techempower** [comment]
thanks @pmlopes !

**Pull request merged**
