### PR TITLE
Add FaF (rust) framework

### PR DESCRIPTION
**Pull request by errantmind**
Add FaF (rust) framework

### CODE REVIEW

**Comment by fafhrd91** [comment]
to me this doesnt look like framework

**Comment by errantmind** [comment]
I suppose that depends on your criteria for a framework. It is minimal, but I think it would satisfy basic criteria. It it an event loop which parses the complete HTTP request and passes everything to the 'user' in a callback who can define the response how they want.  I'd like to get this merged ASAP for testing so if there is a concrete issue please let me know.

**Comment by fafhrd91** [comment]
sure, you can call framework anything that provides callback. but to me this still looks like bunch of low level code.

**Comment by errantmind** [comment]
I generally appreciate feedback but I don't see how that is a useful criticism.  The goals / values for this framework are speed and simplicity of design.  If it is `low level`, it is because it has very few dependencies: it implements its own event loop and manages its own threads, which is going to be 'low level' by definition. Is this because it is a source distribution and not a regular library?

**Comment by nbrady-techempower** [comment]
Hi @errantmind,

Is it possible to get a lot of this low level code in a lib/crate so it's not all committed here?  Could you also tie this down to a specific version, not latest: `FROM errantmind/debian-faf`

**Comment by errantmind** [comment]
@nbrady-techempower Sure, I made the changes

**Pull request merged**
