### PR TITLE
Travis has not been configured properly for redis

### PR DESCRIPTION
**Pull request by hamiltont**
See my comment at https://github.com/TechEmpower/FrameworkBenchmarks/issues/1661#issuecomment-111341509

### CODE REVIEW

**Comment by zane-techempower** [comment]
I took a look around w.r.t. getting Redis working on travis. It seems that we could use `Redis 2.8.4` on travis fairly easily: http://docs.travis-ci.com/user/database-setup/#Redis
This is the version of `redis-server` that gets installed with `apt-get` so I'm assuming that that's what Travis will do if the option is activated. 

What sort of blockers are there to upgrading TFB to Redis 2.8.4? I wouldn't mind undertaking adding Redis, but I suspect there are issues beyond my knowledge.

**Comment by hamiltont** [comment]
> I took a look around w.r.t. getting Redis working on travis. It seems that we could use Redis 2.8.4 on travis fairly easily: http://docs.travis-ci.com/user/database-setup/#Redis

Actually it's not too hard. Looking [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/database.sh#L278), you *don't* want to overwrite the configuration they use on travis, but you *do* want to run the bash script to populate the database. Remember - for travis we don't care about performance tuning, we just want it to turn on and have the correct data when the verification runs. 

> What sort of blockers are there to upgrading TFB to Redis 2.8.4?

From my understanding, the upgrade *might* break some of our configuration options because they occasionally change the valid options (and redis refuses to start with a bad config, IIRC). You would also probably have to modify [inside here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/database.sh#L248) a little bit to keep our minimal database support on ubuntu 12.04.

**Comment by zane-techempower** [comment]
Sounds good to me, thanks for the tips. I will put this on my todo list.

**Comment by msmith-techempower** [comment]
I BELIEVE this was resolved with our latest Travis-CI updates to master.

@ssmith-techempower Please confirm

**Comment by blee-techempower** [comment]
"Travis has not been configured properly for redis." which is right.

For this reason, Crystal/Moonshine, hapi, nodejs and other frameworks which use redis fail the Travis test. 

So, I edited " .travis.yml " like this: https://github.com/TechEmpower/FrameworkBenchmarks/commit/9e61a671fb0cff32c2c5748a9498286f8bf182bd

After this change, the frameworks which fail travis test due to redis pass travis test.

**Comment by kbrock** [comment]
@blee-techempower this is great. thanks so much

**Pull request closed without merging**
