### PR TITLE
nodejs framework update

### PR DESCRIPTION
**Pull request by nbrady-techempower**
Fixed typo in helper.js and updated dependencies.

Rebased after redis fix to see it pass travis.

### CODE REVIEW

**Comment by blee-techempower** [comment]
Without adding redis information on ".travis.yml" file, it will not pass the test.

**Comment by nbrady-techempower** [comment]
@blee-techempower the redis information has already been merged into master, there seems to be another problem

**Comment by blee-techempower** [comment]
@nbrady-techempower 
I think you did not merge or rebase correctly.
Check line 236 : https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/99541375
236: ./config/create-redis.sh: 5: ./config/create-redis.sh: let: not found

shebang #!/bin/bash is still missing!

**Comment by nbrady-techempower** [comment]
@blee-techempower you were looking at an earlier build before the shebang was merged in to master, look at the travis-ci/pr it has completed successfully and ready to be merged

**Comment by nbrady-techempower** [comment]
See https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/99541580 for complete successful test

**Comment by blee-techempower** [comment]
Cool!

Can you check ulib and other stuffs that I pushed?


On 12/31/15 8:28 AM, Nate wrote:
> @blee-techempower <https://github.com/blee-techempower> you were looking
> at an earlier build before the shebang was merged in to master, look at
> the travis-ci/pr it has completed successfully and ready to be merged
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TechEmpower/FrameworkBenchmarks/pull/1835#issuecomment-168216841>.
> 

-- 
Best,
Byung Lee

**Comment by nbrady-techempower** [comment]
@blee-techempower Sure, right after my coffee! Thanks for checking this out.

**Comment by blee-techempower** [comment]
@nbrady-techempower Good. Your old test was in queue, so I did not notice that its old one.

**Comment by msmith-techempower** [comment]
The latest test on this seems to pass; LGTM!

**Comment by nbrady-techempower** [comment]
@msmith-techempower this is RTBM if you agree. Solves some issues. Don't want to merge my own PRs.

**Pull request merged**
