### PR TITLE
[verif] Update swoole pool

### PR DESCRIPTION
**Pull request by jcheron**
### Updated
Compliance with the [new verification](https://github.com/TechEmpower/FrameworkBenchmarks/pull/5145) procedure.
- Swoole did not execute all the db queries (1/4 were lost).
-> Changing the initialization of the connection pool
ping @twose for checking

### CODE REVIEW

**Comment by twose** [comment]
it looks good to me except for some code style :)
And I can not understand why it is `intdiv(512, $srv->setting['worker_num'])`, I think there should be a configuration here instead of hard coding...

**Comment by jcheron** [comment]
Thank you @twose 
I agree with you about the code style.
I left it as is, the priority being elsewhere for the moment.

For the initialization of the pool, what do you propose instead of `intdiv(512, $srv->setting['worker_num'])`?
The number of workers varies.

**Comment by twose** [comment]
I don't know how much the stress of TechEmpower is, so I don't know why 512 instead of some other number
I have no suggestion, we adjust configs based on test results

**Comment by jcheron** [comment]
> I don't know how much the stress of TechEmpower is, so I don't know why 512 instead of some other number

512 is the maximum level of concurrency for Db tests.
It varies between 16 and 512 depending on the tests ([Db](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#single-database-query), [Query](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries), [Fortunes](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#multiple-database-queries) and [Update](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#database-updates)).

**Pull request merged**
