### PR TITLE
Big Travis run - Do Not Merge

### PR DESCRIPTION
**Pull request by nbrady-techempower**
**Problem** 
#2482 made me think of this. After doing the db split and other toolset changes in the past, I realize that some tests might not work correctly unless one of the previous tests in that framework already ran. This shouldn't be the case; each test should work on its own.

**Test for Problems**
I made a *temporary* change to travis to run every test individually, spinning up a new vm every time. This isn't meant to be merged, but just as a one time pass to see if there are any other tests that are failing if they're not run after the other tests in their framework.

So, let's see what travis do.

##### Some tests will break since I didn't take the time to test for os. Just listed all the tests with `--list-tests`, output to a file, quick `sed` to turn it into a travis matrix.

### CODE REVIEW

**Comment by methane** [comment]
#2481 is "big travis run" already.
And #2486 will be too.

**Comment by nbrady-techempower** [comment]
@methane no this  is different. Those are one vm per framework directory.  This is one vm per test.

**Comment by methane** [comment]
Ah, I see.

**Comment by msmith-techempower** [comment]
This would be a mean thing to do; going from 174 to 360 Travis-tests is just painful.

**Comment by nbrady-techempower** [comment]
@msmith-techempower I noted it's not meant to ever be merged or changed. I wanted to do a one time pass to see what other tests like `nodejs` were failing. Found and fixed `hapi` from this.

**Comment by msmith-techempower** [comment]
Ah, I think I see.

This is really interesting. Ideally, we WOULD be able to set up our Travis-CI this way, but it is just too punitive generally. Let's add this is a step to take every now and then (open a new branch with `travis.yml` built this way, throw it against the wall, and see what sticks).

**Comment by nbrady-techempower** [comment]
@msmith-techempower: i can make a script and throw it in the `travis` directory that will generate a `.travis.yml` file like this based on the existing tests.

**Pull request closed without merging**
