### PR TITLE
Update framework version to 1.3.5

### PR DESCRIPTION
**Pull request by jamming**

### CODE REVIEW

**Comment by blee-techempower** [comment]
3 tests: fortune, db, query failed.
```
 Verification Summary
| Test: sabina
|       fortune     : FAIL
|       plaintext   : PASS
|       db          : FAIL
|       update      : PASS
|       json        : PASS
|       query       : FAIL

```

**Comment by jamming** [comment]
I would like to request some help here. When I run the tests from my fork (inside the vagrant-development VM) they pass, but they always fail in Travis.

How could I replay the error in my local environment?

**Comment by msmith-techempower** [comment]
We still have issues with Travis that need to be addressed - we will check this out and run it locally to test it before merging, rather than relying on Travis.

**Comment by jamming** [comment]
Ok, thank you for the information!

**Comment by jamming** [comment]
Retest this please

**Comment by jamming** [comment]
Could you please send an update about the Travis problems? should I pick your latest master changes?

**Comment by msmith-techempower** [comment]
@jamming We have just pushed a bunch of Travis-CI fixes into master; if you could rebase your branch from our master and push the changes, Travis-CI should be able to test automatically.

**Comment by jamming** [comment]
Mmmm... My framework pass the tests but others don't, will it be merged?

**Comment by msmith-techempower** [comment]
Yes, your tests pass: https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/96141934

LGTM!

**Pull request merged**
