### PR TITLE
Set keep-alive to 0 for rocket and make the randomizer output unique numbers from a shuffled array

### PR DESCRIPTION
**Pull request by vegai**
Rocket devs in https://github.com/SergioBenitez/Rocket/issues/1038 suggest that the default keep-alive -setting might cause problems for Rocket.

### CODE REVIEW

**Comment by vegai** [comment]
`   FAIL for http://tfb-server:8000/updates?q=20

     Only 10106 rows updated in the database out of roughly 10240 expected.`

on the Rocket test. I guess this wasn't so simple after all :) Everything else passed though, so this is slightly weird.

**Comment by vegai** [comment]
So I closed/reopened the PR to trigger a rebuild and the 2nd one passed. Slightly weird.

**Comment by nbrady-techempower** [comment]
@vegai it's not consistent. I reran and it failed again. You may need to make sure that the random number you generate is unique, a solution that some of the Java frameworks use.

**Comment by vegai** [comment]
I merely changed the keep-alive -setting though. Do you think that the Rocket test was broken also before this change and something else needs to change to stabilize it? Or that the keep-alive change alone made it unstable?

**Comment by nbrady-techempower** [comment]
It was probably failing verification before this when we added stricter verification testing to the toolset. Probably not a result of your changes but we don’t want to merge broken tests. You could remove that single test to get this merged or if you want to take a shot at fixing it.

**Comment by vegai** [comment]
I can give it a shot. I see that 

```
fn random_number() -> i32 {
    rand::thread_rng().gen_range(1, 10_001)
}
```

You mean this test fails if the same number is generated more than once here? I guess it would be against the rules to just pick sequential numbers? :)

**Comment by nbrady-techempower** [comment]
Haha, yeah no sequential numbers. My guess, from seeing it happen with a couple of other frameworks, is that there is some caching mechanism somewhere that stops a request from hitting the database if it's a number it has already seen.

**Comment by vegai** [comment]
Meh, too difficult, I think I'll give up on this :)

**Comment by vegai** [comment]
Meh, too difficult, I think I'll give up on this :)

**Comment by vegai** [comment]
Seems to have worked now several times. Hopefully I didn't crap on rocket's performance by my code too badly.

**Comment by fraunos** [comment]
@vegai thanks for your input - I'd love to see how rockey performs, can't wait for another round

**Pull request merged**
