### PR TITLE
Add libreactor

### PR DESCRIPTION
**Pull request by fredrikwidlund**
First attempt to add the libreactor framework to the benchmark.

### CODE REVIEW

**Comment by blee-techempower** [comment]
@fredrikwidlund Hello, fredrikwidlund. First of thank you for your contribution. It seems like libreactor is a framework which uses C language, and your travis-ci test result dos not have information about libreactor. Please update your ~/FrameworkBenchmarks/.travis.yml . You just need to add "TESTDIR=C/libreactor" under env: matrix

Thanks.

**Comment by fredrikwidlund** [comment]
Added. The libreactor test seems to pass.

**Comment by blee-techempower** [comment]
Local test passed.
'''
 Verification Summary

| Test: libreactor
|       plaintext   : PASS
''''

**Comment by msmith-techempower** [comment]
This looks good to me; LGTM!

**Pull request merged**
