### PR TITLE
Add sinatra-sequel-puma-jruby benchmark 

### PR DESCRIPTION
**Pull request by mwpastore**
### sinatra-sequel on JRuby

* Make sinatra-sequel framework compatible with JRuby 9K
* Add runner, language setup, and benchmark config for sinatra-sequel-puma-jruby
* Bug Fix: sinatra-sequel framework was applying updates on /updates, but returning the original records (instead of the updated records)

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
@mwpastore I'm getting a fail for update - see log: http://sprunge.us/IRJJ

**Comment by mwpastore** [comment]
@nbrady-techempower It would help a great deal if I could decide whether I want to use a Hash or an Array there. File under "I swear I tested that." :-) Please try again?

**Comment by nbrady-techempower** [comment]
@msmith-techempower these all pass without warning but wanted to ping you to examine the ruby toolset changes before I merged

**Comment by msmith-techempower** [comment]
@nbrady-techempower I looked through these changes the other day and while there are a LOT of moving pieces, I believe they are okay to merge. LGTM!

**Comment by mwpastore** [comment]
@nbrady-techempower @msmith-techempower Are you referring to #1789? This PR is just JRuby compatibility for the new sinatra-sequel framework (and related changes). #1789 is the big kahuna. Anyway, I see that this one was merged. Thank you!

**Pull request merged**
