### PR TITLE
add Nim's web framework "mofuw" on Docker

### PR DESCRIPTION
**Pull request by 2vg**
add Nim's web framework "mofuw", currently include plaintext

### CODE REVIEW

**Comment by 2vg** [comment]
plaintext tests not passed...

**Comment by nbrady-techempower** [comment]
Looks like everything is passing now! Do you plan on introducing more than just the plaintext tests?

**Comment by RX14** [comment]
```
================================================================================
  Verification Summary
| Test: mofuw
|      NO RESULTS (Did framework launch?)
================================================================================
```

Didn't pass, the exit codes are just broken.

**Comment by msmith-techempower** [comment]
@nbrady-techempower Don't trust the checkmarks; @RX14 is correct.

**Comment by nbrady-techempower** [comment]
@2vg Sorry about that. Please open a new PR when you have a chance. The error message looks like something that happens in Nim but I haven't the slightest: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

**Comment by 2vg** [comment]
There is no problem in my local environment…

I look for cause and submit new PR soon.

**Comment by 2vg** [comment]
@nbrady-techempower hi, this result is OK ?
default

**Comment by nbrady-techempower** [comment]
@2vg yes that result would be ok

**Pull request merged**
