### PR TITLE
Update vertx entry

### PR DESCRIPTION
**Pull request by vietj**
Update the vertx benchmark to the latest released version and support Postgres database tests.

### CODE REVIEW

**Comment by vietj** [comment]
where can we get the details of the failure ?

**Comment by RX14** [comment]
[here](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/builds/275084636). vertx wasn't the framework to fail, it can probably be ignored.

**Comment by vietj** [comment]
@RX14 how can it be determined that it's not a vertx failure ? I don't see any log in Travis that gives details.

Should I resubmit a new identical PR or will this be merged ?

**Comment by nbrady-techempower** [comment]
@vietj If you click on the `X` near your commit or the `details` you should see an entire list of all the frameworks that ran. One of the other frameworks ran that didn't need to and it failed. Vertx passed.

**Pull request merged**
