### PR TITLE
Upgrade ffead-cpp to v5.2

### PR DESCRIPTION
**Pull request by sumeetchhetri**
Multiple performance fixes

### CODE REVIEW

**Comment by sumeetchhetri** [comment]
@nbrady-techempower, please merge if travis is green!!

**Comment by nbrady-techempower** [comment]
That’s not how it works, friend. 57 files changed. I’ll review when I have a chance on Monday.

**Comment by sumeetchhetri** [comment]
Sure Thanks.

**Comment by nbrady-techempower** [comment]
@sumeetchhetri haha no worries ;) But, travis is not green :(

**Comment by sumeetchhetri** [comment]
@nbrady-techempower, travis seems to be green now, will wait for your review before these changes are merged.

**Comment by nbrady-techempower** [comment]
@sumeetchhetri Everything looks fine, but can you remove the `frameworks/C++/ffead-cpp/postgresql/` directory please.

**Comment by sumeetchhetri** [comment]
Done as requested.

**Pull request merged**
