### PR TITLE
Swoole send error

### PR DESCRIPTION
**Pull request by joanhey**
Actually Swoole don't send any error, so we think that all is correct.
But the log is full of errors:
https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/swoole/run/swoole.log

This change try to return the errors.
If the errors don't appear in the log, later we will investigate how to show it in the log too.

Unfortunately almost all frameworks using Swoole have the same behavior.
https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/hamlet-swoole/run/hamlet-swoole.log

https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/laravel-swoole/run/laravel-swoole.log

https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/sw-fw-less/run/sw-fw-less.log
....

### CODE REVIEW

**Comment by joanhey** [comment]
Ping 
@vasily-kartashov Hamlet

**Comment by joanhey** [comment]
Ping:
@jcheron Ubiquity
https://tfb-status.techempower.com/unzip/results.2019-10-05-23-14-37-606.zip/results/20191002030153/ubiquity-swoole/run/ubiquity-swoole.log

**Comment by joanhey** [comment]
Watch the results:
https://www.techempower.com/benchmarks/#section=test&runid=42f65a64-69b2-400d-b24e-20ecec9848bc&hw=ph&test=fortune&p=zik0zj-zik0zj-zik0zj-zik06n-f

We can check the erors for: php-raw7-tcp, phpixie and CodeIgniter.
And from sw-fw-less, that use Swoole and do it correctly.

Also I suspect that swoole is sending empty responses when find an error. So the benchmark it is not correct. The wrk don't check the response.

**Comment by jcheron** [comment]
The errors 
`Error 1004 or 1005: swFactoryProcess_finish...` 
present for Swoole and Laravel are due to the fact that **Wrk** closes the connection at the end of the time limit (see https://github.com/swoole/swoole-src/issues/2407).

I think it is possible to disable them by setting the log_level to the highest level.
```php
$serv->set(array(
    log_level' => 5,
));
```
This is what I did for Ubiquity, and this message does not appear in the logs.
Generally, errors that cause logs are disastrous for performance.

This is what I did for Ubiquity, and this message does not appear in the logs.
Generally, errors that cause logs are disastrous for performance.

The `Swoole` and `Hamlet` errors look like a server saturation: the connection could not be made and the db object returns false.

For the last Ubiquity run, I logically create the 512 connections to the db distributed among the Workers, at the start of the Workers (to avoid overloading).
I don't yet know why errors have occurred.

**Comment by joanhey** [comment]
@jcheron Hi
Still Uncaught Exception errors that are not showed in the table.
https://tfb-status.techempower.com/unzip/results.2019-10-15-10-19-34-110.zip/results/20191011190615/ubiquity-swoole/run/ubiquity-swoole.log

Hamlet show the errors now #5142, and also have better results, because don't need to log all the errors.

Before:
https://www.techempower.com/benchmarks/#section=test&runid=97ff3ef2-df44-4e39-9dbf-bab1321c8ee6&hw=ph&test=db&l=zik073-v&p=zik0zj-zik0zj-zik0zj-zik073-v

After:
https://www.techempower.com/benchmarks/#section=test&runid=8aaf581a-45f8-4d19-bb49-95c7900b8ce3&hw=ph&test=db&l=zik073-v&p=zik0zj-zik0zj-zik0zj-zik073-v

**Comment by jcheron** [comment]
Hi @joanhey (Sorry for my impoliteness)
These `Ubiquity-swoole` lines are executed on the php-cli side (and not for each Http request).
The Pool initialization is done in the `onWorkerStart` event.
Exception handling will not change anything here, it is my own code that generates this exception:
```php
$db=$this->createDbInstance();
if($db!==false){
	$this->pool->push($db);
	$capacity--;
}else{
	throw new \RuntimeException('failed to connect to DB server.');
}
```

And I have a lot of difficulty understanding the stack trace that changes the value of a variable during execution:
The value `18` passed to `initPooling` becomes a `7` when the pool constructor is scalled!!!!!

>ubiquity-swoole: Stack trace:
ubiquity-swoole: #0 /ubiquity/vendor/phpmv/ubiquity/src/Ubiquity/orm/traits/DAOPooling.php(38): Ubiquity\db\pooling\AbstractConnectionPool->__construct(Array, 'swoole', 7)
ubiquity-swoole: #1 /ubiquity/app/config/services.php(6): Ubiquity\orm\DAO::initPooling(Array, 'swoole', 18)
ubiquity-swoole: #2 {main}

**Comment by joanhey** [comment]
The log file use 15.2 MB, the maximum in tfb-status.

**Pull request merged**
