### PR TITLE
Upgrade undertow

### PR DESCRIPTION
**Pull request by greg-hellings**
Upgrade undertow and requisite libraries to their latest versions compatible with Java 7. In my test environments I'm seeing about a 4-5% performance boost with these latest library versions.

### CODE REVIEW

**Comment by hamiltont** [comment]
Wow, your latest commit literally appeared while I was hovering over the merge button, guess I'll wait to see if travis ok's the latest :-P

I guess these improvements don't apply to `undertow-edge`?

**Comment by greg-hellings** [comment]
From what I'm seeing at https://repository.jboss.org/nexus/content/groups/public/org/jboss/xnio/xnio-native/ it appears that xnio-native was never updated. The other surrounding libraries could mostly be updated along the same lines, but I'd have to dig deeper to see if xnio-native (aka edge) was abandoned by JBoss.

**Comment by hamiltont** [comment]
Coolio, just checking we were not missing something obvious

**Comment by hamiltont** [comment]
thanks!

**Pull request merged**
