### PR TITLE
bottle ujson optional dependency

### PR DESCRIPTION
**Pull request by kianxineki**
increment speed for json response
https://github.com/bottlepy/bottle/blob/master/bottle.py#L82
https://github.com/bottlepy/bottle/pull/933

### CODE REVIEW

**Comment by nbrady-techempower** [comment]
Hi @kianxineki - Would you mind merging in the latest master? It has travis updates that will fix some of the errors we're seeing here.

**Comment by kianxineki** [comment]
@nbrady-techempower It is done :)

**Comment by kianxineki** [comment]
@nbrady-techempower bottle test ok, travis failed :(

**Comment by nbrady-techempower** [comment]
@kianxineki Yeah, looks good! The merge kicked off a full travis run. Merging now, thanks!

**Pull request merged**
